"""
Shared plumbing for the per-week generator modules (generator/weekNN.py).

Each week module defines WEEK, TOPIC, OVERVIEW, and EXERCISES (a list of
exercise dicts) -- write_week() below turns that into the actual files:

    exercises/weekNN/README.md                  week overview + exercise list
    exercises/weekNN/exerciseXX/solution.py      stub, the entry point
    exercises/weekNN/exerciseXX/README.md        that exercise's own description
    reference_solutions/weekNN/exerciseXX/solution.py
    tests/test_weekNN_exerciseXX.py              that ONE exercise's tests

Every exercise lives in its own folder specifically so a trainee can add
helper submodules next to solution.py (e.g. exercises/week04/exercise02/helpers.py)
without that ever colliding with another exercise's files. solution.py stays
the one filename tests import from in every exercise, in every week.

Tests are one file per exercise, not one aggregated file per week, so
"weekNN_exerciseXX" is a first-class, independently-runnable test target
(`python tools/cli.py test week01_exercise03`) alongside the existing
week-level target "weekNN" (`tools/core.py` runs every exercise test file
for that week when asked for the plain week id -- see run_week_tests()).
This is what lets the git hooks test at two different granularities: a
pre-commit hook can test only the specific exercise(s) just staged, while
a pre-push hook tests the whole week for any exercise touched in it.
"""
import os

STUB_HEADER = '''"""
{title}
Implement the function(s)/class(es) below.

IMPORTANT: do not add an `if __name__ == "__main__":` block to this file.
It must stay a plain importable module -- the test suite in
tests/test_{week}_{exercise}.py imports directly from here. Need a helper
function or class of your own? Add another .py file next to this one inside
exercises/{week}/{exercise}/ and import it as a submodule (e.g.
`from exercises.{week}.{exercise} import helpers`) -- solution.py just has to
stay the entry point these tests import from.
"""


'''


def write_week(root, week, topic, overview, exercises):
    ex_week_dir = os.path.join(root, "exercises", week)
    ref_week_dir = os.path.join(root, "reference_solutions", week)
    tests_dir = os.path.join(root, "tests")
    os.makedirs(ex_week_dir, exist_ok=True)
    os.makedirs(ref_week_dir, exist_ok=True)

    # Older generations of this week wrote one aggregated tests/test_weekNN.py
    # instead of one file per exercise -- remove it so pytest doesn't also
    # pick up stale, duplicate copies of these same tests.
    stale_aggregate = os.path.join(tests_dir, f"test_{week}.py")
    if os.path.exists(stale_aggregate):
        os.remove(stale_aggregate)

    listing = "\n".join(
        f"- **`{ex['name']}/`** -- {ex['summary']}" for ex in exercises
    )
    with open(os.path.join(ex_week_dir, "README.md"), "w") as f:
        f.write(
            f"# {topic}\n\n{overview}\n\n"
            f"## Exercises\n\n"
            f"Each exercise below lives in its own folder with its own "
            f"`solution.py` (the entry point) and `README.md` (the problem "
            f"statement), and is independently testable with "
            f"`python tools/cli.py test {week}_exerciseXX`. Work through "
            f"them in order.\n\n"
            f"{listing}\n"
        )

    for ex in exercises:
        name = ex["name"]
        ex_dir = os.path.join(ex_week_dir, name)
        ref_dir = os.path.join(ref_week_dir, name)
        os.makedirs(ex_dir, exist_ok=True)
        os.makedirs(ref_dir, exist_ok=True)

        with open(os.path.join(ex_dir, "solution.py"), "w") as f:
            f.write(
                STUB_HEADER.format(
                    title=f"{topic} -- {ex['title']}", week=week, exercise=name
                )
                + ex["stub"]
            )
        with open(os.path.join(ex_dir, "README.md"), "w") as f:
            f.write(f"# {ex['title']}\n\n{ex['readme']}\n")
        with open(os.path.join(ref_dir, "solution.py"), "w") as f:
            f.write(ex["reference"])

        test_content = (
            f'"""\n'
            f"Tests for {week}/{name} -- {topic}: {ex['title']}.\n"
            f"Auto-generated by generate.py from generator/{week}.py -- edit "
            f"that file, not this one, then re-run `python generate.py`.\n"
            f'"""\n\n'
        ) + ex["test"]
        with open(os.path.join(tests_dir, f"test_{week}_{name}.py"), "w") as f:
            f.write(test_content)
