"""
Shared plumbing for the per-week generator modules (generator/weekNN.py).

Each week module defines WEEK, TOPIC, OVERVIEW, and EXERCISES (a list of
exercise dicts) -- write_week() below turns that into the actual files:

    exercises/weekNN/README.md                  week overview + exercise list
    exercises/weekNN/exerciseXX/solution.py      stub, the entry point
    exercises/weekNN/exerciseXX/README.md        that exercise's own description
    reference_solutions/weekNN/exerciseXX/solution.py
    tests/test_weekNN.py                         ALL exercises' tests, aggregated

Every exercise lives in its own folder specifically so a trainee can add
helper submodules next to solution.py (e.g. exercises/week04/exercise02/helpers.py)
without that ever colliding with another exercise's files. solution.py stays
the one filename tests import from in every exercise, in every week.
"""
import os

STUB_HEADER = '''"""
{title}
Implement the function(s)/class(es) below.

IMPORTANT: do not add an `if __name__ == "__main__":` block to this file.
It must stay a plain importable module -- the aggregated test suite in
tests/test_{week}.py imports directly from here. Need a helper function or
class of your own? Add another .py file next to this one inside
exercises/{week}/{exercise}/ and import it as a submodule (e.g.
`from exercises.{week}.{exercise} import helpers`) -- solution.py just has to
stay the entry point these tests import from.
"""


'''


def write_week(root, week, topic, overview, exercises):
    ex_week_dir = os.path.join(root, "exercises", week)
    ref_week_dir = os.path.join(root, "reference_solutions", week)
    os.makedirs(ex_week_dir, exist_ok=True)
    os.makedirs(ref_week_dir, exist_ok=True)

    listing = "\n".join(
        f"- **`{ex['name']}/`** -- {ex['summary']}" for ex in exercises
    )
    with open(os.path.join(ex_week_dir, "README.md"), "w") as f:
        f.write(
            f"# {topic}\n\n{overview}\n\n"
            f"## Exercises\n\n"
            f"Each exercise below lives in its own folder with its own "
            f"`solution.py` (the entry point) and `README.md` (the problem "
            f"statement). Work through them in order.\n\n"
            f"{listing}\n"
        )

    test_chunks = [
        f'"""\n'
        f"Aggregated tests for {week} -- {topic}.\n"
        f"Auto-generated by generate.py from generator/{week}.py -- edit that "
        f"file, not this one, then re-run `python generate.py`.\n"
        f'"""\n'
    ]

    for ex in exercises:
        name = ex["name"]
        ex_dir = os.path.join(ex_week_dir, name)
        ref_dir = os.path.join(ref_week_dir, name)
        os.makedirs(ex_dir, exist_ok=True)
        os.makedirs(ref_dir, exist_ok=True)

        with open(os.path.join(ex_dir, "solution.py"), "w") as f:
            f.write(
                STUB_HEADER.format(
                    title=f"{topic} -- {ex['title']}", week=week, exercise=name
                )
                + ex["stub"]
            )
        with open(os.path.join(ex_dir, "README.md"), "w") as f:
            f.write(f"# {ex['title']}\n\n{ex['readme']}\n")
        with open(os.path.join(ref_dir, "solution.py"), "w") as f:
            f.write(ex["reference"])

        test_chunks.append(
            f"\n# {'-' * 66} {name}: {ex['title']}\n" + ex["test"]
        )

    with open(os.path.join(root, "tests", f"test_{week}.py"), "w") as f:
        f.write("\n".join(test_chunks))
