"""
Tests for week03/exercise02 -- Functions: Args and Kwargs.
Auto-generated by generate.py from generator/week03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week03.exercise02.solution import sum_all, build_config, describe_call


def test_sum_all():
    assert sum_all(1, 2, 3) == 6
    assert sum_all() == 0


def test_build_config():
    assert build_config(host="x", port=1) == {"host": "x", "port": 1}


def test_describe_call():
    assert describe_call(1, 2, key="value") == "args=(1, 2), kwargs={'key': 'value'}"
