"""
Tests for stage06/tier3_advanced02 -- OOP I: Descriptors Preview: Typed.
Auto-generated by generate.py from generator/stage06.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage06.tier3_advanced02.solution import Person


def test_typed_descriptor_get_set():
    """name/age read/write through Typed's __get__/__set__."""
    person = Person("Ada", 30)
    assert person.name == "Ada"
    assert person.age == 30


def test_typed_descriptor_rejects_wrong_type():
    """__set__ must raise TypeError when the value doesn't match expected_type."""
    person = Person("Ada", 30)
    with pytest.raises(TypeError):
        person.age = "thirty"


def test_typed_descriptor_rejects_at_construction():
    """__init__ assigns through the descriptors, so construction validates types too."""
    with pytest.raises(TypeError):
        Person("Ada", "thirty")


def test_same_descriptor_class_reused_with_different_expected_types():
    """Typed is reused for both name (str) and age (int) -- each enforcing its own configured type independently."""
    person = Person("Ada", 30)
    with pytest.raises(TypeError):
        person.name = 123
    person.age = 31
    assert person.age == 31
