"""
Tests for stage06/mid01 -- OOP I: Slotted Geometry.
Auto-generated by generate.py from generator/stage06.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage06.mid01.solution import PointSlots, Vector3DSlots


def test_point_slots_basic():
    """__init__ sets x/y via __slots__-declared attributes."""
    p = PointSlots(1, 2)
    assert (p.x, p.y) == (1, 2)


def test_point_slots_has_no_dict():
    """__slots__ replaces the per-instance __dict__ entirely."""
    p = PointSlots(1, 2)
    assert not hasattr(p, "__dict__")


def test_point_slots_rejects_new_attribute():
    """Setting an attribute not named in __slots__ must raise AttributeError."""
    p = PointSlots(1, 2)
    with pytest.raises(AttributeError):
        p.z = 3


def test_vector3d_slots_magnitude():
    """magnitude() == (x**2 + y**2 + z**2) ** 0.5."""
    v = Vector3DSlots(2, 3, 6)
    assert v.magnitude() == 7.0
