"""
Tests for stage02/tier2_mid02 -- Control Flow: Inventory Restock Matcher.
Auto-generated by generate.py from generator/stage02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import exercises.stage02.tier2_mid02.solution as solution


def test_out_of_stock_index_via_while_else():
    """out_of_stock_index is the first index where stock_levels[i] == 0 (while...else, break)."""
    assert solution.out_of_stock_index == 1


def test_needs_urgent_reorder_short_circuit():
    """One `and` expression: out_of_stock_index != -1 guards the item_names indexing on the right."""
    assert solution.needs_urgent_reorder is True


def test_stock_status_ternary():
    """stock_status == "critical" if out_of_stock_index != -1 else "ok", as a ternary expression."""
    assert solution.stock_status == "critical"


def test_low_stock_items_via_zip():
    """low_stock_items built by walking zip(item_names, stock_levels), not manual indexing."""
    assert solution.low_stock_items == ["screws", "nuts"]
