"""
Tests for stage10/exercise04 -- Pandas: Merging and Pivoting.
Auto-generated by generate.py from generator/stage10.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pandas as pd
from exercises.stage10.exercise04.solution import (
    merge_customer_info,
    merge_with_suffixes,
    inner_join_products,
    sales_pivot_table,
    sales_pivot_count,
)


def test_merge_customer_info():
    orders = pd.DataFrame({"customer_id": [1, 2], "amount": [50, 75]})
    customers = pd.DataFrame({"customer_id": [1, 2], "name": ["Ada", "Grace"]})
    result = merge_customer_info(orders, customers)
    assert list(result["name"]) == ["Ada", "Grace"]


def test_merge_with_suffixes_keeps_unmatched_left_rows():
    df1 = pd.DataFrame({"id": [1, 2, 3], "value": ["a", "b", "c"]})
    df2 = pd.DataFrame({"id": [1, 2], "value": ["x", "y"]})
    result = merge_with_suffixes(df1, df2)
    assert len(result) == 3
    assert "value_left" in result.columns and "value_right" in result.columns


def test_inner_join_products_drops_unmatched():
    orders = pd.DataFrame({"product_id": [1, 2, 3]})
    products = pd.DataFrame({"product_id": [1, 2], "name": ["Widget", "Gadget"]})
    result = inner_join_products(orders, products)
    assert len(result) == 2


def _pivot_sample_df():
    return pd.DataFrame({
        "region": ["east", "east", "west"],
        "product": ["A", "B", "A"],
        "sales": [100, 50, 200],
    })


def test_sales_pivot_table():
    result = sales_pivot_table(_pivot_sample_df())
    assert result.loc["east", "A"] == 100
    assert result.loc["west", "A"] == 200


def test_sales_pivot_count():
    result = sales_pivot_count(_pivot_sample_df())
    assert result.loc["east", "A"] == 1
