"""
Tests for stage08/basic02 -- The Python Data Model: PlayingCard: repr, str, eq.
Auto-generated by generate.py from generator/stage08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage08.basic02.solution import PlayingCard


def test_repr_uses_bang_r_formatting():
    """__repr__ must use !r on rank/suit, so the result is valid Python (quoted strings) that recreates the object."""
    assert repr(PlayingCard("A", "Spades")) == "PlayingCard('A', 'Spades')"


def test_str_is_human_friendly():
    """__str__ must be f"{rank} of {suit}"."""
    assert str(PlayingCard("A", "Spades")) == "A of Spades"


def test_eq_compares_rank_and_suit():
    """__eq__ must compare BOTH rank and suit, not just one."""
    assert PlayingCard("A", "Spades") == PlayingCard("A", "Spades")
    assert PlayingCard("A", "Spades") != PlayingCard("A", "Hearts")
    assert PlayingCard("A", "Spades") != PlayingCard("K", "Spades")
