"""
Tests for stage02/exercise02 -- Control Flow: Loop Controls.
Auto-generated by generate.py from generator/stage02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage02.exercise02.solution import (
    sum_until_negative,
    skip_multiples,
    countdown,
    safe_int_list,
)


def test_sum_until_negative():
    assert sum_until_negative([1, 2, 3, -1, 10]) == 6


def test_sum_until_negative_no_negatives():
    assert sum_until_negative([1, 2, 3]) == 6


def test_skip_multiples():
    assert skip_multiples([1, 2, 3, 4, 5, 6], 3) == [1, 2, 4, 5]


def test_countdown():
    assert countdown(5) == [5, 4, 3, 2, 1]


def test_safe_int_list():
    assert safe_int_list(["1", "2", "oops", "3", None]) == [1, 2, 3]
