"""
Tests for stage05/mid02 -- Files, Exceptions, Regex: Config and Log Parsers.
Auto-generated by generate.py from generator/stage05.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage05.mid02.solution import parse_config_line, find_date, parse_log_entry


def test_parse_config_line_uses_compiled_pattern_and_named_groups():
    """parse_config_line matches LINE_PATTERN (a compiled, named-group pattern) and returns groupdict()."""
    assert parse_config_line("host=localhost") == {"key": "host", "value": "localhost"}


def test_parse_config_line_invalid_raises():
    """No match against LINE_PATTERN must raise ValueError."""
    with pytest.raises(ValueError):
        parse_config_line("not-key-value")


def test_find_date_searches_anywhere_in_text():
    """find_date uses DATE_PATTERN.search (not .match), so it finds a date anywhere in the text."""
    result = find_date("event happened on 2024-03-15 in the evening")
    assert result == {"year": "2024", "month": "03", "day": "15"}


def test_find_date_none_found_raises():
    """No date found must raise ValueError."""
    with pytest.raises(ValueError):
        find_date("no date here")


def test_parse_log_entry_uses_compiled_pattern_and_named_groups():
    """parse_log_entry matches LOG_PATTERN and returns its groupdict()."""
    assert parse_log_entry("ERROR: disk full") == {"level": "ERROR", "message": "disk full"}


def test_parse_log_entry_invalid_raises():
    """No match against LOG_PATTERN must raise ValueError."""
    with pytest.raises(ValueError):
        parse_log_entry("not a log line")
