"""
Tests for stage10/tier2_mid02 -- Pandas: Sorting, Grouping, and Merging.
Auto-generated by generate.py from generator/stage10.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pandas as pd
from exercises.stage10.tier2_mid02.solution import (
    sort_by_sales_desc,
    sort_by_multiple,
    total_sales_by_region,
    merge_customer_info,
    inner_join_products,
)


def _group_sample_df():
    return pd.DataFrame({
        "region": ["east", "west", "east", "west", "east"],
        "product": ["A", "A", "B", "B", "A"],
        "sales": [100, 250, 50, 300, 150],
    })


def test_sort_by_sales_desc():
    """sort_by_sales_desc == df.sort_values("sales", ascending=False)."""
    result = sort_by_sales_desc(_group_sample_df())
    assert list(result["sales"]) == [300, 250, 150, 100, 50]


def test_sort_by_multiple():
    """sort_by_multiple sorts by region ascending, then sales descending within each region."""
    result = sort_by_multiple(_group_sample_df())
    assert list(result["region"]) == ["east", "east", "east", "west", "west"]
    assert list(result["sales"])[:3] == [150, 100, 50]


def test_total_sales_by_region():
    """total_sales_by_region == df.groupby("region")["sales"].sum()."""
    result = total_sales_by_region(_group_sample_df())
    assert result["east"] == 300
    assert result["west"] == 550


def test_merge_customer_info():
    """merge_customer_info == orders_df.merge(customers_df, on="customer_id") -- an inner join."""
    orders = pd.DataFrame({"customer_id": [1, 2], "amount": [50, 75]})
    customers = pd.DataFrame({"customer_id": [1, 2], "name": ["Ada", "Grace"]})
    result = merge_customer_info(orders, customers)
    assert list(result["name"]) == ["Ada", "Grace"]


def test_inner_join_products_drops_unmatched():
    """inner_join_products must use how="inner" -- unmatched rows are dropped."""
    orders = pd.DataFrame({"product_id": [1, 2, 3]})
    products = pd.DataFrame({"product_id": [1, 2], "name": ["Widget", "Gadget"]})
    result = inner_join_products(orders, products)
    assert len(result) == 2
