"""
Tests for stage11/tier1_basic01 -- OpenCV: Hand Posture & Face Gesture Recognition: Loading and Inspecting Camera Frames.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import numpy as np
from exercises.stage11.tier1_basic01.solution import (
    load_frame,
    save_frame,
    get_frame_dimensions,
    create_blank_frame,
    crop_to_roi,
)


def test_save_and_load_roundtrip(tmp_path):
    """save_frame/load_frame round-trip via cv2.imwrite/cv2.imread."""
    path = str(tmp_path / "frame.png")
    original = np.zeros((20, 30, 3), dtype=np.uint8)
    original[:, :] = (0, 0, 255)
    assert save_frame(path, original) is True
    loaded = load_frame(path)
    assert loaded is not None
    assert loaded.shape == (20, 30, 3)


def test_load_missing_file_returns_none():
    """cv2.imread must return None (not raise) for a missing file."""
    assert load_frame("/nonexistent/path/to/frame.png") is None


def test_get_frame_dimensions_is_height_then_width():
    """get_frame_dimensions == frame.shape[:2] -- height first, not (width, height)."""
    frame = np.zeros((20, 30, 3), dtype=np.uint8)
    assert get_frame_dimensions(frame) == (20, 30)


def test_create_blank_frame():
    """create_blank_frame == np.zeros((height, width, 3), dtype=np.uint8)."""
    frame = create_blank_frame(10, 20)
    assert frame.shape == (10, 20, 3)
    assert frame.sum() == 0


def test_crop_to_roi_is_plain_array_slicing():
    """crop_to_roi must be frame[y1:y2, x1:x2] -- rows before columns."""
    frame = np.arange(100).reshape(10, 10).astype(np.uint8)
    cropped = crop_to_roi(frame, 2, 5, 3, 6)
    assert cropped.shape == (3, 3)
