"""
Tests for stage03/exercise03 -- Functions: Lambdas and Higher-Order Functions.
Auto-generated by generate.py from generator/stage03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage03.exercise03.solution import (
    make_multiplier,
    sort_by_length,
    top_scorer,
)


def test_make_multiplier():
    double = make_multiplier(2)
    assert double(5) == 10
    triple = make_multiplier(3)
    assert triple(5) == 15


def test_sort_by_length():
    assert sort_by_length(["ccc", "a", "bb"]) == ["a", "bb", "ccc"]


def test_top_scorer():
    records = [{"name": "a", "score": 10}, {"name": "b", "score": 30}, {"name": "c", "score": 20}]
    assert top_scorer(records) == {"name": "b", "score": 30}
