"""
Tests for week12/exercise02 -- Requests + Threading: Sessions and Retry/Backoff.
Auto-generated by generate.py from generator/week12.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from unittest.mock import Mock, patch
import pytest
import requests
from exercises.week12.exercise02.solution import (
    make_default_session,
    create_session_with_headers,
    fetch_multiple_with_session,
    fetch_with_retry,
)


def test_make_default_session():
    assert isinstance(make_default_session(), requests.Session)


def test_create_session_with_headers():
    session = create_session_with_headers({"Authorization": "Bearer token"})
    assert session.headers["Authorization"] == "Bearer token"


def test_fetch_multiple_with_session():
    fake_response = Mock()
    fake_response.json.return_value = {"ok": True}
    with patch.object(requests.Session, "get", return_value=fake_response) as mock_get:
        result = fetch_multiple_with_session(["https://a.test", "https://b.test"])
    assert result == [{"ok": True}, {"ok": True}]
    assert mock_get.call_count == 2


def test_fetch_with_retry_succeeds_after_failures(monkeypatch):
    monkeypatch.setattr("time.sleep", lambda seconds: None)
    fake_response = Mock()
    fake_response.raise_for_status.return_value = None
    fake_response.json.return_value = {"ok": True}

    call_count = {"n": 0}

    def flaky_get(url):
        call_count["n"] += 1
        if call_count["n"] < 3:
            raise requests.exceptions.ConnectionError("boom")
        return fake_response

    with patch("requests.get", side_effect=flaky_get):
        result = fetch_with_retry("https://example.test", max_attempts=5)
    assert result == {"ok": True}
    assert call_count["n"] == 3


def test_fetch_with_retry_raises_after_exhausting_attempts(monkeypatch):
    monkeypatch.setattr("time.sleep", lambda seconds: None)
    with patch("requests.get", side_effect=requests.exceptions.ConnectionError("boom")):
        with pytest.raises(requests.exceptions.RequestException):
            fetch_with_retry("https://example.test", max_attempts=3)
