"""
Aggregated tests for week13 -- Local API Endpoints.
Auto-generated by generate.py from generator/week13.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: Basic Routes
from fastapi.testclient import TestClient
from exercises.week13.exercise01.solution import app as basic_routes_app

basic_routes_client = TestClient(basic_routes_app)


def test_read_root():
    assert basic_routes_client.get("/").json() == {"message": "hello"}


def test_read_item_path_parameter():
    assert basic_routes_client.get("/items/42").json() == {"item_id": 42}


def test_search_query_parameter():
    assert basic_routes_client.get("/search?q=python").json() == {"q": "python"}


def test_search_default_query_parameter():
    assert basic_routes_client.get("/search").json() == {"q": ""}


def test_echo_post():
    assert basic_routes_client.post("/echo", json={"a": 1}).json() == {"a": 1}


# ------------------------------------------------------------------ exercise02: Pydantic Models
from fastapi.testclient import TestClient
from exercises.week13.exercise02.solution import app as models_app

models_client = TestClient(models_app)


def test_create_item_defaults_in_stock_true():
    response = models_client.post("/items", json={"name": "Widget", "price": 9.99})
    assert response.json() == {"name": "Widget", "price": 9.99, "in_stock": True}


def test_create_item_validation_rejects_missing_field():
    response = models_client.post("/items", json={"name": "Widget"})
    assert response.status_code == 422


def test_create_user():
    response = models_client.post("/users", json={"username": "ada", "age": 30})
    assert response.json() == {"username": "ada", "age": 30}


def test_login_never_echoes_password():
    response = models_client.post("/login", json={"username": "ada", "password": "secret"})
    data = response.json()
    assert data == {"ok": True, "username": "ada"}
    assert "password" not in data


# ------------------------------------------------------------------ exercise03: Dependency Injection
from fastapi.testclient import TestClient
from exercises.week13.exercise03.solution import app as di_app

di_client = TestClient(di_app)


def test_paginated_defaults():
    assert di_client.get("/paginated").json() == {"page": 1, "size": 10}


def test_paginated_custom_values():
    assert di_client.get("/paginated?page=3&size=20").json() == {"page": 3, "size": 20}


def test_status_depends_on_get_db():
    assert di_client.get("/status").json() == {"connected": True}


def test_protected_without_token():
    assert di_client.get("/protected").json() == {"error": "unauthorized"}


def test_protected_with_correct_token():
    response = di_client.get("/protected?token=secret")
    assert response.json() == {"data": "secret data"}


# ------------------------------------------------------------------ exercise04: Async Endpoints
from fastapi.testclient import TestClient
from exercises.week13.exercise04.solution import app as async_app

async_client = TestClient(async_app)


def test_async_hello():
    assert async_client.get("/async-hello").json() == {"message": "hello async"}


def test_async_get_item():
    assert async_client.get("/async-items/7").json() == {"item_id": 7}


def test_async_echo():
    assert async_client.post("/async-echo", json={"x": 1}).json() == {"x": 1}


# ------------------------------------------------------------------ exercise05: TestClient, Docs, and uvicorn.run
from unittest.mock import patch
from exercises.week13.exercise05.solution import (
    app,
    get_health_status,
    get_openapi_schema,
    docs_page_status,
    run_server,
)


def test_get_health_status():
    assert get_health_status(app) == {"status": "ok"}


def test_get_openapi_schema_has_health_path():
    schema = get_openapi_schema(app)
    assert "/health" in schema["paths"]


def test_docs_page_status():
    assert docs_page_status(app) == 200


def test_run_server_calls_uvicorn_run_without_starting_a_server():
    with patch("uvicorn.run") as mock_run:
        run_server(app, host="0.0.0.0", port=9000)
    mock_run.assert_called_once_with(app, host="0.0.0.0", port=9000)
