"""
Tests for stage01/basic01 -- Python Fundamentals: Road Trip Fuel Ledger.
Auto-generated by generate.py from generator/stage01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest

import exercises.stage01.basic01.solution as solution


def test_casts_to_correct_types():
    assert isinstance(solution.distance_km, float)
    assert isinstance(solution.fuel_efficiency_l_per_100km, float)
    assert isinstance(solution.fuel_price_per_liter, float)
    assert isinstance(solution.passengers, int)
    assert not isinstance(solution.passengers, bool)


def test_is_price_a_float_flag():
    assert solution.is_price_a_float is True


def test_total_fuel_liters():
    assert solution.total_fuel_liters == pytest.approx(50.49)


def test_total_cost():
    assert solution.total_cost == pytest.approx(77.2497)


def test_cost_per_passenger():
    assert solution.cost_per_passenger == pytest.approx(25.7499)
