"""
Tests for stage02/exercise05 -- Control Flow: Short-Circuit Guards and Truthiness.
Auto-generated by generate.py from generator/stage02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage02.exercise05.solution import (
    is_valid_username,
    has_valid_first_item,
    is_within_bounds,
    describe_truthiness,
    filter_truthy,
    count_falsy,
)


def test_is_valid_username_true():
    assert is_valid_username("ada") is True


def test_is_valid_username_rejects_non_str():
    assert is_valid_username(123) is False


def test_is_valid_username_rejects_empty():
    assert is_valid_username("") is False


def test_has_valid_first_item_empty_list_is_safe():
    assert has_valid_first_item([]) is False


def test_has_valid_first_item_truthy_first():
    assert has_valid_first_item([1, 2]) is True


def test_is_within_bounds_out_of_range_is_safe():
    assert is_within_bounds([1, 2, 3], 10) is False


def test_is_within_bounds_true():
    assert is_within_bounds([1, 2, 3], 1) is True


def test_describe_truthiness():
    assert describe_truthiness(0) == "falsy"
    assert describe_truthiness("hi") == "truthy"
    assert describe_truthiness([]) == "falsy"


def test_filter_truthy():
    assert filter_truthy([0, 1, "", "a", None, 2]) == [1, "a", 2]


def test_count_falsy():
    assert count_falsy([0, 1, "", "a", None, 2]) == 3
