"""
Tests for week07/exercise04 -- OOP II: Abstract Base Classes.
Auto-generated by generate.py from generator/week07.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.week07.exercise04.solution import Shape, Circle, Square


def test_shape_cannot_be_instantiated():
    with pytest.raises(TypeError):
        Shape()


def test_circle_area_and_perimeter():
    c = Circle(2)
    assert round(c.area(), 2) == 12.57
    assert round(c.perimeter(), 2) == 12.57
    assert c.name() == "circle"


def test_square_area_and_perimeter():
    s = Square(4)
    assert s.area() == 16
    assert s.perimeter() == 16
    assert s.name() == "square"


def test_circle_and_square_are_shapes():
    assert isinstance(Circle(1), Shape)
    assert isinstance(Square(1), Shape)
