"""
Tests for stage09/mid01 -- OS, JSON, Datetime, XML: pathlib: The Modern os.path Alternative.
Auto-generated by generate.py from generator/stage09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pathlib
from exercises.stage09.mid01.solution import (
    list_entries,
    build_path,
    read_and_write_pathlib,
    find_txt_files,
)


def test_list_entries(tmp_path):
    """list_entries is the pathlib equivalent of os.listdir, via .iterdir()."""
    (tmp_path / "b.txt").write_text("b")
    (tmp_path / "a.txt").write_text("a")
    assert list_entries(str(tmp_path)) == ["a.txt", "b.txt"]


def test_build_path_uses_slash_operator_and_returns_a_path():
    """build_path must return an actual pathlib.Path, built with the / operator."""
    result = build_path("some/dir", "file.txt")
    assert isinstance(result, pathlib.Path)
    assert result.name == "file.txt"


def test_read_and_write_pathlib_roundtrip(tmp_path):
    """read_and_write_pathlib uses Path.write_text then Path.read_text, no open() needed."""
    path = tmp_path / "note.txt"
    result = read_and_write_pathlib(str(path), "hello")
    assert result == "hello"


def test_find_txt_files_recursive_glob(tmp_path):
    """find_txt_files uses Path.rglob("*.txt") to search recursively, with no manual os.walk loop."""
    (tmp_path / "a.txt").write_text("a")
    sub = tmp_path / "sub"
    sub.mkdir()
    (sub / "b.txt").write_text("b")
    (sub / "c.py").write_text("c")
    assert find_txt_files(str(tmp_path)) == ["a.txt", "b.txt"]
