"""
Aggregated tests for week02 -- Control Flow.
Auto-generated by generate.py from generator/week02.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: Number Patterns
from exercises.week02.exercise01.solution import fizzbuzz, is_prime


def test_fizzbuzz():
    assert fizzbuzz(15) == [
        "1", "2", "Fizz", "4", "Buzz", "Fizz", "7", "8", "Fizz", "Buzz",
        "11", "Fizz", "13", "14", "FizzBuzz",
    ]


def test_is_prime_true_cases():
    assert is_prime(2) is True
    assert is_prime(17) is True


def test_is_prime_false_cases():
    assert is_prime(1) is False
    assert is_prime(18) is False


# ------------------------------------------------------------------ exercise02: Loop Controls
from exercises.week02.exercise02.solution import (
    sum_until_negative,
    skip_multiples,
    countdown,
    safe_int_list,
)


def test_sum_until_negative():
    assert sum_until_negative([1, 2, 3, -1, 10]) == 6


def test_sum_until_negative_no_negatives():
    assert sum_until_negative([1, 2, 3]) == 6


def test_skip_multiples():
    assert skip_multiples([1, 2, 3, 4, 5, 6], 3) == [1, 2, 4, 5]


def test_countdown():
    assert countdown(5) == [5, 4, 3, 2, 1]


def test_safe_int_list():
    assert safe_int_list(["1", "2", "oops", "3", None]) == [1, 2, 3]


# ------------------------------------------------------------------ exercise03: Pairing and Indexing
from exercises.week02.exercise03.solution import (
    pair_names_scores,
    merge_records,
    count_equal_pairs,
    indexed_items,
    labeled_from,
)


def test_pair_names_scores():
    assert pair_names_scores(["a", "b"], [1, 2]) == [("a", 1), ("b", 2)]


def test_merge_records():
    assert merge_records(["x", "y"], [1, 2]) == {"x": 1, "y": 2}


def test_count_equal_pairs():
    assert count_equal_pairs([1, 2, 3], [1, 0, 3]) == 2


def test_indexed_items():
    assert indexed_items(["a", "b"]) == ["0: a", "1: b"]


def test_labeled_from():
    assert labeled_from(["a", "b"], 10) == {10: "a", 11: "b"}


# ------------------------------------------------------------------ exercise04: Ranges and Itertools
from exercises.week02.exercise04.solution import (
    stepped_range,
    numbered_multiples,
    cycle_colors,
    chain_lists,
    all_pairs,
)


def test_stepped_range():
    assert stepped_range(0, 10, 2) == [0, 2, 4, 6, 8]


def test_numbered_multiples():
    assert numbered_multiples(12, 3) == ["0: 3", "1: 6", "2: 9", "3: 12"]


def test_cycle_colors():
    assert cycle_colors(["red", "green"], 5) == ["red", "green", "red", "green", "red"]


def test_chain_lists():
    assert chain_lists([1, 2], [3, 4]) == [1, 2, 3, 4]


def test_all_pairs():
    assert all_pairs([1, 2], ["a", "b"]) == [(1, "a"), (1, "b"), (2, "a"), (2, "b")]


# ------------------------------------------------------------------ exercise05: Short-Circuit Guards and Truthiness
from exercises.week02.exercise05.solution import (
    is_valid_username,
    has_valid_first_item,
    is_within_bounds,
    describe_truthiness,
    filter_truthy,
    count_falsy,
)


def test_is_valid_username_true():
    assert is_valid_username("ada") is True


def test_is_valid_username_rejects_non_str():
    assert is_valid_username(123) is False


def test_is_valid_username_rejects_empty():
    assert is_valid_username("") is False


def test_has_valid_first_item_empty_list_is_safe():
    assert has_valid_first_item([]) is False


def test_has_valid_first_item_truthy_first():
    assert has_valid_first_item([1, 2]) is True


def test_is_within_bounds_out_of_range_is_safe():
    assert is_within_bounds([1, 2, 3], 10) is False


def test_is_within_bounds_true():
    assert is_within_bounds([1, 2, 3], 1) is True


def test_describe_truthiness():
    assert describe_truthiness(0) == "falsy"
    assert describe_truthiness("hi") == "truthy"
    assert describe_truthiness([]) == "falsy"


def test_filter_truthy():
    assert filter_truthy([0, 1, "", "a", None, 2]) == [1, "a", 2]


def test_count_falsy():
    assert count_falsy([0, 1, "", "a", None, 2]) == 3


# ------------------------------------------------------------------ exercise06: Ternary Expressions
from exercises.week02.exercise06.solution import grade_label, abs_value, clamp_to_range


def test_grade_label():
    assert grade_label(75) == "pass"
    assert grade_label(50) == "fail"


def test_abs_value():
    assert abs_value(5) == 5
    assert abs_value(-5) == 5
    assert abs_value(0) == 0


def test_clamp_to_range():
    assert clamp_to_range(15, 0, 10) == 10
    assert clamp_to_range(-5, 0, 10) == 0
    assert clamp_to_range(5, 0, 10) == 5


# ------------------------------------------------------------------ exercise07: The else Clause on Loops
from exercises.week02.exercise07.solution import (
    contains_value,
    all_positive,
    find_first_negative_index,
    retry_until_success,
    first_positive_index,
)


def test_contains_value_found():
    assert contains_value([1, 2, 3], 2) is True


def test_contains_value_not_found():
    assert contains_value([1, 2, 3], 9) is False


def test_all_positive_true():
    assert all_positive([1, 2, 3]) is True


def test_all_positive_false():
    assert all_positive([1, -2, 3]) is False


def test_find_first_negative_index_found():
    assert find_first_negative_index([1, 2, -3, 4]) == 2


def test_find_first_negative_index_none():
    assert find_first_negative_index([1, 2, 3]) == -1


def test_retry_until_success_true():
    assert retry_until_success([False, False, True]) is True


def test_retry_until_success_false():
    assert retry_until_success([False, False]) is False


def test_first_positive_index_found():
    assert first_positive_index([-1, -2, 3, 4]) == 2


def test_first_positive_index_none():
    assert first_positive_index([-1, -2]) == -1
