"""
Tests for stage06/advanced01 -- OOP I: Descriptors Preview: PositiveNumber.
Auto-generated by generate.py from generator/stage06.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage06.advanced01.solution import Product


def test_positive_number_descriptor_get_set():
    """price reads/writes through PositiveNumber's __get__/__set__, just like a @property would."""
    p = Product("Widget", 9.99)
    assert p.price == 9.99
    p.price = 19.99
    assert p.price == 19.99


def test_positive_number_descriptor_rejects_negative():
    """__set__ must raise ValueError for a negative value."""
    p = Product("Widget", 9.99)
    with pytest.raises(ValueError):
        p.price = -1


def test_positive_number_descriptor_rejects_at_construction():
    """__init__ assigns self.price through the descriptor, so construction validates too."""
    with pytest.raises(ValueError):
        Product("Widget", -5)
