"""
Tests for stage08/exercise02 -- The Python Data Model: Deck: A Collection Protocol.
Auto-generated by generate.py from generator/stage08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage08.exercise02.solution import Deck


def test_repr_and_str():
    d = Deck(["A", "K"])
    assert repr(d) == "Deck(['A', 'K'])"
    assert str(d) == "Deck of 2 cards"


def test_len_and_getitem():
    d = Deck(["A", "K", "Q"])
    assert len(d) == 3
    assert d[0] == "A"
    assert d[1:] == ["K", "Q"]


def test_deck_iter():
    d = Deck(["A", "K", "Q"])
    assert list(d) == ["A", "K", "Q"]


def test_deck_contains():
    d = Deck(["A", "K", "Q"])
    assert "K" in d
    assert "J" not in d


def test_add_concatenates():
    d1 = Deck(["A", "K"])
    d2 = Deck(["Q", "J"])
    combined = d1 + d2
    assert list(combined) == ["A", "K", "Q", "J"]
