"""
Tests for stage05/basic01 -- Files, Exceptions, Regex: Session Log Files.
Auto-generated by generate.py from generator/stage05.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage05.basic01.solution import (
    write_lines,
    read_lines,
    append_line,
    count_lines,
)


def test_write_and_read_lines(tmp_path):
    """write_lines/read_lines must each use `with open(...) as f:` -- writing "line\n" per entry, reading via f.read().splitlines()."""
    path = str(tmp_path / "data.txt")
    write_lines(path, ["a", "b", "c"])
    assert read_lines(path) == ["a", "b", "c"]


def test_append_line(tmp_path):
    """append_line opens in "a" mode and writes line + "\n" without truncating existing content."""
    path = str(tmp_path / "data.txt")
    write_lines(path, ["a"])
    append_line(path, "b")
    assert read_lines(path) == ["a", "b"]


def test_count_lines(tmp_path):
    """count_lines opens for reading and returns the number of lines."""
    path = str(tmp_path / "data.txt")
    write_lines(path, ["a", "b", "c", "d"])
    assert count_lines(path) == 4
