"""
Tests for stage09/mid02 -- OS, JSON, Datetime, XML: Timezone-Aware Timestamps in JSON.
Auto-generated by generate.py from generator/stage09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import json
import datetime
import pytest
from exercises.stage09.mid02.solution import (
    aware_now_utc,
    is_timezone_aware,
    make_aware,
    datetime_default,
    serialize_event,
)


def test_aware_now_utc_is_timezone_aware():
    """aware_now_utc() must produce a genuinely timezone-aware datetime."""
    assert is_timezone_aware(aware_now_utc()) is True


def test_make_aware_attaches_timezone_without_shifting_clock_time():
    """make_aware must attach tzinfo via .replace(), not shift the hour/minute."""
    naive = datetime.datetime(2024, 1, 1, 12, 0, 0)
    assert is_timezone_aware(naive) is False
    aware = make_aware(naive, datetime.timezone.utc)
    assert is_timezone_aware(aware) is True
    assert aware.hour == 12 and aware.year == 2024


def test_datetime_default_converts_to_isoformat():
    """datetime_default must return obj.isoformat() for a datetime.datetime."""
    dt = datetime.datetime(2024, 1, 1, 12, 0, 0, tzinfo=datetime.timezone.utc)
    assert datetime_default(dt) == "2024-01-01T12:00:00+00:00"


def test_datetime_default_raises_type_error_for_other_objects():
    """datetime_default must raise TypeError for anything that isn't a datetime.datetime."""
    with pytest.raises(TypeError):
        datetime_default("not a datetime")


def test_serialize_event_uses_datetime_default_under_the_hood():
    """serialize_event's json.dumps(default=datetime_default) must produce a valid JSON string with the ISO timestamp."""
    aware = make_aware(datetime.datetime(2024, 1, 1, 12, 0, 0), datetime.timezone.utc)
    result = serialize_event("launch", aware)
    assert json.loads(result) == {"name": "launch", "timestamp": "2024-01-01T12:00:00+00:00"}
