"""
Tests for stage11/tier3_advanced01 -- OpenCV: Hand Posture & Face Gesture Recognition: Hand Posture via Contours and Convexity Defects.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import math
import cv2
import numpy as np
from exercises.stage11.tier3_advanced01.solution import (
    preprocess_hand_mask,
    find_hand_contour,
    count_extended_fingers,
    classify_hand_posture,
)


def _fist_mask():
    mask = np.zeros((300, 300), dtype=np.uint8)
    cv2.circle(mask, (150, 150), 80, 255, -1)
    return mask


def _star_mask(num_points, canvas=300, cx=150, cy=150, outer_r=110, inner_r=35):
    """A num_points-pointed star: a hand silhouette stand-in with exactly
    num_points "fingertips" and num_points valleys between them, built from
    plain trigonometry so the expected convexity-defect count is exact."""
    pts = []
    n = num_points * 2
    for i in range(n):
        angle = math.pi / 2 + i * (2 * math.pi / n)
        r = outer_r if i % 2 == 0 else inner_r
        x = int(cx + r * math.cos(angle))
        y = int(cy - r * math.sin(angle))
        pts.append([x, y])
    mask = np.zeros((canvas, canvas), dtype=np.uint8)
    cv2.fillPoly(mask, [np.array(pts, dtype=np.int32)], 255)
    return mask


def test_preprocess_hand_mask_stays_binary_and_same_shape():
    """preprocess_hand_mask must blur then re-threshold, staying binary and same shape."""
    mask = _fist_mask()
    processed = preprocess_hand_mask(mask)
    assert processed.shape == mask.shape
    assert set(np.unique(processed)).issubset({0, 255})


def test_find_hand_contour_returns_the_largest_contour():
    """find_hand_contour must pick the largest contour by area."""
    mask = preprocess_hand_mask(_fist_mask())
    contour = find_hand_contour(mask)
    assert cv2.contourArea(contour) > 15000


def test_count_extended_fingers_on_a_fist():
    """A closed fist (a plain circle, no fingertip points) must report 0 extended fingers."""
    mask = preprocess_hand_mask(_fist_mask())
    assert count_extended_fingers(mask) == 0


def test_count_extended_fingers_on_a_three_point_star():
    """A 3-pointed star has exactly 3 deep valleys between its "fingertips"."""
    mask = preprocess_hand_mask(_star_mask(3))
    assert count_extended_fingers(mask) == 3


def test_count_extended_fingers_on_a_five_point_star():
    """A 5-pointed star (an "open hand" stand-in) has exactly 5 deep valleys."""
    mask = preprocess_hand_mask(_star_mask(5))
    assert count_extended_fingers(mask) == 5


def test_classify_hand_posture_buckets():
    """classify_hand_posture: 0 -> "fist", 1-3 -> "partial", 4+ -> "open_hand"."""
    assert classify_hand_posture(preprocess_hand_mask(_fist_mask())) == "fist"
    assert classify_hand_posture(preprocess_hand_mask(_star_mask(3))) == "partial"
    assert classify_hand_posture(preprocess_hand_mask(_star_mask(5))) == "open_hand"
