"""
Tests for stage05/mid01 -- Files, Exceptions, Regex: Order Validation Pipeline.
Auto-generated by generate.py from generator/stage05.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage05.mid01.solution import (
    OrderError,
    OrderValidationError,
    OrderProcessingError,
    parse_order_quantity,
    apply_bulk_discount,
    fulfill_order,
)


def test_hierarchy():
    """OrderValidationError and OrderProcessingError must both be OrderError, which must be an Exception."""
    assert issubclass(OrderValidationError, OrderError)
    assert issubclass(OrderProcessingError, OrderError)
    assert issubclass(OrderError, Exception)


def test_parse_order_quantity_valid():
    """parse_order_quantity("5") == 5."""
    assert parse_order_quantity("5") == 5


def test_parse_order_quantity_chains_value_error():
    """A non-numeric quantity chains the underlying ValueError via `from e`."""
    with pytest.raises(OrderValidationError) as exc_info:
        parse_order_quantity("abc")
    assert isinstance(exc_info.value.__cause__, ValueError)


def test_parse_order_quantity_non_positive_does_not_chain():
    """A non-positive quantity is a fresh validation failure -- no `from`, so __cause__ is None."""
    with pytest.raises(OrderValidationError) as exc_info:
        parse_order_quantity("-3")
    assert exc_info.value.__cause__ is None


def test_apply_bulk_discount_valid():
    """apply_bulk_discount(10, "20") == 10 * (1 - 0.2)."""
    assert apply_bulk_discount(10, "20") == pytest.approx(8.0)


def test_apply_bulk_discount_chains_value_error():
    """A non-numeric discount chains the underlying ValueError via `from e`."""
    with pytest.raises(OrderProcessingError) as exc_info:
        apply_bulk_discount(10, "abc")
    assert isinstance(exc_info.value.__cause__, ValueError)


def test_apply_bulk_discount_out_of_range_suppresses_chaining():
    """An out-of-range discount uses `from None` -- __cause__ must be None."""
    with pytest.raises(OrderProcessingError) as exc_info:
        apply_bulk_discount(10, "150")
    assert exc_info.value.__cause__ is None


def test_fulfill_order():
    """fulfill_order returns stock - quantity, or raises OrderProcessingError if quantity exceeds stock."""
    assert fulfill_order(3, 10) == 7
    with pytest.raises(OrderProcessingError):
        fulfill_order(20, 10)
