"""
Tests for week12/exercise01 -- Requests + Threading: Requests Basics.
Auto-generated by generate.py from generator/week12.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from unittest.mock import Mock, patch
import pytest
import requests
from exercises.week12.exercise01.solution import (
    fetch_json,
    fetch_status_code,
    post_data,
    fetch_with_raise,
)


def _fake_response(json_data=None, status_code=200, raise_error=False):
    response = Mock()
    response.json.return_value = json_data or {}
    response.status_code = status_code
    if raise_error:
        response.raise_for_status.side_effect = requests.HTTPError("boom")
    else:
        response.raise_for_status.return_value = None
    return response


def test_fetch_json():
    with patch("requests.get", return_value=_fake_response({"id": 1})) as mock_get:
        result = fetch_json("https://example.test/api")
    mock_get.assert_called_once_with("https://example.test/api")
    assert result == {"id": 1}


def test_fetch_status_code():
    with patch("requests.get", return_value=_fake_response(status_code=404)):
        assert fetch_status_code("https://example.test/api") == 404


def test_post_data():
    with patch("requests.post", return_value=_fake_response({"created": True})) as mock_post:
        result = post_data("https://example.test/api", {"name": "Ada"})
    mock_post.assert_called_once_with("https://example.test/api", json={"name": "Ada"})
    assert result == {"created": True}


def test_fetch_with_raise_success():
    with patch("requests.get", return_value=_fake_response({"ok": True})):
        assert fetch_with_raise("https://example.test/api") == {"ok": True}


def test_fetch_with_raise_propagates_http_error():
    with patch("requests.get", return_value=_fake_response(raise_error=True)):
        with pytest.raises(requests.HTTPError):
            fetch_with_raise("https://example.test/api")
