"""
Tests for stage05/exercise06 -- Files, Exceptions, Regex: Context Managers.
Auto-generated by generate.py from generator/stage05.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage05.exercise06.solution import (
    Timer,
    SuppressErrors,
    FileLineCounter,
    temporary_value,
    suppress_and_log,
    timing_block,
)


def test_timer_records_elapsed():
    with Timer() as t:
        pass
    assert hasattr(t, "elapsed")
    assert t.elapsed >= 0


def test_suppress_errors_suppresses_matching_type():
    with SuppressErrors(ValueError):
        raise ValueError("boom")


def test_suppress_errors_lets_other_types_propagate():
    with pytest.raises(TypeError):
        with SuppressErrors(ValueError):
            raise TypeError("nope")


def test_file_line_counter(tmp_path):
    path = tmp_path / "data.txt"
    path.write_text("a\nb\nc\n")
    with FileLineCounter(str(path)) as f:
        lines = f.read().splitlines()
    assert lines == ["a", "b", "c"]


class _Config:
    debug = False


def test_temporary_value_restores_after_block():
    cfg = _Config()
    with temporary_value(cfg, "debug", True):
        assert cfg.debug is True
    assert cfg.debug is False


def test_temporary_value_restores_even_on_exception():
    # ValueError, not RuntimeError: NotImplementedError (what an unfinished
    # stub raises) is itself a RuntimeError subclass, so a RuntimeError here
    # would let pytest.raises(RuntimeError) accidentally match an
    # unimplemented temporary_value() instead of only a correct one.
    cfg = _Config()
    with pytest.raises(ValueError):
        with temporary_value(cfg, "debug", True):
            raise ValueError("boom")
    assert cfg.debug is False


def test_suppress_and_log():
    log = []
    with suppress_and_log(log, ValueError):
        raise ValueError("bad input")
    assert log == ["bad input"]


def test_timing_block():
    results = []
    with timing_block(results):
        pass
    assert len(results) == 1
    assert results[0] >= 0
