"""
Tests for stage04/basic02 -- Data Structures: Inventory Category Summary.
Auto-generated by generate.py from generator/stage04.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage04.basic02.solution import (
    category_by_product,
    unique_categories,
    products_in_category,
    category_counts,
    product_count,
)

NAMES = ["Widget", "Gadget", "Gizmo", "Widget", "Sprocket"]
CATEGORIES = ["tools", "electronics", "electronics", "tools", "tools"]


def test_category_by_product_dict_comprehension_collapses_duplicate_key():
    """category_by_product is a dict comprehension -- the second "Widget" entry silently overwrites the first."""
    result = category_by_product(NAMES, CATEGORIES)
    assert result == {"Widget": "tools", "Gadget": "electronics", "Gizmo": "electronics", "Sprocket": "tools"}
    assert len(result) == 4


def test_unique_categories():
    """unique_categories == set(categories)."""
    assert unique_categories(CATEGORIES) == {"tools", "electronics"}


def test_products_in_category_list_comprehension_keeps_all_matches():
    """products_in_category is a filtered list comprehension -- unlike the dict version, both "Widget" entries survive."""
    result = products_in_category(NAMES, CATEGORIES, "tools")
    assert result == ["Widget", "Widget", "Sprocket"]


def test_category_counts():
    """category_counts is a dict comprehension over set(categories), counting each category via .count()."""
    assert category_counts(CATEGORIES) == {"tools": 3, "electronics": 2}


def test_product_count():
    """product_count == len(names)."""
    assert product_count(NAMES) == 5
