"""
Tests for stage11/mid01 -- OpenCV: Thresholding.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import numpy as np
from exercises.stage11.mid01.solution import (
    apply_threshold,
    apply_otsu_threshold,
    apply_adaptive_threshold,
)


def _half_bright_gray():
    image = np.zeros((20, 20), dtype=np.uint8)
    image[:, 10:] = 200
    return image


def test_apply_threshold():
    """apply_threshold binarizes at a fixed global value."""
    result = apply_threshold(_half_bright_gray(), 100)
    assert result[0, 0] == 0
    assert result[0, 15] == 255


def test_apply_otsu_threshold_separates_regions():
    """apply_otsu_threshold must pick its own threshold from the histogram and still separate the two regions."""
    result = apply_otsu_threshold(_half_bright_gray())
    assert result[0, 0] != result[0, 15]


def test_apply_adaptive_threshold_returns_binary_image():
    """apply_adaptive_threshold must return a same-shape image with only 0/255 values."""
    result = apply_adaptive_threshold(_half_bright_gray())
    assert result.shape == (20, 20)
    assert set(np.unique(result)).issubset({0, 255})
