"""
Tests for stage13/tier2_mid02 -- Local API Endpoints: Dependency Injection and Automatic Docs.
Auto-generated by generate.py from generator/stage13.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from fastapi.testclient import TestClient
from exercises.stage13.tier2_mid02.solution import app as di_app, get_openapi_schema, has_docs_route

di_client = TestClient(di_app)


def test_paginated_defaults():
    """paginated depends on get_pagination for its default page/size."""
    assert di_client.get("/paginated").json() == {"page": 1, "size": 10}


def test_paginated_custom_values():
    """Query parameters flow through the Depends()-injected get_pagination."""
    assert di_client.get("/paginated?page=3&size=20").json() == {"page": 3, "size": 20}


def test_status_depends_on_get_db():
    """status returns whatever the get_db dependency returns."""
    assert di_client.get("/status").json() == {"connected": True}


def test_protected_without_token():
    """verify_token's dependency-injected result gates the /protected response."""
    assert di_client.get("/protected").json() == {"error": "unauthorized"}


def test_protected_with_correct_token():
    """A correct token, via the same Depends()-injected verify_token, unlocks the protected data."""
    response = di_client.get("/protected?token=secret")
    assert response.json() == {"data": "secret data"}


def test_get_openapi_schema_has_paginated_path():
    """get_openapi_schema uses app.openapi(), which must describe every registered route."""
    schema = get_openapi_schema(di_app)
    assert "/paginated" in schema["paths"]


def test_has_docs_route():
    """Every FastAPI app gets a /docs route registered automatically, no extra code required."""
    assert has_docs_route(di_app) is True
