"""
Tests for stage13/tier3_advanced02 -- Local API Endpoints: Testing Apps with TestClient.
Auto-generated by generate.py from generator/stage13.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage13.tier3_advanced02.solution import (
    app,
    client_get_json,
    client_post_json,
    client_status_code,
)


def test_client_get_json():
    """client_get_json must build its own TestClient(app) and GET the given path."""
    assert client_get_json(app, "/ping") == {"pong": True}


def test_client_post_json():
    """client_post_json must build its own TestClient(app) and POST the given payload."""
    assert client_post_json(app, "/echo2", {"a": 1}) == {"a": 1}


def test_client_status_code():
    """client_status_code returns the raw HTTP status code from a TestClient GET."""
    assert client_status_code(app, "/ping") == 200
    assert client_status_code(app, "/nonexistent") == 404
