"""
Tests for week05/exercise02 -- Files, Exceptions, Regex: Exceptions and Hierarchies.
Auto-generated by generate.py from generator/week05.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.week05.exercise02.solution import (
    ValidationError,
    NegativeValueError,
    validate_positive,
    safe_parse_int,
    divide_with_cleanup,
    get_attempts,
    reset_attempts,
)


def test_validate_positive_passthrough():
    assert validate_positive(5) == 5


def test_validate_positive_raises_negative_value_error():
    with pytest.raises(NegativeValueError):
        validate_positive(-1)


def test_negative_value_error_is_a_validation_error():
    assert issubclass(NegativeValueError, ValidationError)
    assert issubclass(ValidationError, Exception)


def test_safe_parse_int_valid():
    assert safe_parse_int("42") == 42


def test_safe_parse_int_invalid():
    assert safe_parse_int("nope") is None


def test_divide_with_cleanup_success():
    reset_attempts()
    assert divide_with_cleanup(10, 2) == 5.0
    assert get_attempts() == 1


def test_divide_with_cleanup_counts_failed_attempts_too():
    reset_attempts()
    with pytest.raises(ZeroDivisionError):
        divide_with_cleanup(10, 0)
    assert get_attempts() == 1
