"""
Aggregated tests for week12 -- Requests + Threading.
Auto-generated by generate.py from generator/week12.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: Requests Basics
from unittest.mock import Mock, patch
import pytest
import requests
from exercises.week12.exercise01.solution import (
    fetch_json,
    fetch_status_code,
    post_data,
    fetch_with_raise,
)


def _fake_response(json_data=None, status_code=200, raise_error=False):
    response = Mock()
    response.json.return_value = json_data or {}
    response.status_code = status_code
    if raise_error:
        response.raise_for_status.side_effect = requests.HTTPError("boom")
    else:
        response.raise_for_status.return_value = None
    return response


def test_fetch_json():
    with patch("requests.get", return_value=_fake_response({"id": 1})) as mock_get:
        result = fetch_json("https://example.test/api")
    mock_get.assert_called_once_with("https://example.test/api")
    assert result == {"id": 1}


def test_fetch_status_code():
    with patch("requests.get", return_value=_fake_response(status_code=404)):
        assert fetch_status_code("https://example.test/api") == 404


def test_post_data():
    with patch("requests.post", return_value=_fake_response({"created": True})) as mock_post:
        result = post_data("https://example.test/api", {"name": "Ada"})
    mock_post.assert_called_once_with("https://example.test/api", json={"name": "Ada"})
    assert result == {"created": True}


def test_fetch_with_raise_success():
    with patch("requests.get", return_value=_fake_response({"ok": True})):
        assert fetch_with_raise("https://example.test/api") == {"ok": True}


def test_fetch_with_raise_propagates_http_error():
    with patch("requests.get", return_value=_fake_response(raise_error=True)):
        with pytest.raises(requests.HTTPError):
            fetch_with_raise("https://example.test/api")


# ------------------------------------------------------------------ exercise02: Sessions and Retry/Backoff
from unittest.mock import Mock, patch
import pytest
import requests
from exercises.week12.exercise02.solution import (
    make_default_session,
    create_session_with_headers,
    fetch_multiple_with_session,
    fetch_with_retry,
)


def test_make_default_session():
    assert isinstance(make_default_session(), requests.Session)


def test_create_session_with_headers():
    session = create_session_with_headers({"Authorization": "Bearer token"})
    assert session.headers["Authorization"] == "Bearer token"


def test_fetch_multiple_with_session():
    fake_response = Mock()
    fake_response.json.return_value = {"ok": True}
    with patch.object(requests.Session, "get", return_value=fake_response) as mock_get:
        result = fetch_multiple_with_session(["https://a.test", "https://b.test"])
    assert result == [{"ok": True}, {"ok": True}]
    assert mock_get.call_count == 2


def test_fetch_with_retry_succeeds_after_failures(monkeypatch):
    monkeypatch.setattr("time.sleep", lambda seconds: None)
    fake_response = Mock()
    fake_response.raise_for_status.return_value = None
    fake_response.json.return_value = {"ok": True}

    call_count = {"n": 0}

    def flaky_get(url):
        call_count["n"] += 1
        if call_count["n"] < 3:
            raise requests.exceptions.ConnectionError("boom")
        return fake_response

    with patch("requests.get", side_effect=flaky_get):
        result = fetch_with_retry("https://example.test", max_attempts=5)
    assert result == {"ok": True}
    assert call_count["n"] == 3


def test_fetch_with_retry_raises_after_exhausting_attempts(monkeypatch):
    monkeypatch.setattr("time.sleep", lambda seconds: None)
    with patch("requests.get", side_effect=requests.exceptions.ConnectionError("boom")):
        with pytest.raises(requests.exceptions.RequestException):
            fetch_with_retry("https://example.test", max_attempts=3)


# ------------------------------------------------------------------ exercise03: Threading Basics
import threading
import time
from exercises.week12.exercise03.solution import run_in_background, wait_for_all, run_and_wait


def test_run_in_background_runs_the_function():
    result = []
    t = run_in_background(lambda x: result.append(x), 42)
    t.join()
    assert result == [42]


def test_wait_for_all_blocks_until_every_thread_finishes():
    results = []

    def slow_append(n):
        time.sleep(0.01)
        results.append(n)

    threads = [threading.Thread(target=slow_append, args=(i,)) for i in range(5)]
    for t in threads:
        t.start()
    wait_for_all(threads)
    assert sorted(results) == [0, 1, 2, 3, 4]


def test_run_and_wait_runs_concurrently_and_completes():
    results = []
    funcs = [lambda i=i: results.append(i) for i in range(5)]
    run_and_wait(funcs)
    assert sorted(results) == [0, 1, 2, 3, 4]


# ------------------------------------------------------------------ exercise04: Locks and Race Conditions
import threading
from exercises.week12.exercise04.solution import (
    SafeCounter,
    SafeList,
    transfer_funds,
    parallel_increment,
)


def test_safe_counter_survives_real_concurrency():
    counter = SafeCounter()
    parallel_increment(counter, times=2000, num_threads=10)
    assert counter.value == 2000


def test_safe_list_append_from_many_threads():
    safe_list = SafeList()
    threads = [threading.Thread(target=safe_list.append_safe, args=(i,)) for i in range(50)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    assert sorted(safe_list.items) == list(range(50))


def test_transfer_funds_keeps_books_balanced():
    accounts = {"alice": 1000, "bob": 0}
    lock = threading.Lock()
    threads = [
        threading.Thread(target=transfer_funds, args=(accounts, lock, "alice", "bob", 10))
        for _ in range(50)
    ]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    assert accounts["alice"] == 500
    assert accounts["bob"] == 500
    assert accounts["alice"] + accounts["bob"] == 1000


# ------------------------------------------------------------------ exercise05: ThreadPoolExecutor
from unittest.mock import Mock, patch
from exercises.week12.exercise05.solution import (
    fetch_all_concurrently,
    run_tasks_with_pool,
    compute_squares_concurrently,
)


def test_fetch_all_concurrently():
    fake_response = Mock()
    fake_response.json.return_value = {"ok": True}
    with patch("requests.get", return_value=fake_response) as mock_get:
        result = fetch_all_concurrently(["https://a.test", "https://b.test", "https://c.test"])
    assert result == [{"ok": True}, {"ok": True}, {"ok": True}]
    assert mock_get.call_count == 3


def test_run_tasks_with_pool_preserves_order():
    funcs = [lambda i=i: i * 10 for i in range(5)]
    assert run_tasks_with_pool(funcs) == [0, 10, 20, 30, 40]


def test_compute_squares_concurrently():
    assert compute_squares_concurrently([1, 2, 3, 4]) == [1, 4, 9, 16]
