"""
Tests for stage07/tier2_mid02 -- OOP II: Composition and Swappable Engines.
Auto-generated by generate.py from generator/stage07.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage07.tier2_mid02.solution import GasEngine, ElectricEngine, Boat, swap_engine


def test_boat_composition_delegates_to_gas_engine():
    """Boat.start() delegates to whatever engine object it holds (composition, not inheritance)."""
    boat = Boat(GasEngine())
    assert boat.start() == "Gas engine roaring to life..."


def test_boat_composition_delegates_to_electric_engine():
    """The same Boat class works with a completely different engine object, with no shared inheritance needed."""
    boat = Boat(ElectricEngine())
    assert boat.start() == "Electric engine humming..."


def test_swap_engine_changes_behavior_at_runtime():
    """swap_engine replaces boat.engine after construction -- behavior changes without touching any class hierarchy."""
    boat = Boat(GasEngine())
    assert boat.start() == "Gas engine roaring to life..."
    swap_engine(boat, ElectricEngine())
    assert boat.start() == "Electric engine humming..."


def test_boat_is_not_an_engine():
    """Boat must NOT inherit from either engine class -- it holds one, it isn't one."""
    boat = Boat(GasEngine())
    assert not isinstance(boat, GasEngine)
    assert not isinstance(boat, ElectricEngine)
