"""
Tests for week10/exercise03 -- Pandas: Sorting and Grouping.
Auto-generated by generate.py from generator/week10.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pandas as pd
from exercises.week10.exercise03.solution import (
    sort_by_sales_desc,
    sort_by_multiple,
    total_sales_by_region,
    avg_sales_by_region_and_product,
    orders_per_region_sorted,
)


def _group_sample_df():
    return pd.DataFrame({
        "region": ["east", "west", "east", "west", "east"],
        "product": ["A", "A", "B", "B", "A"],
        "sales": [100, 250, 50, 300, 150],
    })


def test_sort_by_sales_desc():
    result = sort_by_sales_desc(_group_sample_df())
    assert list(result["sales"]) == [300, 250, 150, 100, 50]


def test_sort_by_multiple():
    result = sort_by_multiple(_group_sample_df())
    assert list(result["region"]) == ["east", "east", "east", "west", "west"]
    assert list(result["sales"])[:3] == [150, 100, 50]


def test_total_sales_by_region():
    result = total_sales_by_region(_group_sample_df())
    assert result["east"] == 300
    assert result["west"] == 550


def test_avg_sales_by_region_and_product_is_multi_indexed():
    result = avg_sales_by_region_and_product(_group_sample_df())
    assert isinstance(result.index, pd.MultiIndex)
    assert result[("east", "A")] == 125.0


def test_orders_per_region_sorted():
    result = orders_per_region_sorted(_group_sample_df())
    assert list(result.index) == ["east", "west"]
    assert list(result.values) == [3, 2]
