"""
Tests for stage02/tier4_testing -- Control Flow: Testing Without a Framework: Catch the Bug.
Auto-generated by generate.py from generator/stage02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import exercises.stage02.tier4_testing.solution as solution


def test_check_results_has_one_entry_per_target_value():
    """check_results must have exactly four (description, bool) entries, one per target value in README.md."""
    assert len(solution.check_results) == 4


def test_check_results_entries_are_description_bool_pairs():
    """Each check_results entry must be a (str, bool) tuple, not a raised assert."""
    for entry in solution.check_results:
        assert isinstance(entry, tuple) and len(entry) == 2
        description, passed = entry
        assert isinstance(description, str) and description != ""
        assert isinstance(passed, bool)


def test_total_and_passed_checks_reflect_the_real_bugs():
    """total_checks == 4; passed_checks == 2 -- the v1 variants meet spec, the v2 variants don't."""
    assert solution.total_checks == 4
    assert solution.passed_checks == 2


def test_failed_descriptions_derived_from_check_results():
    """failed_descriptions must be exactly the descriptions of the failing entries in check_results, in order."""
    expected = [desc for desc, ok in solution.check_results if not ok]
    assert solution.failed_descriptions == expected
    assert len(solution.failed_descriptions) == 2
