"""
Tests for stage14/exercise01 -- Capstone: Library and Book.
Auto-generated by generate.py from generator/stage14.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage14.exercise01.solution import Book, Library


def test_add_and_len():
    lib = Library()
    lib.add_book(Book("Dune", "Herbert", "111"))
    assert len(lib) == 1


def test_find_by_author():
    lib = Library()
    lib.add_book(Book("Dune", "Herbert", "111"))
    lib.add_book(Book("Foundation", "Asimov", "222"))
    result = lib.find_by_author("Herbert")
    assert len(result) == 1
    assert result[0].isbn == "111"


def test_contains():
    lib = Library()
    lib.add_book(Book("Dune", "Herbert", "111"))
    assert "111" in lib


def test_book_eq_by_isbn():
    assert Book("Dune", "Herbert", "111") == Book("Dune (reprint)", "F. Herbert", "111")


def test_save_and_load_roundtrip(tmp_path):
    lib = Library()
    lib.add_book(Book("Dune", "Herbert", "111"))
    path = str(tmp_path / "lib.json")
    lib.save_to_json(path)

    new_lib = Library()
    new_lib.load_from_json(path)
    assert len(new_lib) == 1
    assert new_lib._books[0].title == "Dune"
