"""
Tests for stage09/exercise02 -- OS, JSON, Datetime, XML: Recursive Traversal.
Auto-generated by generate.py from generator/stage09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage09.exercise02.solution import (
    find_all_py_files,
    count_files_by_extension,
    total_size_of_directory,
    find_txt_files_pathlib,
)


def _make_tree(tmp_path):
    (tmp_path / "a.py").write_text("x = 1")
    (tmp_path / "b.txt").write_text("hello")
    sub = tmp_path / "sub"
    sub.mkdir()
    (sub / "c.py").write_text("y = 2")
    (sub / "d.txt").write_text("world")
    return tmp_path


def test_find_all_py_files(tmp_path):
    _make_tree(tmp_path)
    result = find_all_py_files(str(tmp_path))
    assert len(result) == 2
    assert all(p.endswith(".py") for p in result)


def test_count_files_by_extension(tmp_path):
    _make_tree(tmp_path)
    result = count_files_by_extension(str(tmp_path))
    assert result == {".py": 2, ".txt": 2}


def test_total_size_of_directory(tmp_path):
    _make_tree(tmp_path)
    assert total_size_of_directory(str(tmp_path)) == len("x = 1") + len("hello") + len("y = 2") + len("world")


def test_find_txt_files_pathlib(tmp_path):
    _make_tree(tmp_path)
    assert find_txt_files_pathlib(str(tmp_path)) == ["b.txt", "d.txt"]
