"""
Tests for stage04/exercise01 -- Data Structures: List and Tuple Basics.
Auto-generated by generate.py from generator/stage04.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage04.exercise01.solution import (
    build_shopping_list,
    unique_sorted,
    sort_in_place,
    as_tuple_pairs,
    zip_and_sum,
    label_each,
    count_items,
)


def test_build_shopping_list():
    assert build_shopping_list(["milk", "eggs"]) == ["milk", "eggs"]


def test_unique_sorted():
    assert unique_sorted([3, 1, 2, 1, 3]) == [1, 2, 3]


def test_sort_in_place():
    items = [3, 1, 2]
    result = sort_in_place(items)
    assert result is None
    assert items == [1, 2, 3]


def test_as_tuple_pairs():
    assert as_tuple_pairs(["a", "b"], [1, 2]) == [("a", 1), ("b", 2)]


def test_zip_and_sum():
    assert zip_and_sum([1, 2, 3], [10, 20, 30]) == [11, 22, 33]


def test_label_each():
    assert label_each(["a", "b"]) == ["0:a", "1:b"]


def test_count_items():
    assert count_items([1, 2, 3]) == 3
