"""
Tests for stage08/exercise06 -- The Python Data Model: Money and Score: Operator Overloading.
Auto-generated by generate.py from generator/stage08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage08.exercise06.solution import Money, Score


def test_money_add_and_eq():
    assert Money(100) + Money(50) == Money(150)


def test_money_sum():
    assert sum([Money(100), Money(200), Money(300)]) == Money(600)


def test_money_hash():
    assert len({Money(100), Money(100), Money(200)}) == 2


def test_score_add_and_eq():
    assert Score(10) + Score(5) == Score(15)


def test_score_sum():
    assert sum([Score(1), Score(2), Score(3)]) == Score(6)


def test_money_repr():
    assert repr(Money(500)) == "Money(500)"
