"""
Tests for stage03/exercise07 -- Functions: Signature Styles.
Auto-generated by generate.py from generator/stage03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage03.exercise07.solution import compute_area, divide, connect, scale_point


def test_compute_area_default_unit():
    assert compute_area(2, 3) == "6m^2"


def test_compute_area_custom_unit_keyword_only():
    assert compute_area(2, 3, unit="cm") == "6cm^2"


def test_compute_area_unit_must_be_keyword():
    with pytest.raises(TypeError):
        compute_area(2, 3, "cm")


def test_divide():
    assert divide(10, 3, precision=3) == 3.333


def test_divide_positional_only_enforced():
    with pytest.raises(TypeError):
        divide(a=7, b=2)


def test_divide_precision_keyword_only_enforced():
    with pytest.raises(TypeError):
        divide(7, 2, 3)


def test_connect_defaults():
    assert connect("localhost", 8080) == {
        "host": "localhost", "port": 8080, "timeout": 30, "retries": 3,
    }


def test_connect_keyword_only_overrides():
    result = connect("localhost", 8080, timeout=5, retries=1)
    assert result == {"host": "localhost", "port": 8080, "timeout": 5, "retries": 1}


def test_connect_positional_only_enforced():
    with pytest.raises(TypeError):
        connect(host="localhost", port=8080)


def test_scale_point_default_factor():
    assert scale_point(2, 3) == (2, 3)


def test_scale_point_with_factor_positional_or_keyword():
    assert scale_point(2, 3, 2) == (4, 6)
    assert scale_point(2, 3, factor=2) == (4, 6)


def test_scale_point_positional_only_enforced():
    with pytest.raises(TypeError):
        scale_point(x=2, y=3)
