"""
Tests for stage05/exercise03 -- Files, Exceptions, Regex: Exception Chaining.
Auto-generated by generate.py from generator/stage05.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage05.exercise03.solution import (
    ConfigError,
    ConfigParseError,
    load_config_value,
    NetworkError,
    RetryError,
    fetch_with_retry_simulation,
    ScoreError,
    parse_score,
)


def test_load_config_value_valid():
    assert load_config_value("42") == 42


def test_load_config_value_chains_value_error():
    with pytest.raises(ConfigParseError) as exc_info:
        load_config_value("abc")
    assert isinstance(exc_info.value.__cause__, ValueError)
    assert isinstance(exc_info.value, ConfigError)


def test_fetch_with_retry_simulation_success():
    assert fetch_with_retry_simulation(False) == "ok"


def test_fetch_with_retry_simulation_chains_network_error():
    with pytest.raises(RetryError) as exc_info:
        fetch_with_retry_simulation(True)
    assert isinstance(exc_info.value.__cause__, NetworkError)


def test_parse_score_valid():
    assert parse_score("85") == 85


def test_parse_score_chains_value_error():
    with pytest.raises(ScoreError) as exc_info:
        parse_score("abc")
    assert isinstance(exc_info.value.__cause__, ValueError)


def test_parse_score_out_of_range_suppresses_chaining():
    with pytest.raises(ScoreError) as exc_info:
        parse_score("150")
    assert exc_info.value.__cause__ is None
