"""
Tests for stage07/exercise02 -- OOP II: super() and Polymorphism.
Auto-generated by generate.py from generator/stage07.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage07.exercise02.solution import (
    Vehicle,
    Car,
    ElectricCar,
    total_description,
    is_car,
)


def test_vehicle_describe():
    assert Vehicle("Honda", "Civic").describe() == "Honda Civic"


def test_car_describe_extends_vehicle():
    assert Car("Honda", "Civic", 4).describe() == "Honda Civic (4 doors)"


def test_electric_car_describe_extends_car():
    car = ElectricCar("Tesla", "Model 3", 4, 75)
    assert car.describe() == "Tesla Model 3 (4 doors), 75kWh battery"


def test_total_description_polymorphism():
    vehicles = [Vehicle("A", "B"), Car("C", "D", 2), ElectricCar("E", "F", 4, 50)]
    result = total_description(vehicles)
    assert result == [
        "A B",
        "C D (2 doors)",
        "E F (4 doors), 50kWh battery",
    ]


def test_is_car():
    assert is_car(Car("C", "D", 2)) is True
    assert is_car(ElectricCar("E", "F", 4, 50)) is True
    assert is_car(Vehicle("A", "B")) is False
