"""
Tests for stage10/tier1_basic02 -- Pandas: Reading and Inspecting Employee Data.
Auto-generated by generate.py from generator/stage10.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pandas as pd
from exercises.stage10.tier1_basic02.solution import (
    load_employees,
    preview_employees,
    salary_summary,
    column_names,
    row_count,
)


def test_load_employees(tmp_path):
    """load_employees == pd.read_csv(path), on a different dataset shape."""
    path = tmp_path / "employees.csv"
    path.write_text("name,salary\nAda,90000\nGrace,95000\nLinus,80000\n")
    df = load_employees(str(path))
    assert list(df.columns) == ["name", "salary"]
    assert len(df) == 3


def test_preview_employees():
    """preview_employees == df.head(n)."""
    df = pd.DataFrame({"name": ["a", "b", "c", "d"], "salary": [1, 2, 3, 4]})
    assert len(preview_employees(df, 2)) == 2


def test_salary_summary():
    """salary_summary == df.describe()."""
    df = pd.DataFrame({"salary": [90000, 95000, 80000]})
    result = salary_summary(df)
    assert round(result.loc["mean", "salary"], 2) == 88333.33


def test_column_names():
    """column_names == list(df.columns)."""
    df = pd.DataFrame({"name": ["Ada"], "salary": [90000]})
    assert column_names(df) == ["name", "salary"]


def test_row_count():
    """row_count == len(df)."""
    df = pd.DataFrame({"name": ["Ada", "Grace"]})
    assert row_count(df) == 2
