"""
Tests for stage07/basic01 -- OOP II: Animal Sounds: Inheritance and Duck Typing.
Auto-generated by generate.py from generator/stage07.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage07.basic01.solution import (
    Animal,
    Dog,
    Cat,
    describe_animal,
    Duck,
    Person,
    make_it_quack,
)


def test_dog_speak():
    """Dog overrides Animal.speak()."""
    assert Dog("Rex").speak() == "Rex says Woof!"


def test_cat_speak_and_super_init():
    """Cat.__init__ must call super().__init__(name) before setting its own indoor attribute."""
    cat = Cat("Whiskers")
    assert cat.speak() == "Whiskers says Meow!"
    assert cat.name == "Whiskers"
    assert cat.indoor is True


def test_describe_animal_polymorphism():
    """describe_animal works for any Animal subclass via inheritance-based polymorphism."""
    assert describe_animal(Dog("Rex")) == "Rex says Woof!"
    assert describe_animal(Cat("Whiskers", indoor=False)) == "Whiskers says Meow!"


def test_dog_and_cat_are_animals():
    """Dog/Cat must both be real Animal subclasses."""
    assert isinstance(Dog("Rex"), Animal)
    assert isinstance(Cat("Whiskers"), Animal)


def test_make_it_quack_duck_typing_with_no_shared_base_class():
    """make_it_quack works on Duck and Person alike -- neither shares a base class, only a matching .quack() method."""
    assert make_it_quack(Duck()) == "Quack!"
    assert make_it_quack(Person()) == "I'm quacking like a duck!"
    assert Duck.__bases__ == (object,)
    assert Person.__bases__ == (object,)
