"""
Tests for week11/exercise03 -- OpenCV: Drawing on Images.
Auto-generated by generate.py from generator/week11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import numpy as np
from exercises.week11.exercise03.solution import (
    draw_rectangle,
    draw_filled_rectangle,
    draw_bounding_boxes,
)


def test_draw_rectangle_does_not_mutate_original():
    image = np.zeros((20, 20, 3), dtype=np.uint8)
    result = draw_rectangle(image, (2, 2), (10, 10), (255, 255, 255))
    assert np.array_equal(image, np.zeros((20, 20, 3), dtype=np.uint8))
    assert result[2, 2].tolist() == [255, 255, 255]


def test_draw_filled_rectangle_fills_interior():
    image = np.zeros((20, 20, 3), dtype=np.uint8)
    result = draw_filled_rectangle(image, (2, 2), (10, 10), (255, 255, 255))
    assert result[5, 5].tolist() == [255, 255, 255]


def test_draw_bounding_boxes_draws_all():
    image = np.zeros((30, 30, 3), dtype=np.uint8)
    boxes = [(1, 1, 5, 5), (10, 10, 15, 15)]
    result = draw_bounding_boxes(image, boxes, (255, 0, 0))
    assert result[1, 1].tolist() == [255, 0, 0]
    assert result[10, 10].tolist() == [255, 0, 0]
