"""
Tests for stage06/exercise05 -- OOP I: Descriptors Preview.
Auto-generated by generate.py from generator/stage06.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage06.exercise05.solution import Product, Person


def test_positive_number_descriptor_get_set():
    p = Product("Widget", 9.99)
    assert p.price == 9.99
    p.price = 19.99
    assert p.price == 19.99


def test_positive_number_descriptor_rejects_negative():
    p = Product("Widget", 9.99)
    with pytest.raises(ValueError):
        p.price = -1


def test_positive_number_descriptor_rejects_at_construction():
    with pytest.raises(ValueError):
        Product("Widget", -5)


def test_typed_descriptor_get_set():
    person = Person("Ada", 30)
    assert person.name == "Ada"
    assert person.age == 30


def test_typed_descriptor_rejects_wrong_type():
    person = Person("Ada", 30)
    with pytest.raises(TypeError):
        person.age = "thirty"


def test_typed_descriptor_rejects_at_construction():
    with pytest.raises(TypeError):
        Person("Ada", "thirty")
