"""
Tests for week02/exercise04 -- Control Flow: Ranges and Itertools.
Auto-generated by generate.py from generator/week02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week02.exercise04.solution import (
    stepped_range,
    numbered_multiples,
    cycle_colors,
    chain_lists,
    all_pairs,
)


def test_stepped_range():
    assert stepped_range(0, 10, 2) == [0, 2, 4, 6, 8]


def test_numbered_multiples():
    assert numbered_multiples(12, 3) == ["0: 3", "1: 6", "2: 9", "3: 12"]


def test_cycle_colors():
    assert cycle_colors(["red", "green"], 5) == ["red", "green", "red", "green", "red"]


def test_chain_lists():
    assert chain_lists([1, 2], [3, 4]) == [1, 2, 3, 4]


def test_all_pairs():
    assert all_pairs([1, 2], ["a", "b"]) == [(1, "a"), (1, "b"), (2, "a"), (2, "b")]
