"""
Tests for stage10/advanced01 -- Pandas: Inspecting, Pivoting, and Multi-Indexing.
Auto-generated by generate.py from generator/stage10.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pandas as pd
from exercises.stage10.advanced01.solution import (
    capture_info,
    avg_sales_by_region_and_product,
    sales_pivot_table,
    sales_pivot_count,
)


def test_capture_info():
    """capture_info must redirect df.info()'s stdout output into a returned string."""
    df = pd.DataFrame({"x": [1, 2, 3]})
    text = capture_info(df)
    assert "RangeIndex" in text


def _group_sample_df():
    return pd.DataFrame({
        "region": ["east", "west", "east", "west", "east"],
        "product": ["A", "A", "B", "B", "A"],
        "sales": [100, 250, 50, 300, 150],
    })


def test_avg_sales_by_region_and_product_is_multi_indexed():
    """Grouping by two columns must produce a pd.MultiIndex result."""
    result = avg_sales_by_region_and_product(_group_sample_df())
    assert isinstance(result.index, pd.MultiIndex)
    assert result[("east", "A")] == 125.0


def _pivot_sample_df():
    return pd.DataFrame({
        "region": ["east", "east", "west"],
        "product": ["A", "B", "A"],
        "sales": [100, 50, 200],
    })


def test_sales_pivot_table():
    """sales_pivot_table uses aggfunc="sum"."""
    result = sales_pivot_table(_pivot_sample_df())
    assert result.loc["east", "A"] == 100
    assert result.loc["west", "A"] == 200


def test_sales_pivot_count():
    """sales_pivot_count uses aggfunc="count" instead of "sum"."""
    result = sales_pivot_count(_pivot_sample_df())
    assert result.loc["east", "A"] == 1
