"""
Tests for stage04/exercise03 -- Data Structures: Comprehensions.
Auto-generated by generate.py from generator/stage04.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage04.exercise03.solution import squares, evens_squared_dict, flatten


def test_squares():
    assert squares(5) == [0, 1, 4, 9, 16]


def test_evens_squared_dict():
    assert evens_squared_dict(6) == {0: 0, 2: 4, 4: 16}


def test_flatten():
    assert flatten([[1, 2], [3, 4], [5]]) == [1, 2, 3, 4, 5]
