"""
Tests for stage12/exercise05 -- Requests + Threading: ThreadPoolExecutor.
Auto-generated by generate.py from generator/stage12.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from unittest.mock import Mock, patch
from exercises.stage12.exercise05.solution import (
    fetch_all_concurrently,
    run_tasks_with_pool,
    compute_squares_concurrently,
)


def test_fetch_all_concurrently():
    fake_response = Mock()
    fake_response.json.return_value = {"ok": True}
    with patch("requests.get", return_value=fake_response) as mock_get:
        result = fetch_all_concurrently(["https://a.test", "https://b.test", "https://c.test"])
    assert result == [{"ok": True}, {"ok": True}, {"ok": True}]
    assert mock_get.call_count == 3


def test_run_tasks_with_pool_preserves_order():
    funcs = [lambda i=i: i * 10 for i in range(5)]
    assert run_tasks_with_pool(funcs) == [0, 10, 20, 30, 40]


def test_compute_squares_concurrently():
    assert compute_squares_concurrently([1, 2, 3, 4]) == [1, 4, 9, 16]
