"""
Aggregated tests for week08 -- The Python Data Model.
Auto-generated by generate.py from generator/week08.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: Vector: The Flagship Dunder Class
from exercises.week08.exercise01.solution import Vector


def test_vector_repr():
    assert repr(Vector(1, 2)) == "Vector(1, 2)"


def test_str():
    assert str(Vector(1, 2)) == "(1, 2)"


def test_eq():
    assert Vector(1, 2) == Vector(1, 2)
    assert Vector(1, 2) != Vector(3, 4)


def test_add():
    assert Vector(1, 2) + Vector(3, 4) == Vector(4, 6)


def test_radd_via_sum():
    total = sum([Vector(1, 1), Vector(2, 2), Vector(3, 3)])
    assert total == Vector(6, 6)


def test_hash_and_set():
    vectors = {Vector(1, 2), Vector(1, 2), Vector(3, 4)}
    assert len(vectors) == 2


def test_vector_bool():
    assert bool(Vector(0, 0)) is False
    assert bool(Vector(1, 0)) is True


def test_vector_getitem():
    v = Vector(5, 7)
    assert v[0] == 5
    assert v[1] == 7


# ------------------------------------------------------------------ exercise02: Deck: A Collection Protocol
from exercises.week08.exercise02.solution import Deck


def test_repr_and_str():
    d = Deck(["A", "K"])
    assert repr(d) == "Deck(['A', 'K'])"
    assert str(d) == "Deck of 2 cards"


def test_len_and_getitem():
    d = Deck(["A", "K", "Q"])
    assert len(d) == 3
    assert d[0] == "A"
    assert d[1:] == ["K", "Q"]


def test_deck_iter():
    d = Deck(["A", "K", "Q"])
    assert list(d) == ["A", "K", "Q"]


def test_deck_contains():
    d = Deck(["A", "K", "Q"])
    assert "K" in d
    assert "J" not in d


def test_add_concatenates():
    d1 = Deck(["A", "K"])
    d2 = Deck(["Q", "J"])
    combined = d1 + d2
    assert list(combined) == ["A", "K", "Q", "J"]


# ------------------------------------------------------------------ exercise03: Inventory: Mapping-ish Container
from exercises.week08.exercise03.solution import Inventory


def test_empty_inventory_is_falsy():
    inv = Inventory()
    assert bool(inv) is False
    assert len(inv) == 0


def test_add_item_and_str():
    inv = Inventory()
    inv.add_item("bolt", 10)
    inv.add_item("nut", 20)
    assert str(inv) == "Inventory(2 item types)"
    assert bool(inv) is True


def test_add_item_accumulates():
    inv = Inventory()
    inv.add_item("bolt", 10)
    inv.add_item("bolt", 5)
    assert inv.items["bolt"] == 15


def test_contains():
    inv = Inventory()
    inv.add_item("bolt", 10)
    assert "bolt" in inv
    assert "screw" not in inv


def test_iter_yields_names():
    inv = Inventory()
    inv.add_item("bolt", 10)
    inv.add_item("nut", 20)
    assert set(inv) == {"bolt", "nut"}


# ------------------------------------------------------------------ exercise04: Callables
from exercises.week08.exercise04.solution import Multiplier, Adder, Toggler


def test_multiplier():
    double = Multiplier(2)
    assert double(5) == 10


def test_adder():
    add5 = Adder(5)
    assert add5(10) == 15


def test_toggler_carries_state():
    toggle = Toggler()
    assert toggle() is True
    assert toggle() is False
    assert toggle() is True


def test_instances_are_callable():
    assert callable(Multiplier(2))
    assert callable(Adder(1))
    assert callable(Toggler())


# ------------------------------------------------------------------ exercise05: NumberRange: A Read-Only Sequence
import pytest
from exercises.week08.exercise05.solution import NumberRange


def test_number_range_repr():
    assert repr(NumberRange(1, 5)) == "NumberRange(1, 5)"


def test_number_range_eq_and_hash():
    assert NumberRange(1, 5) == NumberRange(1, 5)
    assert len({NumberRange(1, 5), NumberRange(1, 5), NumberRange(2, 6)}) == 2


def test_number_range_len():
    assert len(NumberRange(1, 5)) == 4
    assert len(NumberRange(5, 5)) == 0


def test_number_range_getitem():
    r = NumberRange(10, 15)
    assert r[0] == 10
    assert r[4] == 14
    with pytest.raises(IndexError):
        r[5]


def test_number_range_iter():
    assert list(NumberRange(1, 5)) == [1, 2, 3, 4]


def test_number_range_contains():
    r = NumberRange(1, 5)
    assert 3 in r
    assert 5 not in r


def test_number_range_bool():
    assert bool(NumberRange(1, 5)) is True
    assert bool(NumberRange(5, 5)) is False


# ------------------------------------------------------------------ exercise06: Money and Score: Operator Overloading
from exercises.week08.exercise06.solution import Money, Score


def test_money_add_and_eq():
    assert Money(100) + Money(50) == Money(150)


def test_money_sum():
    assert sum([Money(100), Money(200), Money(300)]) == Money(600)


def test_money_hash():
    assert len({Money(100), Money(100), Money(200)}) == 2


def test_score_add_and_eq():
    assert Score(10) + Score(5) == Score(15)


def test_score_sum():
    assert sum([Score(1), Score(2), Score(3)]) == Score(6)


def test_money_repr():
    assert repr(Money(500)) == "Money(500)"


# ------------------------------------------------------------------ exercise07: Context Managers as a Protocol
import pytest
from exercises.week08.exercise07.solution import ResourceGuard, Transaction, SuppressAll


def test_resource_guard_active_during_block():
    guard = ResourceGuard()
    with guard:
        assert guard.active is True
    assert guard.active is False


def test_transaction_commits_on_success():
    with Transaction() as tx:
        pass
    assert tx.committed is True
    assert tx.rolled_back is False


def test_transaction_rolls_back_on_exception():
    with pytest.raises(RuntimeError):
        with Transaction() as tx:
            raise RuntimeError("boom")
    assert tx.rolled_back is True
    assert tx.committed is False


def test_suppress_all_swallows_any_exception():
    with SuppressAll():
        raise ValueError("this never propagates")
    with SuppressAll():
        raise KeyError("neither does this")


def test_no_special_base_class():
    assert ResourceGuard.__bases__ == (object,)
    assert Transaction.__bases__ == (object,)
    assert SuppressAll.__bases__ == (object,)
