"""
Tests for stage08/exercise05 -- The Python Data Model: NumberRange: A Read-Only Sequence.
Auto-generated by generate.py from generator/stage08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage08.exercise05.solution import NumberRange


def test_number_range_repr():
    assert repr(NumberRange(1, 5)) == "NumberRange(1, 5)"


def test_number_range_eq_and_hash():
    assert NumberRange(1, 5) == NumberRange(1, 5)
    assert len({NumberRange(1, 5), NumberRange(1, 5), NumberRange(2, 6)}) == 2


def test_number_range_len():
    assert len(NumberRange(1, 5)) == 4
    assert len(NumberRange(5, 5)) == 0


def test_number_range_getitem():
    r = NumberRange(10, 15)
    assert r[0] == 10
    assert r[4] == 14
    with pytest.raises(IndexError):
        r[5]


def test_number_range_iter():
    assert list(NumberRange(1, 5)) == [1, 2, 3, 4]


def test_number_range_contains():
    r = NumberRange(1, 5)
    assert 3 in r
    assert 5 not in r


def test_number_range_bool():
    assert bool(NumberRange(1, 5)) is True
    assert bool(NumberRange(5, 5)) is False
