"""
Tests for stage04/tier2_mid02 -- Data Structures: League Membership Analyzer.
Auto-generated by generate.py from generator/stage04.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage04.tier2_mid02.solution import (
    both_conferences,
    all_players,
    east_only,
    west_only,
    symmetric_difference_manual,
)

EAST = {"Ava", "Ben", "Cy", "Dee"}
WEST = {"Cy", "Dee", "Emi", "Finn"}


def test_both_conferences_intersection():
    """both_conferences == east & west."""
    assert both_conferences(EAST, WEST) == {"Cy", "Dee"}


def test_all_players_union():
    """all_players == east | west."""
    assert all_players(EAST, WEST) == {"Ava", "Ben", "Cy", "Dee", "Emi", "Finn"}


def test_east_only_difference():
    """east_only == east - west."""
    assert east_only(EAST, WEST) == {"Ava", "Ben"}


def test_west_only_difference_is_not_symmetric_with_east_only():
    """west_only == west - east, which differs from east - west -- difference is directional."""
    assert west_only(EAST, WEST) == {"Emi", "Finn"}
    assert west_only(EAST, WEST) != east_only(EAST, WEST)


def test_symmetric_difference_manual_matches_builtin_xor():
    """symmetric_difference_manual, built from (east - west) | (west - east), must equal Python's east ^ west."""
    result = symmetric_difference_manual(EAST, WEST)
    assert result == {"Ava", "Ben", "Emi", "Finn"}
    assert result == (EAST ^ WEST)
