"""
Tests for stage02/tier2_mid01 -- Control Flow: Shift Coverage Checker.
Auto-generated by generate.py from generator/stage02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import exercises.stage02.tier2_mid01.solution as solution


def test_all_checked_in_via_for_else():
    """all_checked_in must be False as soon as a scheduled name isn't checked in (for...else, break)."""
    assert solution.all_checked_in is False


def test_missing_list():
    """missing_list == every scheduled name not in checked_in_names, in original order."""
    assert solution.missing_list == ["Cy", "Ella"]


def test_first_missing_has_long_shift_short_circuit():
    """One `and` expression: len(missing_list) > 0 guards indexing missing_list[0] safely."""
    assert solution.first_missing_has_long_shift is True


def test_coverage_status_ternary():
    """coverage_status == "full" if missing_list is empty else "short-staffed", as a ternary expression."""
    assert solution.coverage_status == "short-staffed"


def test_overtime_names_via_zip():
    """overtime_names built by walking zip(scheduled_names, shift_hours), not manual indexing."""
    assert solution.overtime_names == ["Cy"]
