"""
Tests for stage11/tier3_advanced02 -- OpenCV: Hand Posture & Face Gesture Recognition: Face Gesture and Gaze Direction (Driver-Camera Style).
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from unittest.mock import Mock
import cv2
import numpy as np
from exercises.stage11.tier3_advanced02.solution import (
    load_face_cascade,
    load_eye_cascade,
    load_smile_cascade,
    is_cascade_loaded,
    detect_smile,
    estimate_gaze_direction,
)


def test_load_face_cascade_loads_successfully():
    """load_face_cascade must load one of OpenCV's own bundled, already-trained cascades."""
    assert is_cascade_loaded(load_face_cascade()) is True


def test_load_eye_cascade_loads_successfully():
    """load_eye_cascade must load successfully too."""
    assert is_cascade_loaded(load_eye_cascade()) is True


def test_load_smile_cascade_loads_successfully():
    """load_smile_cascade must load successfully -- a facial GESTURE detector, not just a face detector."""
    assert is_cascade_loaded(load_smile_cascade()) is True


def test_is_cascade_loaded_false_for_a_bad_path():
    """is_cascade_loaded must be False when the classifier failed to load."""
    bad_cascade = cv2.CascadeClassifier("/nonexistent/cascade.xml")
    assert is_cascade_loaded(bad_cascade) is False


def test_detect_smile_uses_the_tuned_scale_and_neighbors():
    """detect_smile must call detectMultiScale with scaleFactor=1.7, minNeighbors=20, and interpret len()>0 as a smile."""
    region = np.zeros((50, 50), dtype=np.uint8)

    smiling_cascade = Mock()
    smiling_cascade.detectMultiScale.return_value = [(10, 10, 20, 20)]
    assert detect_smile(region, smiling_cascade) is True
    smiling_cascade.detectMultiScale.assert_called_once_with(region, scaleFactor=1.7, minNeighbors=20)

    neutral_cascade = Mock()
    neutral_cascade.detectMultiScale.return_value = []
    assert detect_smile(region, neutral_cascade) is False


def test_estimate_gaze_direction_center():
    """Eyes centered within the face box must estimate "center"."""
    face = (100, 80, 200, 200)
    eyes = [(150, 120, 30, 20), (230, 120, 30, 20)]
    assert estimate_gaze_direction(face, eyes) == "center"


def test_estimate_gaze_direction_left_and_right():
    """Eyes shifted well to one side of the face center must estimate that side."""
    face = (100, 80, 200, 200)
    left_eyes = [(110, 120, 30, 20), (150, 120, 30, 20)]
    right_eyes = [(250, 120, 30, 20), (290, 120, 30, 20)]
    assert estimate_gaze_direction(face, left_eyes) == "left"
    assert estimate_gaze_direction(face, right_eyes) == "right"


def test_estimate_gaze_direction_no_eyes_is_looking_away():
    """No detected eyes at all must estimate "looking_away", not crash or default to "center"."""
    face = (100, 80, 200, 200)
    assert estimate_gaze_direction(face, []) == "looking_away"
