"""
Tests for stage07/basic02 -- OOP II: Vehicle Fleet.
Auto-generated by generate.py from generator/stage07.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage07.basic02.solution import (
    Vehicle,
    Car,
    ElectricCar,
    fleet_summary,
    is_car,
)


def test_vehicle_describe():
    """Vehicle.describe() == f"{make} {model}"."""
    assert Vehicle("Honda", "Civic").describe() == "Honda Civic"


def test_car_describe_extends_vehicle_via_super():
    """Car.describe() must call super().describe() and append to it, not rewrite the whole string."""
    assert Car("Honda", "Civic", 4).describe() == "Honda Civic (4 doors)"


def test_electric_car_describe_extends_car_via_super():
    """ElectricCar.describe() extends Car.describe() via super(), which itself extends Vehicle.describe() -- a three-level chain."""
    car = ElectricCar("Tesla", "Model 3", 4, 75)
    assert car.describe() == "Tesla Model 3 (4 doors), 75kWh battery"


def test_fleet_summary_polymorphism_across_all_three_classes():
    """fleet_summary works across a mixed list of Vehicle/Car/ElectricCar via polymorphism."""
    vehicles = [Vehicle("A", "B"), Car("C", "D", 2), ElectricCar("E", "F", 4, 50)]
    assert fleet_summary(vehicles) == "A B, C D (2 doors), E F (4 doors), 50kWh battery"


def test_is_car():
    """is_car == isinstance(vehicle, Car) -- True for ElectricCar too (it IS a Car), False for a plain Vehicle."""
    assert is_car(Car("C", "D", 2)) is True
    assert is_car(ElectricCar("E", "F", 4, 50)) is True
    assert is_car(Vehicle("A", "B")) is False
