"""
Tests for week03/exercise05 -- Functions: Decorators.
Auto-generated by generate.py from generator/week03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week03.exercise05.solution import log_calls, count_calls, uppercase_result


def test_log_calls_tracks_call_count():
    @log_calls
    def add(a, b):
        return a + b

    assert add(1, 2) == 3
    assert add(2, 2) == 4
    assert add.calls == 2


def test_log_calls_preserves_metadata():
    @log_calls
    def greet(name):
        """Say hello."""
        return f"hi {name}"

    assert greet.__name__ == "greet"
    assert greet.__doc__ == "Say hello."


def test_count_calls():
    @count_calls
    def noop():
        return None

    noop()
    noop()
    noop()
    assert noop.call_count() == 3


def test_uppercase_result():
    @uppercase_result
    def shout(msg):
        return msg

    assert shout("hello") == "HELLO"


def test_uppercase_result_passthrough_non_str():
    @uppercase_result
    def give_number():
        return 42

    assert give_number() == 42
