"""
Tests for stage01/tier3_advanced01 -- Python Fundamentals: Exact Ledger vs. Float Drift.
Auto-generated by generate.py from generator/stage01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import math
from decimal import Decimal

import exercises.stage01.tier3_advanced01.solution as solution


def test_casts_and_float_total():
    """price_each_float is a float() cast, quantity is an int() cast; float_total is plain float arithmetic."""
    assert isinstance(solution.price_each_float, float)
    assert isinstance(solution.quantity, int)
    assert solution.float_total == solution.price_each_float * 7


def test_exact_total_is_precise_decimal():
    """exact_total must be Decimal(price_each_text) * Decimal(quantity_text) -- built from the STRINGS, not the float."""
    assert solution.exact_total == Decimal("139.93")


def test_totals_are_not_exactly_equal_due_to_float_drift():
    """totals_are_exactly_equal == (float(exact_total) == float_total) -- this is False; that's the whole point."""
    assert solution.totals_are_exactly_equal is False


def test_totals_are_close():
    """totals_are_close == math.isclose(float(exact_total), float_total) -- the correct way to compare these."""
    assert solution.totals_are_close is True


def test_point_one_plus_point_two_textbook_case():
    """The classic case: 0.1 + 0.2 != 0.3 exactly, but math.isclose() says they're close."""
    assert solution.is_exactly_point_three is False
    assert solution.is_close_to_point_three is True
    assert math.isclose(solution.point_one_plus_point_two, 0.3)
