"""
Tests for stage13/exercise01 -- Local API Endpoints: Basic Routes.
Auto-generated by generate.py from generator/stage13.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from fastapi.testclient import TestClient
from exercises.stage13.exercise01.solution import app as basic_routes_app

basic_routes_client = TestClient(basic_routes_app)


def test_read_root():
    assert basic_routes_client.get("/").json() == {"message": "hello"}


def test_read_item_path_parameter():
    assert basic_routes_client.get("/items/42").json() == {"item_id": 42}


def test_search_query_parameter():
    assert basic_routes_client.get("/search?q=python").json() == {"q": "python"}


def test_search_default_query_parameter():
    assert basic_routes_client.get("/search").json() == {"q": ""}


def test_echo_post():
    assert basic_routes_client.post("/echo", json={"a": 1}).json() == {"a": 1}
