"""
Tests for stage04/tier1_basic01 -- Data Structures: Race Results Ledger.
Auto-generated by generate.py from generator/stage04.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage04.tier1_basic01.solution import (
    build_results,
    rank_by_time,
    fastest_n,
    podium_labels,
    racer_count,
)

NAMES = ["Ava", "Ben", "Cy", "Dee", "Emi"]
TIMES = [54.2, 49.8, 61.0, 49.8, 57.3]


def test_build_results_via_append_and_zip():
    """build_results must loop over zip(names, times), .append()-ing (name, time) tuples -- not just wrap zip() in list()."""
    results = build_results(NAMES, TIMES)
    assert results == [("Ava", 54.2), ("Ben", 49.8), ("Cy", 61.0), ("Dee", 49.8), ("Emi", 57.3)]
    assert isinstance(results[0], tuple)


def test_rank_by_time_does_not_mutate_input():
    """rank_by_time uses sorted(), which returns a new list and leaves the original untouched."""
    results = build_results(NAMES, TIMES)
    ranked = rank_by_time(results)
    assert ranked[0] == ("Ben", 49.8)
    assert results[0] == ("Ava", 54.2)


def test_fastest_n_slices_ranked_results():
    """fastest_n(ranked_results, n) == ranked_results[:n]."""
    ranked = rank_by_time(build_results(NAMES, TIMES))
    assert fastest_n(ranked, 3) == [("Ben", 49.8), ("Dee", 49.8), ("Ava", 54.2)]


def test_podium_labels_uses_enumerate_in_a_comprehension():
    """podium_labels builds one f-string label per entry via enumerate() inside a list comprehension."""
    fastest = fastest_n(rank_by_time(build_results(NAMES, TIMES)), 3)
    assert podium_labels(fastest) == ["1. Ben (49.8s)", "2. Dee (49.8s)", "3. Ava (54.2s)"]


def test_racer_count():
    """racer_count == len(names)."""
    assert racer_count(NAMES) == 5
