"""
Tests for stage02/tier1_basic02 -- Control Flow: Bus Route Ticket Counter.
Auto-generated by generate.py from generator/stage02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import exercises.stage02.tier1_basic02.solution as solution


def test_passengers_after_processing():
    """passengers reflects IN:/OUT: events up to (not including) the one that triggers overflow."""
    assert solution.passengers == 2


def test_trip_ended_early_flag():
    """trip_ended_early is True once an IN:n would push passengers over capacity."""
    assert solution.trip_ended_early is True


def test_skip_event_uses_continue():
    """A "SKIP" event must be a no-op -- passengers unaffected either way."""
    # passengers already covers this indirectly: 2+1-1=2, SKIP contributes nothing.
    assert solution.passengers == 2


def test_bad_event_uses_pass_not_a_crash():
    """A malformed event ("BAD") must be silently ignored (pass), not raise or change state."""
    assert solution.passengers == 2


def test_total_seats_via_nested_for():
    """total_seats == sections * rows_per_section * seats_per_row, built with nested for-loops and +=."""
    assert solution.total_seats == 12


def test_capacity_is_valid():
    """capacity_is_valid == (capacity <= total_seats)."""
    assert solution.capacity_is_valid is True
