"""
Tests for stage08/tier2_mid02 -- The Python Data Model: Inventory and Callables.
Auto-generated by generate.py from generator/stage08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage08.tier2_mid02.solution import Inventory, Multiplier, Adder, Toggler


def test_empty_inventory_is_falsy():
    """__bool__ makes an empty Inventory falsy."""
    inv = Inventory()
    assert bool(inv) is False


def test_add_item_makes_inventory_truthy():
    """Adding an item makes __bool__ return True."""
    inv = Inventory()
    inv.add_item("bolt", 10)
    assert bool(inv) is True


def test_add_item_accumulates():
    """add_item must accumulate quantities for the same name, not overwrite."""
    inv = Inventory()
    inv.add_item("bolt", 10)
    inv.add_item("bolt", 5)
    assert inv.items["bolt"] == 15


def test_contains():
    """__contains__ makes the `in` operator work against item names."""
    inv = Inventory()
    inv.add_item("bolt", 10)
    assert "bolt" in inv
    assert "screw" not in inv


def test_iter_yields_names():
    """__iter__ must yield item NAMES, same as iterating a plain dict."""
    inv = Inventory()
    inv.add_item("bolt", 10)
    inv.add_item("nut", 20)
    assert set(inv) == {"bolt", "nut"}


def test_multiplier_and_adder_are_callable():
    """__call__ makes instances directly callable like a function."""
    double = Multiplier(2)
    add5 = Adder(5)
    assert double(5) == 10
    assert add5(10) == 15
    assert callable(double)
    assert callable(add5)


def test_toggler_carries_state_across_calls():
    """Toggler's __call__ must flip and return its own state each call, like a stateful closure."""
    toggle = Toggler()
    assert toggle() is True
    assert toggle() is False
    assert toggle() is True
