"""
Tests for stage02/exercise03 -- Control Flow: Pairing and Indexing.
Auto-generated by generate.py from generator/stage02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage02.exercise03.solution import (
    pair_names_scores,
    merge_records,
    count_equal_pairs,
    indexed_items,
    labeled_from,
)


def test_pair_names_scores():
    assert pair_names_scores(["a", "b"], [1, 2]) == [("a", 1), ("b", 2)]


def test_merge_records():
    assert merge_records(["x", "y"], [1, 2]) == {"x": 1, "y": 2}


def test_count_equal_pairs():
    assert count_equal_pairs([1, 2, 3], [1, 0, 3]) == 2


def test_indexed_items():
    assert indexed_items(["a", "b"]) == ["0: a", "1: b"]


def test_labeled_from():
    assert labeled_from(["a", "b"], 10) == {10: "a", 11: "b"}
