"""
Tests for stage04/advanced01 -- Data Structures: Log Aggregator.
Auto-generated by generate.py from generator/stage04.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage04.advanced01.solution import (
    entries_by_level,
    level_counts,
    most_common_level,
    last_n_entries,
    rotate_entries,
)

ENTRIES = ["ERROR:disk", "INFO:boot", "ERROR:disk", "WARN:mem", "ERROR:net", "INFO:boot", "ERROR:disk"]


def test_entries_by_level_uses_defaultdict():
    """entries_by_level buckets whole entries under their LEVEL prefix via collections.defaultdict(list)."""
    result = entries_by_level(ENTRIES)
    assert result == {
        "ERROR": ["ERROR:disk", "ERROR:disk", "ERROR:net", "ERROR:disk"],
        "INFO": ["INFO:boot", "INFO:boot"],
        "WARN": ["WARN:mem"],
    }


def test_level_counts_uses_counter():
    """level_counts == dict(collections.Counter(levels))."""
    assert level_counts(ENTRIES) == {"ERROR": 4, "INFO": 2, "WARN": 1}


def test_most_common_level_uses_counter_most_common():
    """most_common_level == collections.Counter(levels).most_common(1)[0]."""
    assert most_common_level(ENTRIES) == ("ERROR", 4)


def test_last_n_entries_uses_bounded_deque():
    """last_n_entries pushes onto a collections.deque(maxlen=n), keeping only the most recent n."""
    assert last_n_entries(ENTRIES, 3) == ["ERROR:net", "INFO:boot", "ERROR:disk"]


def test_rotate_entries_uses_deque_rotate():
    """rotate_entries builds a collections.deque(entries) and calls .rotate(k)."""
    assert rotate_entries(ENTRIES, 2) == [
        "INFO:boot", "ERROR:disk", "ERROR:disk", "INFO:boot", "ERROR:disk", "WARN:mem", "ERROR:net",
    ]
