"""
Tests for week06/exercise04 -- OOP I: Slots and Memory.
Auto-generated by generate.py from generator/week06.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.week06.exercise04.solution import PointSlots, Vector3DSlots, TemperatureSlots


def test_point_slots_basic():
    p = PointSlots(1, 2)
    assert (p.x, p.y) == (1, 2)


def test_point_slots_has_no_dict():
    p = PointSlots(1, 2)
    assert not hasattr(p, "__dict__")


def test_point_slots_rejects_new_attribute():
    p = PointSlots(1, 2)
    with pytest.raises(AttributeError):
        p.z = 3


def test_vector3d_slots_magnitude():
    v = Vector3DSlots(2, 3, 6)
    assert v.magnitude() == 7.0


def test_temperature_slots_fahrenheit():
    t = TemperatureSlots(0)
    assert t.fahrenheit() == 32.0
