"""
Aggregated tests for week10 -- Pandas.
Auto-generated by generate.py from generator/week10.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: Reading and Inspecting
import pandas as pd
from exercises.week10.exercise01.solution import (
    load_csv,
    preview_rows,
    summarize,
    capture_info,
)


def test_load_csv(tmp_path):
    path = tmp_path / "data.csv"
    path.write_text("name,sales\nAda,100\nGrace,200\n")
    df = load_csv(str(path))
    assert list(df.columns) == ["name", "sales"]
    assert len(df) == 2


def test_preview_rows():
    df = pd.DataFrame({"x": range(10)})
    assert len(preview_rows(df, 3)) == 3


def test_summarize():
    df = pd.DataFrame({"sales": [10, 20, 30]})
    result = summarize(df)
    assert result.loc["mean", "sales"] == 20.0


def test_capture_info():
    df = pd.DataFrame({"x": [1, 2, 3]})
    text = capture_info(df)
    assert "RangeIndex" in text


# ------------------------------------------------------------------ exercise02: Boolean Indexing
import pandas as pd
from exercises.week10.exercise02.solution import (
    filter_by_region,
    filter_high_sales,
    filter_multiple_conditions,
)


def _filter_sample_df():
    return pd.DataFrame({
        "region": ["east", "west", "east", "west"],
        "product": ["A", "B", "C", "D"],
        "sales": [100, 250, 50, 300],
    })


def test_filter_by_region():
    result = filter_by_region(_filter_sample_df(), "east")
    assert list(result["product"]) == ["A", "C"]


def test_filter_high_sales():
    result = filter_high_sales(_filter_sample_df(), 100)
    assert list(result["product"]) == ["B", "D"]


def test_filter_multiple_conditions():
    result = filter_multiple_conditions(_filter_sample_df(), "west", 100)
    assert list(result["product"]) == ["B", "D"]


# ------------------------------------------------------------------ exercise03: Sorting and Grouping
import pandas as pd
from exercises.week10.exercise03.solution import (
    sort_by_sales_desc,
    sort_by_multiple,
    total_sales_by_region,
    avg_sales_by_region_and_product,
    orders_per_region_sorted,
)


def _group_sample_df():
    return pd.DataFrame({
        "region": ["east", "west", "east", "west", "east"],
        "product": ["A", "A", "B", "B", "A"],
        "sales": [100, 250, 50, 300, 150],
    })


def test_sort_by_sales_desc():
    result = sort_by_sales_desc(_group_sample_df())
    assert list(result["sales"]) == [300, 250, 150, 100, 50]


def test_sort_by_multiple():
    result = sort_by_multiple(_group_sample_df())
    assert list(result["region"]) == ["east", "east", "east", "west", "west"]
    assert list(result["sales"])[:3] == [150, 100, 50]


def test_total_sales_by_region():
    result = total_sales_by_region(_group_sample_df())
    assert result["east"] == 300
    assert result["west"] == 550


def test_avg_sales_by_region_and_product_is_multi_indexed():
    result = avg_sales_by_region_and_product(_group_sample_df())
    assert isinstance(result.index, pd.MultiIndex)
    assert result[("east", "A")] == 125.0


def test_orders_per_region_sorted():
    result = orders_per_region_sorted(_group_sample_df())
    assert list(result.index) == ["east", "west"]
    assert list(result.values) == [3, 2]


# ------------------------------------------------------------------ exercise04: Merging and Pivoting
import pandas as pd
from exercises.week10.exercise04.solution import (
    merge_customer_info,
    merge_with_suffixes,
    inner_join_products,
    sales_pivot_table,
    sales_pivot_count,
)


def test_merge_customer_info():
    orders = pd.DataFrame({"customer_id": [1, 2], "amount": [50, 75]})
    customers = pd.DataFrame({"customer_id": [1, 2], "name": ["Ada", "Grace"]})
    result = merge_customer_info(orders, customers)
    assert list(result["name"]) == ["Ada", "Grace"]


def test_merge_with_suffixes_keeps_unmatched_left_rows():
    df1 = pd.DataFrame({"id": [1, 2, 3], "value": ["a", "b", "c"]})
    df2 = pd.DataFrame({"id": [1, 2], "value": ["x", "y"]})
    result = merge_with_suffixes(df1, df2)
    assert len(result) == 3
    assert "value_left" in result.columns and "value_right" in result.columns


def test_inner_join_products_drops_unmatched():
    orders = pd.DataFrame({"product_id": [1, 2, 3]})
    products = pd.DataFrame({"product_id": [1, 2], "name": ["Widget", "Gadget"]})
    result = inner_join_products(orders, products)
    assert len(result) == 2


def _pivot_sample_df():
    return pd.DataFrame({
        "region": ["east", "east", "west"],
        "product": ["A", "B", "A"],
        "sales": [100, 50, 200],
    })


def test_sales_pivot_table():
    result = sales_pivot_table(_pivot_sample_df())
    assert result.loc["east", "A"] == 100
    assert result.loc["west", "A"] == 200


def test_sales_pivot_count():
    result = sales_pivot_count(_pivot_sample_df())
    assert result.loc["east", "A"] == 1


# ------------------------------------------------------------------ exercise05: Apply and Dtype Optimization
import pandas as pd
from exercises.week10.exercise05.solution import (
    add_sales_tax_column,
    categorize_sales,
    full_name_column,
    optimize_dtypes,
    set_region_product_index,
)


def test_add_sales_tax_column():
    df = pd.DataFrame({"sales": [100, 200]})
    result = add_sales_tax_column(df, 0.1)
    assert list(result["total"]) == [110.0, 220.0]


def test_categorize_sales():
    df = pd.DataFrame({"sales": [50, 150, 350]})
    result = categorize_sales(df)
    assert list(result["tier"]) == ["low", "medium", "high"]


def test_full_name_column():
    df = pd.DataFrame({"first": ["Ada", "Grace"], "last": ["Lovelace", "Hopper"]})
    result = full_name_column(df)
    assert list(result["full_name"]) == ["Ada Lovelace", "Grace Hopper"]


def test_optimize_dtypes():
    df = pd.DataFrame({"region": ["east", "west", "east"]})
    result = optimize_dtypes(df)
    assert str(result["region"].dtype) == "category"


def test_set_region_product_index():
    df = pd.DataFrame({"region": ["east", "west"], "product": ["A", "B"], "sales": [1, 2]})
    result = set_region_product_index(df)
    assert isinstance(result.index, pd.MultiIndex)
    assert result.loc[("east", "A"), "sales"] == 1
