"""
Tests for stage13/exercise04 -- Local API Endpoints: Async Endpoints.
Auto-generated by generate.py from generator/stage13.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from fastapi.testclient import TestClient
from exercises.stage13.exercise04.solution import app as async_app

async_client = TestClient(async_app)


def test_async_hello():
    assert async_client.get("/async-hello").json() == {"message": "hello async"}


def test_async_get_item():
    assert async_client.get("/async-items/7").json() == {"item_id": 7}


def test_async_echo():
    assert async_client.post("/async-echo", json={"x": 1}).json() == {"x": 1}
