"""
Tests for stage02/advanced02 -- Control Flow: Round-Robin Task Scheduler.
Auto-generated by generate.py from generator/stage02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import exercises.stage02.advanced02.solution as solution


def test_all_tasks_via_chain():
    """all_tasks == morning_tasks followed by afternoon_tasks, via itertools.chain."""
    assert solution.all_tasks == ["t1", "t2", "t3", "t4", "t5", "t6", "t7"]


def test_assignments_round_robin_via_cycle():
    """assignments pairs each task with a worker, cycling through workers via itertools.cycle."""
    assert solution.assignments == [
        ("t1", "alpha"), ("t2", "beta"), ("t3", "gamma"),
        ("t4", "alpha"), ("t5", "beta"), ("t6", "gamma"), ("t7", "alpha"),
    ]


def test_first_three_assignments_via_islice():
    """first_three_assignments == the first 3 of assignments, via itertools.islice."""
    assert solution.first_three_assignments == [("t1", "alpha"), ("t2", "beta"), ("t3", "gamma")]


def test_worker_task_counts():
    """worker_task_counts tallies assignments per worker via dict.get(..., 0) + 1."""
    assert solution.worker_task_counts == {"alpha": 3, "beta": 2, "gamma": 2}
