"""
Tests for stage06/tier2_mid02 -- OOP I: Slotted Records.
Auto-generated by generate.py from generator/stage06.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage06.tier2_mid02.solution import TemperatureSlots, InventoryItemSlots


def test_temperature_slots_fahrenheit():
    """fahrenheit() == celsius * 9 / 5 + 32."""
    t = TemperatureSlots(0)
    assert t.fahrenheit() == 32.0


def test_inventory_item_slots_total_value():
    """total_value() == round(price * quantity, 2)."""
    item = InventoryItemSlots("Widget", 2.5, 4)
    assert item.total_value() == 10.0


def test_inventory_item_slots_rejects_new_attribute():
    """Setting an attribute not named in __slots__ must raise AttributeError."""
    item = InventoryItemSlots("Widget", 2.5, 4)
    with pytest.raises(AttributeError):
        item.discount = 0.1
