"""
Tests for stage10/exercise01 -- Pandas: Reading and Inspecting.
Auto-generated by generate.py from generator/stage10.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pandas as pd
from exercises.stage10.exercise01.solution import (
    load_csv,
    preview_rows,
    summarize,
    capture_info,
)


def test_load_csv(tmp_path):
    path = tmp_path / "data.csv"
    path.write_text("name,sales\nAda,100\nGrace,200\n")
    df = load_csv(str(path))
    assert list(df.columns) == ["name", "sales"]
    assert len(df) == 2


def test_preview_rows():
    df = pd.DataFrame({"x": range(10)})
    assert len(preview_rows(df, 3)) == 3


def test_summarize():
    df = pd.DataFrame({"sales": [10, 20, 30]})
    result = summarize(df)
    assert result.loc["mean", "sales"] == 20.0


def test_capture_info():
    df = pd.DataFrame({"x": [1, 2, 3]})
    text = capture_info(df)
    assert "RangeIndex" in text
