"""
Tests for stage01/exercise02 -- Python Fundamentals: Temperature and BMI.
Auto-generated by generate.py from generator/stage01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage01.exercise02.solution import (
    celsius_to_fahrenheit,
    bmi_calculator,
    validate_measurement,
)


def test_celsius_to_fahrenheit_freezing():
    assert celsius_to_fahrenheit(0) == 32.0


def test_celsius_to_fahrenheit_boiling():
    assert celsius_to_fahrenheit(100) == 212.0


def test_bmi_calculator():
    assert abs(bmi_calculator(70, 1.75) - 22.86) < 0.01


def test_validate_measurement_accepts_int_and_float():
    assert validate_measurement(70) is True
    assert validate_measurement(1.75) is True


def test_validate_measurement_rejects_bool():
    assert validate_measurement(True) is False
    assert validate_measurement(False) is False


def test_validate_measurement_rejects_str():
    assert validate_measurement("70") is False
