"""
Tests for stage11/tier1_basic01 -- OpenCV: Image I/O, Shape, and NumPy Arrays.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import numpy as np
from exercises.stage11.tier1_basic01.solution import (
    load_image,
    save_image,
    get_dimensions,
    get_channel_count,
    create_blank_image,
    crop_image,
)


def test_save_and_load_roundtrip(tmp_path):
    """save_image/load_image round-trip via cv2.imwrite/cv2.imread."""
    path = str(tmp_path / "img.png")
    original = np.zeros((20, 30, 3), dtype=np.uint8)
    original[:, :] = (0, 0, 255)
    assert save_image(path, original) is True
    loaded = load_image(path)
    assert loaded is not None
    assert loaded.shape == (20, 30, 3)


def test_load_missing_file_returns_none():
    """cv2.imread must return None (not raise) for a missing file."""
    assert load_image("/nonexistent/path/to/image.png") is None


def test_get_dimensions_is_height_then_width():
    """get_dimensions == image.shape[:2] -- height first, not (width, height)."""
    image = np.zeros((20, 30, 3), dtype=np.uint8)
    assert get_dimensions(image) == (20, 30)


def test_get_channel_count_color_vs_grayscale():
    """get_channel_count reads image.shape[2] for color, defaults to 1 for grayscale (2D)."""
    color = np.zeros((10, 10, 3), dtype=np.uint8)
    gray = np.zeros((10, 10), dtype=np.uint8)
    assert get_channel_count(color) == 3
    assert get_channel_count(gray) == 1


def test_create_blank_image():
    """create_blank_image == np.zeros((height, width, channels), dtype=np.uint8)."""
    image = create_blank_image(10, 20, 3)
    assert image.shape == (10, 20, 3)
    assert image.sum() == 0


def test_crop_image_is_plain_array_slicing():
    """crop_image must be image[y1:y2, x1:x2] -- rows before columns."""
    image = np.arange(100).reshape(10, 10).astype(np.uint8)
    cropped = crop_image(image, 2, 5, 3, 6)
    assert cropped.shape == (3, 3)
