"""
Tests for stage09/tier1_basic01 -- OS, JSON, Datetime, XML: Config File Manager.
Auto-generated by generate.py from generator/stage09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage09.tier1_basic01.solution import (
    config_path,
    config_exists,
    save_config,
    load_config,
    list_config_names,
)


def test_config_path_joins_directory_and_json_suffix():
    """config_path == os.path.join(directory, name + ".json")."""
    assert config_path("dir", "app") in ("dir/app.json", "dir\\app.json")


def test_config_exists_before_and_after_save(tmp_path):
    """config_exists uses os.path.exists against the computed config_path."""
    d = str(tmp_path)
    assert config_exists(d, "app") is False
    save_config(d, "app", {"debug": True})
    assert config_exists(d, "app") is True


def test_save_and_load_config_roundtrip(tmp_path):
    """save_config writes JSON; load_config reads it back via json.load."""
    d = str(tmp_path)
    save_config(d, "app", {"debug": True, "retries": 3})
    assert load_config(d, "app") == {"debug": True, "retries": 3}


def test_list_config_names_strips_json_suffix(tmp_path):
    """list_config_names must list only *.json files, sorted, with the suffix stripped."""
    d = str(tmp_path)
    save_config(d, "app", {})
    save_config(d, "db", {})
    (tmp_path / "notes.txt").write_text("ignore me")
    assert list_config_names(d) == ["app", "db"]
