"""
Tests for stage11/exercise06 -- OpenCV: NumPy Arrays and Cascade Classifiers.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import cv2
import numpy as np
from exercises.stage11.exercise06.solution import (
    create_blank_image,
    crop_image,
    paste_region,
    load_default_face_cascade,
    load_cascade_from_path,
    is_cascade_loaded,
)


def test_create_blank_image():
    image = create_blank_image(10, 20, 3)
    assert image.shape == (10, 20, 3)
    assert image.sum() == 0


def test_crop_image():
    image = np.arange(100).reshape(10, 10).astype(np.uint8)
    cropped = crop_image(image, 2, 5, 3, 6)
    assert cropped.shape == (3, 3)


def test_paste_region_does_not_mutate_original():
    image = np.zeros((10, 10), dtype=np.uint8)
    region = np.full((3, 3), 255, dtype=np.uint8)
    result = paste_region(image, region, 2, 2)
    assert image.sum() == 0
    assert result[2, 2] == 255


def test_load_default_face_cascade_loads_successfully():
    cascade = load_default_face_cascade()
    assert is_cascade_loaded(cascade) is True


def test_load_cascade_from_bad_path_fails_to_load():
    cascade = load_cascade_from_path("/nonexistent/cascade.xml")
    assert is_cascade_loaded(cascade) is False


def test_load_cascade_from_good_path():
    good_path = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
    cascade = load_cascade_from_path(good_path)
    assert is_cascade_loaded(cascade) is True
