"""
Tests for stage02/advanced01 -- Control Flow: Custom Iterator: CountdownTimer.
Auto-generated by generate.py from generator/stage02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest

from exercises.stage02.advanced01.solution import CountdownTimer


def test_list_of_countdown_timer():
    """list(CountdownTimer(3)) walks __iter__ then __next__ repeatedly -- [3, 2, 1, 0]."""
    assert list(CountdownTimer(3)) == [3, 2, 1, 0]


def test_iter_returns_self():
    """__iter__ must return self -- CountdownTimer is its own iterator."""
    timer = CountdownTimer(2)
    assert iter(timer) is timer


def test_next_raises_stopiteration_when_exhausted():
    """__next__ must raise StopIteration once current < 0."""
    timer = CountdownTimer(0)
    assert next(timer) == 0
    with pytest.raises(StopIteration):
        next(timer)


def test_next_keeps_raising_after_exhaustion():
    """Calling __next__ again after StopIteration must raise StopIteration again, not resume or crash."""
    timer = CountdownTimer(0)
    next(timer)
    with pytest.raises(StopIteration):
        next(timer)
    with pytest.raises(StopIteration):
        next(timer)


def test_for_loop_consumes_it_correctly():
    """A real `for` loop must consume the whole sequence via the protocol, not just list()."""
    collected = []
    for value in CountdownTimer(2):
        collected.append(value)
    assert collected == [2, 1, 0]
