"""
Tests for stage13/tier1_basic01 -- Local API Endpoints: Basic Routes.
Auto-generated by generate.py from generator/stage13.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from fastapi.testclient import TestClient
from exercises.stage13.tier1_basic01.solution import app as basic_routes_app

basic_routes_client = TestClient(basic_routes_app)


def test_read_root():
    """GET / returns {"message": "hello"}."""
    assert basic_routes_client.get("/").json() == {"message": "hello"}


def test_read_item_path_parameter():
    """{item_id} is a path parameter, auto-converted to int."""
    assert basic_routes_client.get("/items/42").json() == {"item_id": 42}


def test_search_query_parameter():
    """q is a query parameter (?q=...), not part of the route path."""
    assert basic_routes_client.get("/search?q=python").json() == {"q": "python"}


def test_search_default_query_parameter():
    """search's q defaults to "" when omitted."""
    assert basic_routes_client.get("/search").json() == {"q": ""}


def test_echo_post():
    """POST /echo returns the JSON body unchanged."""
    assert basic_routes_client.post("/echo", json={"a": 1}).json() == {"a": 1}
