"""
Tests for stage05/tier3_advanced02 -- Files, Exceptions, Regex: Generator-Based Context Managers.
Auto-generated by generate.py from generator/stage05.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage05.tier3_advanced02.solution import temporary_value, suppress_and_log, timing_block


class _Config:
    debug = False


def test_temporary_value_restores_after_block():
    """temporary_value sets obj.attr for the duration of the with-block, then restores the original."""
    cfg = _Config()
    with temporary_value(cfg, "debug", True):
        assert cfg.debug is True
    assert cfg.debug is False


def test_temporary_value_restores_even_on_exception():
    """The finally inside temporary_value must restore the original value even when the with-block raises."""
    # ValueError, not RuntimeError: NotImplementedError (what an unfinished
    # stub raises) is itself a RuntimeError subclass, so a RuntimeError here
    # would let pytest.raises(RuntimeError) accidentally match an
    # unimplemented temporary_value() instead of only a correct one.
    cfg = _Config()
    with pytest.raises(ValueError):
        with temporary_value(cfg, "debug", True):
            raise ValueError("boom")
    assert cfg.debug is False


def test_suppress_and_log():
    """suppress_and_log catches a matching exception and records str(e) instead of propagating."""
    log = []
    with suppress_and_log(log, ValueError):
        raise ValueError("bad input")
    assert log == ["bad input"]


def test_timing_block():
    """timing_block appends one elapsed-seconds entry via its finally block."""
    results = []
    with timing_block(results):
        pass
    assert len(results) == 1
    assert results[0] >= 0
