"""
Tests for stage08/basic01 -- The Python Data Model: Point: repr, str, eq.
Auto-generated by generate.py from generator/stage08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage08.basic01.solution import Point


def test_repr_is_unambiguous_and_developer_facing():
    """__repr__ must be f"Point(x, y)" -- what a debugger/traceback would show."""
    assert repr(Point(1, 2)) == "Point(1, 2)"


def test_str_is_friendlier_and_differs_from_repr():
    """__str__ must be f"(x, y)" -- friendlier than __repr__, and distinct from it."""
    assert str(Point(1, 2)) == "(1, 2)"
    assert str(Point(1, 2)) != repr(Point(1, 2))


def test_eq_compares_field_values_not_identity():
    """Without a custom __eq__, two distinct Point objects would never compare equal -- this one must compare x/y."""
    assert Point(1, 2) == Point(1, 2)
    assert Point(1, 2) != Point(3, 4)
    assert Point(1, 2) is not Point(1, 2)
