"""
Tests for stage09/exercise05 -- OS, JSON, Datetime, XML: Datetime Basics.
Auto-generated by generate.py from generator/stage09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import datetime
from exercises.stage09.exercise05.solution import (
    current_timestamp_iso,
    format_date,
    parse_iso,
    days_between,
)


def test_current_timestamp_iso_is_parseable():
    text = current_timestamp_iso()
    parsed = datetime.datetime.fromisoformat(text)
    assert isinstance(parsed, datetime.datetime)


def test_format_date():
    dt = datetime.datetime(2024, 3, 15)
    assert format_date(dt) == "2024-03-15"


def test_parse_iso():
    result = parse_iso("2024-03-15T12:00:00")
    assert result == datetime.datetime(2024, 3, 15, 12, 0, 0)


def test_days_between():
    d1 = datetime.date(2024, 1, 1)
    d2 = datetime.date(2024, 1, 11)
    assert days_between(d1, d2) == 10
