"""
Tests for stage08/exercise01 -- The Python Data Model: Vector: The Flagship Dunder Class.
Auto-generated by generate.py from generator/stage08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage08.exercise01.solution import Vector


def test_vector_repr():
    assert repr(Vector(1, 2)) == "Vector(1, 2)"


def test_str():
    assert str(Vector(1, 2)) == "(1, 2)"


def test_eq():
    assert Vector(1, 2) == Vector(1, 2)
    assert Vector(1, 2) != Vector(3, 4)


def test_add():
    assert Vector(1, 2) + Vector(3, 4) == Vector(4, 6)


def test_radd_via_sum():
    total = sum([Vector(1, 1), Vector(2, 2), Vector(3, 3)])
    assert total == Vector(6, 6)


def test_hash_and_set():
    vectors = {Vector(1, 2), Vector(1, 2), Vector(3, 4)}
    assert len(vectors) == 2


def test_vector_bool():
    assert bool(Vector(0, 0)) is False
    assert bool(Vector(1, 0)) is True


def test_vector_getitem():
    v = Vector(5, 7)
    assert v[0] == 5
    assert v[1] == 7
