"""
Aggregated tests for week05 -- Files, Exceptions, Regex.
Auto-generated by generate.py from generator/week05.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: File Basics
from exercises.week05.exercise01.solution import (
    write_lines,
    read_lines,
    append_line,
    count_lines,
)


def test_write_and_read_lines(tmp_path):
    path = str(tmp_path / "data.txt")
    write_lines(path, ["a", "b", "c"])
    assert read_lines(path) == ["a", "b", "c"]


def test_append_line(tmp_path):
    path = str(tmp_path / "data.txt")
    write_lines(path, ["a"])
    append_line(path, "b")
    assert read_lines(path) == ["a", "b"]


def test_count_lines(tmp_path):
    path = str(tmp_path / "data.txt")
    write_lines(path, ["a", "b", "c", "d"])
    assert count_lines(path) == 4


# ------------------------------------------------------------------ exercise02: Exceptions and Hierarchies
import pytest
from exercises.week05.exercise02.solution import (
    ValidationError,
    NegativeValueError,
    validate_positive,
    safe_parse_int,
    divide_with_cleanup,
    get_attempts,
    reset_attempts,
)


def test_validate_positive_passthrough():
    assert validate_positive(5) == 5


def test_validate_positive_raises_negative_value_error():
    with pytest.raises(NegativeValueError):
        validate_positive(-1)


def test_negative_value_error_is_a_validation_error():
    assert issubclass(NegativeValueError, ValidationError)
    assert issubclass(ValidationError, Exception)


def test_safe_parse_int_valid():
    assert safe_parse_int("42") == 42


def test_safe_parse_int_invalid():
    assert safe_parse_int("nope") is None


def test_divide_with_cleanup_success():
    reset_attempts()
    assert divide_with_cleanup(10, 2) == 5.0
    assert get_attempts() == 1


def test_divide_with_cleanup_counts_failed_attempts_too():
    reset_attempts()
    with pytest.raises(ZeroDivisionError):
        divide_with_cleanup(10, 0)
    assert get_attempts() == 1


# ------------------------------------------------------------------ exercise03: Exception Chaining
import pytest
from exercises.week05.exercise03.solution import (
    ConfigError,
    ConfigParseError,
    load_config_value,
    NetworkError,
    RetryError,
    fetch_with_retry_simulation,
    ScoreError,
    parse_score,
)


def test_load_config_value_valid():
    assert load_config_value("42") == 42


def test_load_config_value_chains_value_error():
    with pytest.raises(ConfigParseError) as exc_info:
        load_config_value("abc")
    assert isinstance(exc_info.value.__cause__, ValueError)
    assert isinstance(exc_info.value, ConfigError)


def test_fetch_with_retry_simulation_success():
    assert fetch_with_retry_simulation(False) == "ok"


def test_fetch_with_retry_simulation_chains_network_error():
    with pytest.raises(RetryError) as exc_info:
        fetch_with_retry_simulation(True)
    assert isinstance(exc_info.value.__cause__, NetworkError)


def test_parse_score_valid():
    assert parse_score("85") == 85


def test_parse_score_chains_value_error():
    with pytest.raises(ScoreError) as exc_info:
        parse_score("abc")
    assert isinstance(exc_info.value.__cause__, ValueError)


def test_parse_score_out_of_range_suppresses_chaining():
    with pytest.raises(ScoreError) as exc_info:
        parse_score("150")
    assert exc_info.value.__cause__ is None


# ------------------------------------------------------------------ exercise04: Regex Basics
from exercises.week05.exercise04.solution import (
    contains_digit,
    find_all_numbers,
    starts_with_word,
    normalize_whitespace,
    extract_emails,
)


def test_contains_digit():
    assert contains_digit("room 42") is True
    assert contains_digit("no numbers here") is False


def test_find_all_numbers():
    assert find_all_numbers("a1 b22 c333") == ["1", "22", "333"]


def test_starts_with_word():
    assert starts_with_word("hello world", "hello") is True
    assert starts_with_word("say hello", "hello") is False


def test_normalize_whitespace():
    assert normalize_whitespace("a   b\t\tc\n\nd") == "a b c d"


def test_extract_emails():
    text = "contact ada@example.com or grace@nav.mil for details"
    assert extract_emails(text) == ["ada@example.com", "grace@nav.mil"]


# ------------------------------------------------------------------ exercise05: Regex Named Groups
import pytest
from exercises.week05.exercise05.solution import parse_log_line, parse_date, parse_key_value


def test_parse_log_line():
    assert parse_log_line("ERROR: disk full") == {"level": "ERROR", "message": "disk full"}


def test_parse_log_line_invalid_raises():
    with pytest.raises(ValueError):
        parse_log_line("not a log line")


def test_parse_date():
    result = parse_date("event happened on 2024-03-15 in the evening")
    assert result == {"year": "2024", "month": "03", "day": "15"}


def test_parse_date_none_found_raises():
    with pytest.raises(ValueError):
        parse_date("no date here")


def test_parse_key_value():
    assert parse_key_value("host=localhost") == {"key": "host", "value": "localhost"}


def test_parse_key_value_invalid_raises():
    with pytest.raises(ValueError):
        parse_key_value("not-key-value")


# ------------------------------------------------------------------ exercise06: Context Managers
import pytest
from exercises.week05.exercise06.solution import (
    Timer,
    SuppressErrors,
    FileLineCounter,
    temporary_value,
    suppress_and_log,
    timing_block,
)


def test_timer_records_elapsed():
    with Timer() as t:
        pass
    assert hasattr(t, "elapsed")
    assert t.elapsed >= 0


def test_suppress_errors_suppresses_matching_type():
    with SuppressErrors(ValueError):
        raise ValueError("boom")


def test_suppress_errors_lets_other_types_propagate():
    with pytest.raises(TypeError):
        with SuppressErrors(ValueError):
            raise TypeError("nope")


def test_file_line_counter(tmp_path):
    path = tmp_path / "data.txt"
    path.write_text("a\nb\nc\n")
    with FileLineCounter(str(path)) as f:
        lines = f.read().splitlines()
    assert lines == ["a", "b", "c"]


class _Config:
    debug = False


def test_temporary_value_restores_after_block():
    cfg = _Config()
    with temporary_value(cfg, "debug", True):
        assert cfg.debug is True
    assert cfg.debug is False


def test_temporary_value_restores_even_on_exception():
    # ValueError, not RuntimeError: NotImplementedError (what an unfinished
    # stub raises) is itself a RuntimeError subclass, so a RuntimeError here
    # would let pytest.raises(RuntimeError) accidentally match an
    # unimplemented temporary_value() instead of only a correct one.
    cfg = _Config()
    with pytest.raises(ValueError):
        with temporary_value(cfg, "debug", True):
            raise ValueError("boom")
    assert cfg.debug is False


def test_suppress_and_log():
    log = []
    with suppress_and_log(log, ValueError):
        raise ValueError("bad input")
    assert log == ["bad input"]


def test_timing_block():
    results = []
    with timing_block(results):
        pass
    assert len(results) == 1
    assert results[0] >= 0
