"""
Tests for stage03/exercise06 -- Functions: Functools Toolbox.
Auto-generated by generate.py from generator/stage03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import functools
from exercises.stage03.exercise06.solution import (
    cached_fibonacci,
    cached_is_prime,
    cached_factorial,
    make_adder,
    make_multiplier_via_partial,
    make_usd_formatter,
)


def test_cached_fibonacci_correctness_and_caching():
    assert cached_fibonacci(10) == 55
    assert hasattr(cached_fibonacci, "cache_info")


def test_cached_is_prime_correctness_and_caching():
    assert cached_is_prime(17) is True
    assert cached_is_prime(18) is False
    assert hasattr(cached_is_prime, "cache_info")


def test_cached_factorial_correctness_and_caching():
    assert cached_factorial(5) == 120
    assert hasattr(cached_factorial, "cache_info")


def test_make_adder():
    add5 = make_adder(5)
    assert add5(3) == 8
    assert isinstance(add5, functools.partial)


def test_make_multiplier_via_partial():
    times3 = make_multiplier_via_partial(3)
    assert times3(4) == 12
    assert isinstance(times3, functools.partial)


def test_make_usd_formatter():
    usd = make_usd_formatter()
    assert usd(9.5) == "$9.50"
    assert isinstance(usd, functools.partial)
