"""
Tests for week06/exercise01 -- OOP I: Bank Account.
Auto-generated by generate.py from generator/week06.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.week06.exercise01.solution import BankAccount


def test_initial_balance():
    acct = BankAccount("Ada", 100)
    assert acct.balance == 100


def test_deposit():
    acct = BankAccount("Ada", 100)
    acct.deposit(50)
    assert acct.balance == 150


def test_withdraw():
    acct = BankAccount("Ada", 100)
    acct.withdraw(30)
    assert acct.balance == 70


def test_withdraw_insufficient_funds_raises():
    acct = BankAccount("Ada", 100)
    with pytest.raises(ValueError):
        acct.withdraw(200)


def test_negative_balance_raises():
    with pytest.raises(ValueError):
        BankAccount("Ada", -5)


def test_is_valid_amount():
    assert BankAccount.is_valid_amount(10) is True
    assert BankAccount.is_valid_amount(-1) is False
    assert BankAccount.is_valid_amount("10") is False
