"""
Tests for stage04/exercise05 -- Data Structures: Dataclasses.
Auto-generated by generate.py from generator/stage04.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage04.exercise05.solution import Point, FrozenPoint, TaggedItem


def test_point_distance_and_eq():
    assert Point(3, 4).distance_from_origin() == 5.0
    assert Point(1, 2) == Point(1, 2)


def test_point_is_not_hashable():
    with pytest.raises(TypeError):
        hash(Point(1, 2))


def test_frozen_point_distance_and_eq():
    assert FrozenPoint(3, 4).distance_from_origin() == 5.0
    assert FrozenPoint(1, 2) == FrozenPoint(1, 2)


def test_frozen_point_is_hashable():
    points = {FrozenPoint(1, 2), FrozenPoint(1, 2), FrozenPoint(3, 4)}
    assert len(points) == 2


def test_tagged_item_add_tag():
    item = TaggedItem("shirt")
    item.add_tag("clothing")
    assert item.tags == ["clothing"]


def test_tagged_item_default_factory_is_independent_per_instance():
    item1 = TaggedItem("shirt")
    item2 = TaggedItem("shoe")
    item1.add_tag("clothing")
    assert item2.tags == []
