"""
Tests for stage06/tier1_basic01 -- OOP I: Bank Account.
Auto-generated by generate.py from generator/stage06.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage06.tier1_basic01.solution import BankAccount


def test_initial_balance_goes_through_the_setter():
    """__init__ must assign self.balance (the property), not self._balance directly."""
    acct = BankAccount("Ada", 100)
    assert acct.balance == 100


def test_deposit():
    """deposit() adds to balance through the property setter."""
    acct = BankAccount("Ada", 100)
    acct.deposit(50)
    assert acct.balance == 150


def test_withdraw():
    """withdraw() subtracts from balance through the property setter."""
    acct = BankAccount("Ada", 100)
    acct.withdraw(30)
    assert acct.balance == 70


def test_withdraw_insufficient_funds_raises():
    """withdraw() must raise ValueError if amount exceeds the current balance."""
    acct = BankAccount("Ada", 100)
    with pytest.raises(ValueError):
        acct.withdraw(200)


def test_negative_balance_raises_at_construction():
    """__init__ must route through the balance setter, so a negative starting balance raises ValueError too."""
    with pytest.raises(ValueError):
        BankAccount("Ada", -5)


def test_is_valid_amount_is_a_staticmethod():
    """is_valid_amount is callable on the class itself (no instance) and rejects non-numeric/negative values."""
    assert BankAccount.is_valid_amount(10) is True
    assert BankAccount.is_valid_amount(-1) is False
    assert BankAccount.is_valid_amount("10") is False
