"""
Tests for week01/exercise06 -- Python Fundamentals: Mutability and Identity.
Auto-generated by generate.py from generator/week01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week01.exercise06.solution import (
    append_and_return,
    concat_strings,
    same_object,
    equal_but_not_identical,
    default_if_none,
)


def test_append_and_return_mutates_in_place_and_is_same_object():
    original = [1, 2]
    result = append_and_return(original, 3)
    assert result == [1, 2, 3]
    assert result is original


def test_concat_strings_returns_new_object():
    a = "foo"
    b = "bar"
    result = concat_strings(a, b)
    assert result == "foobar"
    assert result is not a
    assert result is not b


def test_same_object_true_for_shared_reference():
    x = [1, 2, 3]
    y = x
    assert same_object(x, y) is True


def test_same_object_false_for_equal_but_distinct_objects():
    x = [1, 2, 3]
    y = [1, 2, 3]
    assert x == y
    assert same_object(x, y) is False


def test_equal_but_not_identical():
    l1, l2 = equal_but_not_identical()
    assert l1 == l2
    assert l1 is not l2


def test_default_if_none_uses_default_for_none():
    assert default_if_none(None, "fallback") == "fallback"


def test_default_if_none_keeps_real_value():
    assert default_if_none(0, "fallback") == 0
