"""
Tests for stage08/advanced02 -- The Python Data Model: Context Managers as a Protocol.
Auto-generated by generate.py from generator/stage08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage08.advanced02.solution import ResourceGuard, Transaction, SuppressAll


def test_resource_guard_active_during_block():
    """__enter__ sets active True and returns self; __exit__ sets it back to False."""
    guard = ResourceGuard()
    with guard:
        assert guard.active is True
    assert guard.active is False


def test_transaction_commits_on_success():
    """__exit__ sets committed=True when the block finishes with no exception (exc_type is None)."""
    with Transaction() as tx:
        pass
    assert tx.committed is True
    assert tx.rolled_back is False


def test_transaction_rolls_back_on_exception():
    """__exit__ sets rolled_back=True when the block raises, and must return False so the exception still propagates."""
    with pytest.raises(RuntimeError):
        with Transaction() as tx:
            raise RuntimeError("boom")
    assert tx.rolled_back is True
    assert tx.committed is False


def test_suppress_all_swallows_any_exception():
    """__exit__ must always return True, suppressing any exception type raised inside the block."""
    with SuppressAll():
        raise ValueError("this never propagates")
    with SuppressAll():
        raise KeyError("neither does this")


def test_no_special_base_class_required_for_with_statement():
    """None of the three classes inherit from any special base -- `with` works purely via the __enter__/__exit__ protocol."""
    assert ResourceGuard.__bases__ == (object,)
    assert Transaction.__bases__ == (object,)
    assert SuppressAll.__bases__ == (object,)
