"""
Tests for stage09/tier1_basic02 -- OS, JSON, Datetime, XML: Library Catalog: Dates and XML.
Auto-generated by generate.py from generator/stage09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import datetime
from exercises.stage09.tier1_basic02.solution import (
    catalog_timestamp,
    parse_catalog_titles,
    parse_catalog_titles_from_string,
    count_catalog_books,
)

LIBRARY_XML = (
    "<library>"
    '<book id="1"><title>Dune</title></book>'
    '<book id="2"><title>Foundation</title></book>'
    "</library>"
)


def test_catalog_timestamp_is_parseable_isoformat():
    """catalog_timestamp must be a real datetime.now().isoformat() string."""
    text = catalog_timestamp()
    parsed = datetime.datetime.fromisoformat(text)
    assert isinstance(parsed, datetime.datetime)


def test_parse_catalog_titles(tmp_path):
    """parse_catalog_titles uses ET.parse + .//title to collect every title's text."""
    path = tmp_path / "library.xml"
    path.write_text(LIBRARY_XML)
    assert parse_catalog_titles(str(path)) == ["Dune", "Foundation"]


def test_parse_catalog_titles_from_string():
    """parse_catalog_titles_from_string uses ET.fromstring instead of ET.parse."""
    assert parse_catalog_titles_from_string(LIBRARY_XML) == ["Dune", "Foundation"]


def test_count_catalog_books(tmp_path):
    """count_catalog_books == len(root.findall(".//book"))."""
    path = tmp_path / "library.xml"
    path.write_text(LIBRARY_XML)
    assert count_catalog_books(str(path)) == 2
