"""
Aggregated tests for week09 -- OS, JSON, Datetime, XML.
Auto-generated by generate.py from generator/week09.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: os.path and pathlib Basics
from exercises.week09.exercise01.solution import (
    list_files,
    join_path,
    file_exists,
    list_files_pathlib,
    read_text_pathlib,
)


def test_list_files(tmp_path):
    (tmp_path / "b.txt").write_text("b")
    (tmp_path / "a.txt").write_text("a")
    assert list_files(str(tmp_path)) == ["a.txt", "b.txt"]


def test_join_path():
    assert join_path("dir", "file.txt") in ("dir/file.txt", "dir\\file.txt")


def test_file_exists(tmp_path):
    (tmp_path / "a.txt").write_text("a")
    assert file_exists(str(tmp_path / "a.txt")) is True
    assert file_exists(str(tmp_path / "missing.txt")) is False


def test_list_files_pathlib(tmp_path):
    (tmp_path / "b.txt").write_text("b")
    (tmp_path / "a.txt").write_text("a")
    assert list_files_pathlib(str(tmp_path)) == ["a.txt", "b.txt"]


def test_read_text_pathlib(tmp_path):
    path = tmp_path / "a.txt"
    path.write_text("hello")
    assert read_text_pathlib(str(path)) == "hello"


# ------------------------------------------------------------------ exercise02: Recursive Traversal
from exercises.week09.exercise02.solution import (
    find_all_py_files,
    count_files_by_extension,
    total_size_of_directory,
    find_txt_files_pathlib,
)


def _make_tree(tmp_path):
    (tmp_path / "a.py").write_text("x = 1")
    (tmp_path / "b.txt").write_text("hello")
    sub = tmp_path / "sub"
    sub.mkdir()
    (sub / "c.py").write_text("y = 2")
    (sub / "d.txt").write_text("world")
    return tmp_path


def test_find_all_py_files(tmp_path):
    _make_tree(tmp_path)
    result = find_all_py_files(str(tmp_path))
    assert len(result) == 2
    assert all(p.endswith(".py") for p in result)


def test_count_files_by_extension(tmp_path):
    _make_tree(tmp_path)
    result = count_files_by_extension(str(tmp_path))
    assert result == {".py": 2, ".txt": 2}


def test_total_size_of_directory(tmp_path):
    _make_tree(tmp_path)
    assert total_size_of_directory(str(tmp_path)) == len("x = 1") + len("hello") + len("y = 2") + len("world")


def test_find_txt_files_pathlib(tmp_path):
    _make_tree(tmp_path)
    assert find_txt_files_pathlib(str(tmp_path)) == ["b.txt", "d.txt"]


# ------------------------------------------------------------------ exercise03: JSON Basics
from exercises.week09.exercise03.solution import (
    save_json,
    load_json,
    to_json_string,
    from_json_string,
)


def test_save_and_load_json_roundtrip(tmp_path):
    path = str(tmp_path / "data.json")
    save_json(path, {"name": "Ada", "age": 30})
    assert load_json(path) == {"name": "Ada", "age": 30}


def test_to_and_from_json_string_roundtrip():
    text = to_json_string({"x": 1, "y": [1, 2, 3]})
    assert from_json_string(text) == {"x": 1, "y": [1, 2, 3]}


# ------------------------------------------------------------------ exercise04: Custom JSON Encoding
import json
import datetime
from exercises.week09.exercise04.solution import (
    Point,
    serialize_with_points,
    serialize_with_datetimes,
    serialize_with_sets,
)


def test_serialize_with_points():
    result = serialize_with_points({"origin": Point(0, 0)})
    assert json.loads(result) == {"origin": {"x": 0, "y": 0}}


def test_serialize_with_datetimes():
    dt = datetime.datetime(2024, 1, 1, 12, 0, 0)
    result = serialize_with_datetimes({"created": dt})
    assert json.loads(result) == {"created": "2024-01-01T12:00:00"}


def test_serialize_with_sets():
    result = serialize_with_sets({"tags": {"b", "a", "c"}})
    assert json.loads(result) == {"tags": ["a", "b", "c"]}


# ------------------------------------------------------------------ exercise05: Datetime Basics
import datetime
from exercises.week09.exercise05.solution import (
    current_timestamp_iso,
    format_date,
    parse_iso,
    days_between,
)


def test_current_timestamp_iso_is_parseable():
    text = current_timestamp_iso()
    parsed = datetime.datetime.fromisoformat(text)
    assert isinstance(parsed, datetime.datetime)


def test_format_date():
    dt = datetime.datetime(2024, 3, 15)
    assert format_date(dt) == "2024-03-15"


def test_parse_iso():
    result = parse_iso("2024-03-15T12:00:00")
    assert result == datetime.datetime(2024, 3, 15, 12, 0, 0)


def test_days_between():
    d1 = datetime.date(2024, 1, 1)
    d2 = datetime.date(2024, 1, 11)
    assert days_between(d1, d2) == 10


# ------------------------------------------------------------------ exercise06: Timezone-Aware vs. Naive Datetimes
import datetime
from exercises.week09.exercise06.solution import (
    naive_now,
    aware_now_utc,
    is_timezone_aware,
    to_utc_isoformat,
    make_aware,
)


def test_naive_now_is_not_aware():
    assert is_timezone_aware(naive_now()) is False


def test_aware_now_utc_is_aware():
    assert is_timezone_aware(aware_now_utc()) is True


def test_make_aware():
    naive = datetime.datetime(2024, 1, 1, 12, 0, 0)
    aware = make_aware(naive, datetime.timezone.utc)
    assert is_timezone_aware(aware) is True
    assert aware.year == 2024 and aware.hour == 12


def test_to_utc_isoformat():
    aware = datetime.datetime(2024, 1, 1, 12, 0, 0, tzinfo=datetime.timezone.utc)
    assert to_utc_isoformat(aware) == "2024-01-01T12:00:00+00:00"


def test_naive_and_aware_cannot_be_compared():
    import pytest
    with pytest.raises(TypeError):
        naive_now() < aware_now_utc()


# ------------------------------------------------------------------ exercise07: XML with ElementTree
import xml.etree.ElementTree as ET
from exercises.week09.exercise07.solution import (
    parse_xml_titles,
    parse_xml_string_titles,
    count_elements,
    get_attribute_values,
    build_simple_xml,
)

LIBRARY_XML = (
    '<library>'
    '<book id="1"><title>Dune</title></book>'
    '<book id="2"><title>Foundation</title></book>'
    "</library>"
)


def test_parse_xml_titles(tmp_path):
    path = tmp_path / "library.xml"
    path.write_text(LIBRARY_XML)
    assert parse_xml_titles(str(path)) == ["Dune", "Foundation"]


def test_parse_xml_string_titles():
    assert parse_xml_string_titles(LIBRARY_XML) == ["Dune", "Foundation"]


def test_count_elements(tmp_path):
    path = tmp_path / "library.xml"
    path.write_text(LIBRARY_XML)
    assert count_elements(str(path), "book") == 2


def test_get_attribute_values(tmp_path):
    path = tmp_path / "library.xml"
    path.write_text(LIBRARY_XML)
    assert get_attribute_values(str(path), "book", "id") == ["1", "2"]


def test_build_simple_xml():
    xml_string = build_simple_xml(["a", "b"])
    root = ET.fromstring(xml_string)
    items = root.findall("item")
    assert [el.text for el in items] == ["a", "b"]
