"""
Tests for stage01/exercise01 -- Python Fundamentals: Profile Basics.
Auto-generated by generate.py from generator/stage01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage01.exercise01.solution import (
    build_profile,
    value_kind,
    display_profile,
)


def test_build_profile():
    profile = build_profile("Ada", 30, 1.7, False)
    assert profile == {"name": "Ada", "age": 30, "height_m": 1.7, "is_student": False}


def test_value_kind_int():
    assert value_kind(5) == "int"


def test_value_kind_str():
    assert value_kind("hi") == "str"


def test_value_kind_float():
    assert value_kind(3.14) == "float"


def test_display_profile(capsys):
    display_profile({"name": "Ada", "age": 30, "height_m": 1.7, "is_student": False})
    out = capsys.readouterr().out
    assert out == "Ada is 30 years old, 1.7m tall, student=False\n"
