"""
Tests for stage11/tier1_basic02 -- OpenCV: Color Conversion, Resizing, and Drawing.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import numpy as np
from exercises.stage11.tier1_basic02.solution import (
    to_grayscale,
    to_rgb,
    resize_image,
    resize_by_scale,
    draw_rectangle,
    draw_bounding_boxes,
)


def _bgr_image():
    image = np.zeros((10, 10, 3), dtype=np.uint8)
    image[:, :] = (255, 0, 0)
    return image


def test_to_grayscale_drops_channel_dim():
    """to_grayscale must use cv2.COLOR_BGR2GRAY, producing a 2D array."""
    gray = to_grayscale(_bgr_image())
    assert gray.shape == (10, 10)


def test_to_rgb_swaps_channel_order():
    """to_rgb must use cv2.COLOR_BGR2RGB -- BGR (255,0,0) becomes RGB (0,0,255)."""
    rgb = to_rgb(_bgr_image())
    assert tuple(rgb[0, 0]) == (0, 0, 255)


def test_resize_image_uses_width_height_order():
    """resize_image passes (width, height) to cv2.resize -- the opposite of .shape's (height, width)."""
    resized = resize_image(_bgr_image(), 20, 5)
    assert resized.shape[:2] == (5, 20)


def test_resize_by_scale():
    """resize_by_scale == cv2.resize(image, None, fx=scale, fy=scale)."""
    resized = resize_by_scale(_bgr_image(), 2.0)
    assert resized.shape[:2] == (20, 20)


def test_draw_rectangle_does_not_mutate_original():
    """draw_rectangle must draw on image.copy(), leaving the original untouched."""
    image = np.zeros((20, 20, 3), dtype=np.uint8)
    result = draw_rectangle(image, (2, 2), (10, 10), (255, 255, 255))
    assert np.array_equal(image, np.zeros((20, 20, 3), dtype=np.uint8))
    assert result[2, 2].tolist() == [255, 255, 255]


def test_draw_bounding_boxes_draws_all_and_does_not_mutate():
    """draw_bounding_boxes draws every box from a copy, leaving the original image untouched."""
    image = np.zeros((30, 30, 3), dtype=np.uint8)
    boxes = [(1, 1, 5, 5), (10, 10, 15, 15)]
    result = draw_bounding_boxes(image, boxes, (255, 0, 0))
    assert result[1, 1].tolist() == [255, 0, 0]
    assert result[10, 10].tolist() == [255, 0, 0]
    assert image.sum() == 0
