"""
Tests for stage05/tier3_advanced01 -- Files, Exceptions, Regex: Class-Based Context Managers.
Auto-generated by generate.py from generator/stage05.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage05.tier3_advanced01.solution import Timer, SuppressErrors, FileLineCounter


def test_timer_records_elapsed():
    """Timer.__enter__ returns self and records _start; __exit__ sets .elapsed."""
    with Timer() as t:
        pass
    assert hasattr(t, "elapsed")
    assert t.elapsed >= 0


def test_suppress_errors_suppresses_matching_type():
    """SuppressErrors.__exit__ returns True for a matching exception type, so it must not propagate."""
    with SuppressErrors(ValueError):
        raise ValueError("boom")


def test_suppress_errors_lets_other_types_propagate():
    """SuppressErrors.__exit__ returns False for a non-matching type, so it must propagate."""
    with pytest.raises(TypeError):
        with SuppressErrors(ValueError):
            raise TypeError("nope")


def test_file_line_counter(tmp_path):
    """FileLineCounter.__enter__ opens and returns the file object; __exit__ closes it."""
    path = tmp_path / "data.txt"
    path.write_text("a\nb\nc\n")
    with FileLineCounter(str(path)) as f:
        lines = f.read().splitlines()
    assert lines == ["a", "b", "c"]
