"""
Tests for stage04/exercise06 -- Data Structures: Records and Hashability.
Auto-generated by generate.py from generator/stage04.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage04.exercise06.solution import (
    Coordinate,
    make_coordinate,
    SimpleFraction,
    dedupe_preserving_order,
)


def test_make_coordinate():
    c = make_coordinate(1, 2)
    assert c == Coordinate(1, 2)
    assert c.x == 1 and c.y == 2


def test_simple_fraction_reduces():
    assert SimpleFraction(2, 4) == SimpleFraction(1, 2)


def test_simple_fraction_normalizes_negative_denominator():
    assert SimpleFraction(1, -2) == SimpleFraction(-1, 2)


def test_simple_fraction_zero_denominator_raises():
    with pytest.raises(ZeroDivisionError):
        SimpleFraction(1, 0)


def test_simple_fraction_is_hashable():
    fractions = {SimpleFraction(1, 2), SimpleFraction(2, 4), SimpleFraction(1, 3)}
    assert len(fractions) == 2


def test_dedupe_preserving_order_with_hashable_records():
    items = [
        SimpleFraction(1, 2),
        SimpleFraction(2, 4),
        Coordinate(1, 1),
        SimpleFraction(1, 3),
        Coordinate(1, 1),
    ]
    result = dedupe_preserving_order(items)
    assert result == [SimpleFraction(1, 2), Coordinate(1, 1), SimpleFraction(1, 3)]


def test_dedupe_preserving_order_with_plain_values():
    assert dedupe_preserving_order([1, 2, 1, 3, 2]) == [1, 2, 3]
