"""
Tests for stage11/tier2_mid01 -- OpenCV: Hand Posture & Face Gesture Recognition: Skin-Tone Thresholding for Hand Segmentation.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import numpy as np
from exercises.stage11.tier2_mid01.solution import (
    to_hsv,
    segment_skin,
    refine_mask,
    SKIN_HSV_LOWER,
    SKIN_HSV_UPPER,
)


def _skin_toned_frame():
    frame = np.zeros((100, 100, 3), dtype=np.uint8)
    frame[20:80, 20:80] = (120, 150, 200)  # a BGR skin-tone swatch
    return frame


def test_to_hsv_converts_color_space():
    """to_hsv must use cv2.COLOR_BGR2HSV, changing pixel values from the BGR input."""
    frame = _skin_toned_frame()
    hsv = to_hsv(frame)
    assert hsv.shape == frame.shape
    assert not np.array_equal(hsv, frame)


def test_segment_skin_isolates_the_skin_toned_region():
    """segment_skin must mark the skin-toned swatch 255 and the black background 0."""
    frame = _skin_toned_frame()
    mask = segment_skin(frame, SKIN_HSV_LOWER, SKIN_HSV_UPPER)
    assert mask[50, 50] == 255
    assert mask[5, 5] == 0
    assert np.count_nonzero(mask) == 60 * 60


def test_refine_mask_stays_binary():
    """refine_mask must produce a purely 0/255 mask via an explicit threshold pass."""
    frame = _skin_toned_frame()
    mask = segment_skin(frame, SKIN_HSV_LOWER, SKIN_HSV_UPPER)
    refined = refine_mask(mask)
    assert set(np.unique(refined)).issubset({0, 255})
    assert np.array_equal(refined, mask)
