"""
Tests for stage03/basic01 -- Functions: Order Total Calculator.
Auto-generated by generate.py from generator/stage03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage03.basic01.solution import compute_total, apply_discount


def test_compute_total_with_surcharges_and_custom_tax_rate():
    """compute_total(*item_prices, tax_rate=..., **surcharges) combines *args, a keyword default override, and **kwargs surcharges."""
    assert compute_total(10, 20, 30, tax_rate=0.1, shipping=5, handling=2) == 73.0


def test_compute_total_default_tax_rate_no_surcharges():
    """compute_total() with no surcharges still applies the default tax_rate=0.08."""
    assert compute_total(50) == 54.0


def test_apply_discount_default_percentage():
    """apply_discount(price) uses the default pct=0.10."""
    assert apply_discount(100) == 90.0


def test_apply_discount_custom_percentage():
    """apply_discount(price, pct=...) overrides the default keyword argument."""
    assert apply_discount(100, 0.25) == 75.0
