"""
Tests for stage09/advanced02 -- OS, JSON, Datetime, XML: Recursing with os.walk: Size and Depth.
Auto-generated by generate.py from generator/stage09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage09.advanced02.solution import total_size_of_directory, max_directory_depth


def _make_tree(tmp_path):
    (tmp_path / "a.py").write_text("x = 1")
    (tmp_path / "b.txt").write_text("hello")
    sub = tmp_path / "sub"
    sub.mkdir()
    (sub / "c.py").write_text("y = 2")
    (sub / "d.txt").write_text("world")
    return tmp_path


def test_total_size_of_directory(tmp_path):
    """total_size_of_directory sums os.path.getsize() across every file found by os.walk."""
    _make_tree(tmp_path)
    assert total_size_of_directory(str(tmp_path)) == len("x = 1") + len("hello") + len("y = 2") + len("world")


def test_max_directory_depth_at_root_level(tmp_path):
    """A directory with only top-level files has max depth 0."""
    (tmp_path / "a.txt").write_text("a")
    assert max_directory_depth(str(tmp_path)) == 0


def test_max_directory_depth_with_nested_subdirectories(tmp_path):
    """max_directory_depth must track the deepest subdirectory reached during the os.walk."""
    sub = tmp_path / "sub"
    sub.mkdir()
    subsub = sub / "subsub"
    subsub.mkdir()
    (subsub / "deep.txt").write_text("deep")
    assert max_directory_depth(str(tmp_path)) == 2
