"""
Tests for stage12/tier2_mid01 -- Requests + Threading: Raising on HTTP Errors.
Auto-generated by generate.py from generator/stage12.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from unittest.mock import Mock, patch
import pytest
import requests
from exercises.stage12.tier2_mid01.solution import fetch_with_raise, url_is_healthy


def _fake_response(json_data=None, raise_error=False):
    response = Mock()
    response.json.return_value = json_data or {}
    if raise_error:
        response.raise_for_status.side_effect = requests.HTTPError("boom")
    else:
        response.raise_for_status.return_value = None
    return response


def test_fetch_with_raise_success():
    """fetch_with_raise returns r.json() when raise_for_status() doesn't raise."""
    with patch("requests.get", return_value=_fake_response({"ok": True})):
        assert fetch_with_raise("https://example.test/api") == {"ok": True}


def test_fetch_with_raise_propagates_http_error():
    """fetch_with_raise must let raise_for_status()'s HTTPError propagate, not swallow it."""
    with patch("requests.get", return_value=_fake_response(raise_error=True)):
        with pytest.raises(requests.HTTPError):
            fetch_with_raise("https://example.test/api")


def test_url_is_healthy_true_when_no_error():
    """url_is_healthy must catch RequestException and turn it into a bool, not propagate it."""
    with patch("requests.get", return_value=_fake_response()):
        assert url_is_healthy("https://example.test/api") is True


def test_url_is_healthy_false_on_http_error():
    """url_is_healthy is False when raise_for_status() raises."""
    with patch("requests.get", return_value=_fake_response(raise_error=True)):
        assert url_is_healthy("https://example.test/api") is False
