"""
Tests for stage12/tier1_basic02 -- Requests + Threading: Threading Basics.
Auto-generated by generate.py from generator/stage12.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import threading
import time
from exercises.stage12.tier1_basic02.solution import run_in_background, wait_for_all, run_and_wait


def test_run_in_background_runs_the_function():
    """run_in_background must start the thread and return it."""
    result = []
    t = run_in_background(lambda x: result.append(x), 42)
    t.join()
    assert result == [42]


def test_wait_for_all_blocks_until_every_thread_finishes():
    """wait_for_all must .join() every thread, blocking until each is done."""
    results = []

    def slow_append(n):
        time.sleep(0.01)
        results.append(n)

    threads = [threading.Thread(target=slow_append, args=(i,)) for i in range(5)]
    for t in threads:
        t.start()
    wait_for_all(threads)
    assert sorted(results) == [0, 1, 2, 3, 4]


def test_run_and_wait_runs_concurrently_and_completes():
    """run_and_wait must start every thread BEFORE joining any of them."""
    results = []
    funcs = [lambda i=i: results.append(i) for i in range(5)]
    run_and_wait(funcs)
    assert sorted(results) == [0, 1, 2, 3, 4]
