"""
Tests for stage01/basic02 -- Python Fundamentals: Digital Clock Decoder.
Auto-generated by generate.py from generator/stage01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import exercises.stage01.basic02.solution as solution


def test_total_seconds_cast():
    assert solution.total_seconds == 9384
    assert isinstance(solution.total_seconds, int)


def test_decomposition():
    assert solution.hours == 2
    assert solution.minutes == 36
    assert solution.seconds == 24


def test_decomposition_reconstructs_total():
    assert solution.hours * 3600 + solution.minutes * 60 + solution.seconds == 9384


def test_is_daylight_saving_avoids_bool_string_trap():
    assert solution.is_daylight_saving is False
