"""
Tests for stage09/exercise06 -- OS, JSON, Datetime, XML: Timezone-Aware vs. Naive Datetimes.
Auto-generated by generate.py from generator/stage09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import datetime
from exercises.stage09.exercise06.solution import (
    naive_now,
    aware_now_utc,
    is_timezone_aware,
    to_utc_isoformat,
    make_aware,
)


def test_naive_now_is_not_aware():
    assert is_timezone_aware(naive_now()) is False


def test_aware_now_utc_is_aware():
    assert is_timezone_aware(aware_now_utc()) is True


def test_make_aware():
    naive = datetime.datetime(2024, 1, 1, 12, 0, 0)
    aware = make_aware(naive, datetime.timezone.utc)
    assert is_timezone_aware(aware) is True
    assert aware.year == 2024 and aware.hour == 12


def test_to_utc_isoformat():
    aware = datetime.datetime(2024, 1, 1, 12, 0, 0, tzinfo=datetime.timezone.utc)
    assert to_utc_isoformat(aware) == "2024-01-01T12:00:00+00:00"


def test_naive_and_aware_cannot_be_compared():
    import pytest
    with pytest.raises(TypeError):
        naive_now() < aware_now_utc()
