"""
Tests for stage03/tier2_mid01 -- Functions: Rate-Limited Logger Factory + Clamp.
Auto-generated by generate.py from generator/stage03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage03.tier2_mid01.solution import make_logger, clamp, function_signature_info


def test_make_logger_accumulates_and_caps_entries():
    """The log(message) closure appends prefix-prefixed entries and drops the oldest once past max_entries."""
    logger = make_logger(prefix="APP", max_entries=2)
    assert logger("a") == ["APP: a"]
    assert logger("b") == ["APP: a", "APP: b"]
    assert logger("c") == ["APP: b", "APP: c"]


def test_make_logger_prefix_and_max_entries_are_keyword_only():
    """prefix/max_entries must be keyword-only -- calling make_logger positionally must raise TypeError."""
    with pytest.raises(TypeError):
        make_logger("APP", 2)


def test_clamp_bounds_and_passthrough():
    """clamp(value, lo, hi) returns lo/hi/value depending on which side value falls, if any."""
    assert clamp(15, 0, 10) == 10
    assert clamp(-5, 0, 10) == 0
    assert clamp(5, 0, 10) == 5


def test_clamp_arguments_are_positional_only():
    """value/lo/hi must be positional-only -- calling clamp with keywords must raise TypeError."""
    with pytest.raises(TypeError):
        clamp(value=5, lo=0, hi=10)


def test_function_signature_info():
    """function_signature_info(fn) introspects fn.__name__ and fn.__doc__."""
    def sample():
        """A sample docstring."""

    assert function_signature_info(sample) == {"name": "sample", "doc": "A sample docstring."}
