"""
Tests for stage08/exercise03 -- The Python Data Model: Inventory: Mapping-ish Container.
Auto-generated by generate.py from generator/stage08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage08.exercise03.solution import Inventory


def test_empty_inventory_is_falsy():
    inv = Inventory()
    assert bool(inv) is False
    assert len(inv) == 0


def test_add_item_and_str():
    inv = Inventory()
    inv.add_item("bolt", 10)
    inv.add_item("nut", 20)
    assert str(inv) == "Inventory(2 item types)"
    assert bool(inv) is True


def test_add_item_accumulates():
    inv = Inventory()
    inv.add_item("bolt", 10)
    inv.add_item("bolt", 5)
    assert inv.items["bolt"] == 15


def test_contains():
    inv = Inventory()
    inv.add_item("bolt", 10)
    assert "bolt" in inv
    assert "screw" not in inv


def test_iter_yields_names():
    inv = Inventory()
    inv.add_item("bolt", 10)
    inv.add_item("nut", 20)
    assert set(inv) == {"bolt", "nut"}
