"""
Tests for stage11/exercise04 -- OpenCV: Thresholding and Blurring.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import numpy as np
from exercises.stage11.exercise04.solution import (
    apply_threshold,
    apply_otsu_threshold,
    apply_adaptive_threshold,
    apply_gaussian_blur,
    apply_strong_blur,
)


def _half_bright_gray():
    image = np.zeros((20, 20), dtype=np.uint8)
    image[:, 10:] = 200
    return image


def test_apply_threshold():
    result = apply_threshold(_half_bright_gray(), 100)
    assert result[0, 0] == 0
    assert result[0, 15] == 255


def test_apply_otsu_threshold_separates_regions():
    result = apply_otsu_threshold(_half_bright_gray())
    assert result[0, 0] != result[0, 15]


def test_apply_adaptive_threshold_returns_binary_image():
    result = apply_adaptive_threshold(_half_bright_gray())
    assert result.shape == (20, 20)
    assert set(np.unique(result)).issubset({0, 255})


def test_apply_gaussian_blur_preserves_shape():
    image = np.random.randint(0, 255, (20, 20, 3), dtype=np.uint8)
    blurred = apply_gaussian_blur(image, 5)
    assert blurred.shape == image.shape


def test_apply_strong_blur_smooths_more_than_light_blur():
    image = np.zeros((30, 30), dtype=np.uint8)
    image[15, 15] = 255
    light = apply_gaussian_blur(image, 3)
    strong = apply_strong_blur(image)
    assert strong[15, 15] < light[15, 15]
