"""
Tests for stage01/mid01 -- Python Fundamentals: Precision Price Comparator.
Auto-generated by generate.py from generator/stage01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest

import exercises.stage01.mid01.solution as solution


def test_casts_to_correct_types():
    assert isinstance(solution.price_a, float)
    assert isinstance(solution.price_b, float)
    assert isinstance(solution.quantity, int)


def test_walrus_computed_savings_is_exposed_as_module_variable():
    assert solution.savings == pytest.approx(3.98)


def test_savings_message_contains_the_formatted_value():
    assert "3.98" in solution.savings_message


def test_both_under_20_chained_comparison():
    assert solution.both_under_20 is True


def test_total_cost_via_augmented_assignment():
    assert solution.total_cost == pytest.approx(155.94)


def test_weighted_score_respects_operator_precedence():
    assert solution.weighted_score == pytest.approx(1200.8003)
