"""
Tests for week09/exercise04 -- OS, JSON, Datetime, XML: Custom JSON Encoding.
Auto-generated by generate.py from generator/week09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import json
import datetime
from exercises.week09.exercise04.solution import (
    Point,
    serialize_with_points,
    serialize_with_datetimes,
    serialize_with_sets,
)


def test_serialize_with_points():
    result = serialize_with_points({"origin": Point(0, 0)})
    assert json.loads(result) == {"origin": {"x": 0, "y": 0}}


def test_serialize_with_datetimes():
    dt = datetime.datetime(2024, 1, 1, 12, 0, 0)
    result = serialize_with_datetimes({"created": dt})
    assert json.loads(result) == {"created": "2024-01-01T12:00:00"}


def test_serialize_with_sets():
    result = serialize_with_sets({"tags": {"b", "a", "c"}})
    assert json.loads(result) == {"tags": ["a", "b", "c"]}
