"""
Tests for week01/exercise05 -- Python Fundamentals: CLI Interaction.
Auto-generated by generate.py from generator/week01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week01.exercise05.solution import (
    ask_name,
    ask_age,
    ask_yes_no,
    greet,
    greeting_flow,
)


def test_ask_name(monkeypatch):
    monkeypatch.setattr("builtins.input", lambda prompt="": "Ada")
    assert ask_name() == "Ada"


def test_ask_age(monkeypatch):
    monkeypatch.setattr("builtins.input", lambda prompt="": "30")
    assert ask_age() == 30


def test_ask_yes_no_true_for_y(monkeypatch):
    monkeypatch.setattr("builtins.input", lambda prompt="": "y")
    assert ask_yes_no("Continue? ") is True


def test_ask_yes_no_true_for_yes_mixed_case(monkeypatch):
    monkeypatch.setattr("builtins.input", lambda prompt="": "YES")
    assert ask_yes_no("Continue? ") is True


def test_ask_yes_no_false_for_no(monkeypatch):
    monkeypatch.setattr("builtins.input", lambda prompt="": "n")
    assert ask_yes_no("Continue? ") is False


def test_greet(capsys):
    greet("Ada")
    assert capsys.readouterr().out == "Hello, Ada!\n"


def test_greeting_flow(monkeypatch, capsys):
    monkeypatch.setattr("builtins.input", lambda prompt="": "Ada")
    result = greeting_flow()
    assert result == "Ada"
    assert capsys.readouterr().out == "Hello, Ada!\n"
