"""
Tests for week09/exercise03 -- OS, JSON, Datetime, XML: JSON Basics.
Auto-generated by generate.py from generator/week09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week09.exercise03.solution import (
    save_json,
    load_json,
    to_json_string,
    from_json_string,
)


def test_save_and_load_json_roundtrip(tmp_path):
    path = str(tmp_path / "data.json")
    save_json(path, {"name": "Ada", "age": 30})
    assert load_json(path) == {"name": "Ada", "age": 30}


def test_to_and_from_json_string_roundtrip():
    text = to_json_string({"x": 1, "y": [1, 2, 3]})
    assert from_json_string(text) == {"x": 1, "y": [1, 2, 3]}
