"""
Tests for stage12/advanced02 -- Requests + Threading: ThreadPoolExecutor.
Auto-generated by generate.py from generator/stage12.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from unittest.mock import Mock, patch
from exercises.stage12.advanced02.solution import (
    fetch_all_concurrently,
    run_tasks_with_pool,
    compute_squares_concurrently,
)


def test_fetch_all_concurrently():
    """fetch_all_concurrently must use ThreadPoolExecutor.map, one call per URL, results in order."""
    fake_response = Mock()
    fake_response.json.return_value = {"ok": True}
    with patch("requests.get", return_value=fake_response) as mock_get:
        result = fetch_all_concurrently(["https://a.test", "https://b.test", "https://c.test"])
    assert result == [{"ok": True}, {"ok": True}, {"ok": True}]
    assert mock_get.call_count == 3


def test_run_tasks_with_pool_preserves_order():
    """run_tasks_with_pool must preserve input order in its results, same contract as map()."""
    funcs = [lambda i=i: i * 10 for i in range(5)]
    assert run_tasks_with_pool(funcs) == [0, 10, 20, 30, 40]


def test_compute_squares_concurrently():
    """compute_squares_concurrently == list(executor.map(lambda x: x ** 2, numbers))."""
    assert compute_squares_concurrently([1, 2, 3, 4]) == [1, 4, 9, 16]
