"""
Tests for stage04/mid01 -- Data Structures: Player Records: Dataclass vs. namedtuple.
Auto-generated by generate.py from generator/stage04.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage04.mid01.solution import (
    Player,
    PlayerRecord,
    convert_to_record,
    players_are_equal,
    records_are_equal,
)


def test_convert_to_record():
    """convert_to_record(player) == PlayerRecord(player.name, player.position)."""
    record = convert_to_record(Player("Ava", "guard"))
    assert record == PlayerRecord("Ava", "guard")


def test_players_are_equal_uses_dataclass_generated_eq_not_identity():
    """@dataclasses.dataclass generates __eq__ from fields -- two distinct objects with equal fields compare equal."""
    a = Player("Ava", "guard")
    b = Player("Ava", "guard")
    assert a is not b
    assert players_are_equal(a, b) is True


def test_players_are_equal_false_for_different_fields():
    """players_are_equal must actually compare fields, not always return True."""
    assert players_are_equal(Player("Ava", "guard"), Player("Ben", "forward")) is False


def test_records_are_equal_uses_namedtuple_field_equality():
    """namedtuple equality is field-based (inherited from tuple), with no @dataclass decorator involved."""
    a = PlayerRecord("Ava", "guard")
    b = PlayerRecord("Ava", "guard")
    assert records_are_equal(a, b) is True
    assert records_are_equal(a, PlayerRecord("Ben", "forward")) is False
