"""
Tests for stage03/exercise04 -- Functions: Scope: global and nonlocal.
Auto-generated by generate.py from generator/stage03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage03.exercise04.solution import (
    increment_counter,
    reset_counter,
    set_counter,
    get_counter,
    make_counter,
    make_accumulator,
    make_toggle,
)


def test_increment_and_reset_counter():
    reset_counter()
    assert get_counter() == 0
    assert increment_counter() == 1
    assert increment_counter() == 2
    reset_counter()
    assert get_counter() == 0


def test_set_counter():
    set_counter(100)
    assert get_counter() == 100
    reset_counter()


def test_make_counter_is_independent_per_closure():
    counter_a = make_counter()
    counter_b = make_counter()
    assert counter_a() == 1
    assert counter_a() == 2
    assert counter_b() == 1


def test_make_accumulator():
    acc = make_accumulator(10)
    assert acc(5) == 15
    assert acc(5) == 20


def test_make_toggle():
    toggle = make_toggle()
    assert toggle() is True
    assert toggle() is False
    assert toggle() is True
