"""
Aggregated tests for week07 -- OOP II.
Auto-generated by generate.py from generator/week07.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: Inheritance Basics
from exercises.week07.exercise01.solution import Animal, Dog, Cat, describe_animal


def test_dog_speak():
    assert Dog("Rex").speak() == "Rex says Woof!"


def test_cat_speak_and_super_init():
    cat = Cat("Whiskers")
    assert cat.speak() == "Whiskers says Meow!"
    assert cat.name == "Whiskers"
    assert cat.indoor is True


def test_describe_animal_polymorphism():
    assert describe_animal(Dog("Rex")) == "Rex says Woof!"
    assert describe_animal(Cat("Whiskers", indoor=False)) == "Whiskers says Meow!"


def test_dog_and_cat_are_animals():
    assert isinstance(Dog("Rex"), Animal)
    assert isinstance(Cat("Whiskers"), Animal)


# ------------------------------------------------------------------ exercise02: super() and Polymorphism
from exercises.week07.exercise02.solution import (
    Vehicle,
    Car,
    ElectricCar,
    total_description,
    is_car,
)


def test_vehicle_describe():
    assert Vehicle("Honda", "Civic").describe() == "Honda Civic"


def test_car_describe_extends_vehicle():
    assert Car("Honda", "Civic", 4).describe() == "Honda Civic (4 doors)"


def test_electric_car_describe_extends_car():
    car = ElectricCar("Tesla", "Model 3", 4, 75)
    assert car.describe() == "Tesla Model 3 (4 doors), 75kWh battery"


def test_total_description_polymorphism():
    vehicles = [Vehicle("A", "B"), Car("C", "D", 2), ElectricCar("E", "F", 4, 50)]
    result = total_description(vehicles)
    assert result == [
        "A B",
        "C D (2 doors)",
        "E F (4 doors), 50kWh battery",
    ]


def test_is_car():
    assert is_car(Car("C", "D", 2)) is True
    assert is_car(ElectricCar("E", "F", 4, 50)) is True
    assert is_car(Vehicle("A", "B")) is False


# ------------------------------------------------------------------ exercise03: Duck Typing and Composition
from exercises.week07.exercise03.solution import (
    Engine,
    Boat,
    Duck,
    Person,
    make_it_quack,
    is_duck_instance,
)


def test_boat_composition_delegates_to_engine():
    boat = Boat(Engine())
    assert boat.start() == "Engine starting..."


def test_make_it_quack_duck():
    assert make_it_quack(Duck()) == "Quack!"


def test_make_it_quack_person_duck_typing():
    assert make_it_quack(Person()) == "I'm quacking like a duck!"


def test_is_duck_instance():
    assert is_duck_instance(Duck()) is True
    assert is_duck_instance(Person()) is False


# ------------------------------------------------------------------ exercise04: Abstract Base Classes
import pytest
from exercises.week07.exercise04.solution import Shape, Circle, Square


def test_shape_cannot_be_instantiated():
    with pytest.raises(TypeError):
        Shape()


def test_circle_area_and_perimeter():
    c = Circle(2)
    assert round(c.area(), 2) == 12.57
    assert round(c.perimeter(), 2) == 12.57
    assert c.name() == "circle"


def test_square_area_and_perimeter():
    s = Square(4)
    assert s.area() == 16
    assert s.perimeter() == 16
    assert s.name() == "square"


def test_circle_and_square_are_shapes():
    assert isinstance(Circle(1), Shape)
    assert isinstance(Square(1), Shape)


# ------------------------------------------------------------------ exercise05: Mixins and Protocols
from exercises.week07.exercise05.solution import (
    LoggingMixin,
    SerializableMixin,
    Widget,
    SupportsArea,
    Coin,
    total_area,
    supports_area,
)


def test_widget_uses_both_mixins():
    w = Widget("gadget")
    assert w.log("created") == "[Widget] created"
    assert w.to_dict() == {"name": "gadget"}


def test_widget_is_instance_of_both_mixins():
    w = Widget("gadget")
    assert isinstance(w, LoggingMixin)
    assert isinstance(w, SerializableMixin)


def test_total_area():
    assert round(total_area([Coin(1), Coin(2)]), 2) == round(3.14159 + 12.56636, 2)


def test_supports_area_structural_typing():
    assert supports_area(Coin(1)) is True
    assert supports_area("not a shape") is False


def test_coin_never_inherits_from_supports_area():
    assert SupportsArea not in Coin.__bases__
