"""
Tests for stage10/basic01 -- Pandas: Reading and Inspecting Sales Data.
Auto-generated by generate.py from generator/stage10.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pandas as pd
from exercises.stage10.basic01.solution import load_csv, preview_rows, summarize


def test_load_csv(tmp_path):
    """load_csv == pd.read_csv(path)."""
    path = tmp_path / "data.csv"
    path.write_text("name,sales\nAda,100\nGrace,200\n")
    df = load_csv(str(path))
    assert list(df.columns) == ["name", "sales"]
    assert len(df) == 2


def test_preview_rows():
    """preview_rows == df.head(n)."""
    df = pd.DataFrame({"x": range(10)})
    assert len(preview_rows(df, 3)) == 3


def test_summarize():
    """summarize == df.describe(), with a "mean" row among others."""
    df = pd.DataFrame({"sales": [10, 20, 30]})
    result = summarize(df)
    assert result.loc["mean", "sales"] == 20.0
