"""
Tests for stage06/tier1_basic02 -- OOP I: Employee Registry.
Auto-generated by generate.py from generator/stage06.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage06.tier1_basic02.solution import Employee


def test_instance_attributes_are_per_employee():
    """name/salary are instance attributes -- distinct per Employee."""
    a = Employee("Ada", 90000)
    b = Employee("Grace", 95000)
    assert a.name == "Ada"
    assert b.name == "Grace"
    assert a.salary != b.salary


def test_class_attribute_shared_across_instances():
    """company_name is a class attribute -- the same object for every instance."""
    a = Employee("Ada", 90000)
    b = Employee("Grace", 95000)
    assert a.company_name == "Acme Corp"
    assert b.company_name == "Acme Corp"
    assert a.company_name is b.company_name


def test_employee_count_increments_via_class_not_instance():
    """__init__ must increment Employee.employee_count (the shared class attribute), not create a shadowing instance attribute."""
    before = Employee.get_employee_count()
    Employee("New Hire", 50000)
    after = Employee.get_employee_count()
    assert after == before + 1


def test_annual_bonus_is_computed_from_salary():
    """annual_bonus == round(salary * 0.1, 2), recomputed fresh on every access."""
    e = Employee("Ada", 90000)
    assert e.annual_bonus == 9000.0
    e.salary = 100000
    assert e.annual_bonus == 10000.0


def test_hire_intern_alternate_constructor():
    """hire_intern is a @classmethod that builds and returns a new instance via cls(...)."""
    intern = Employee.hire_intern("Intern Ivy")
    assert intern.name == "Intern Ivy"
    assert intern.salary == 0
    assert isinstance(intern, Employee)


def test_is_valid_salary_is_a_staticmethod():
    """is_valid_salary is callable on the class itself."""
    assert Employee.is_valid_salary(50000) is True
    assert Employee.is_valid_salary(-1) is False
