"""
Tests for stage11/tier2_mid02 -- OpenCV: Edge Detection with Canny.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import cv2
import numpy as np
from exercises.stage11.tier2_mid02.solution import detect_edges, detect_edges_default, count_edge_pixels


def _square_image():
    image = np.zeros((50, 50), dtype=np.uint8)
    cv2.rectangle(image, (10, 10), (30, 30), 255, -1)
    return image


def test_detect_edges_finds_something():
    """detect_edges must find edge pixels around the square's boundary."""
    edges = detect_edges(_square_image(), 50, 150)
    assert edges.sum() > 0


def test_detect_edges_default_uses_100_200():
    """detect_edges_default == cv2.Canny(gray_image, 100, 200), same output shape as input."""
    edges = detect_edges_default(_square_image())
    assert edges.shape == (50, 50)


def test_count_edge_pixels():
    """count_edge_pixels counts nonzero pixels in the Canny output."""
    assert count_edge_pixels(_square_image(), 50, 150) > 0
