"""
Tests for week01/exercise04 -- Python Fundamentals: Boolean Logic.
Auto-generated by generate.py from generator/week01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week01.exercise04.solution import (
    can_enter_venue,
    access_level,
    is_valid_choice,
    toggle_flag,
)


def test_can_enter_venue_adult_with_ticket():
    assert can_enter_venue(20, True, False) is True


def test_can_enter_venue_minor_rejected():
    assert can_enter_venue(15, True, True) is False


def test_can_enter_venue_unknown_age_rejected():
    assert can_enter_venue(None, True, True) is False


def test_can_enter_venue_vip_without_ticket():
    assert can_enter_venue(25, False, True) is True


def test_access_level_backstage_for_staff():
    assert access_level(False, False, True) == "backstage"


def test_access_level_general_for_ticket_only():
    assert access_level(True, False, False) == "general"


def test_access_level_denied():
    assert access_level(False, False, False) == "denied"


def test_is_valid_choice_true():
    assert is_valid_choice("red", ["red", "blue"]) is True


def test_is_valid_choice_not_in_list():
    assert is_valid_choice("green", ["red", "blue"]) is False


def test_is_valid_choice_empty_string():
    assert is_valid_choice("", ["", "blue"]) is False


def test_is_valid_choice_non_string():
    assert is_valid_choice(5, ["red", "blue"]) is False


def test_toggle_flag():
    assert toggle_flag(True) is False
    assert toggle_flag(False) is True
