"""
Tests for stage11/tier2_mid02 -- OpenCV: Hand Posture & Face Gesture Recognition: Edge Detection on the Hand Silhouette.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import numpy as np
from exercises.stage11.tier2_mid02.solution import (
    detect_hand_edges,
    detect_hand_edges_default,
    count_edge_pixels,
)


def _hand_mask():
    mask = np.zeros((100, 100), dtype=np.uint8)
    mask[20:80, 20:80] = 255
    return mask


def test_detect_hand_edges_finds_the_silhouette_boundary():
    """detect_hand_edges must find edge pixels around the mask's boundary."""
    edges = detect_hand_edges(_hand_mask(), 50, 150)
    assert edges.sum() > 0


def test_detect_hand_edges_default_uses_50_150():
    """detect_hand_edges_default == cv2.Canny(binary_mask, 50, 150), same output shape as input."""
    edges = detect_hand_edges_default(_hand_mask())
    assert edges.shape == (100, 100)


def test_count_edge_pixels():
    """count_edge_pixels counts nonzero pixels in the Canny output."""
    assert count_edge_pixels(_hand_mask(), 50, 150) > 0
