"""
Tests for stage08/tier2_mid01 -- The Python Data Model: Deck: A Collection Protocol.
Auto-generated by generate.py from generator/stage08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage08.tier2_mid01.solution import Deck


def test_init_copies_the_input_list():
    """__init__ must store list(cards) -- a copy, not the same list object."""
    original = ["A", "K"]
    d = Deck(original)
    original.append("Q")
    assert list(d) == ["A", "K"]


def test_len_and_getitem():
    """__len__ and __getitem__ make len(deck) and indexing/slicing work."""
    d = Deck(["A", "K", "Q"])
    assert len(d) == 3
    assert d[0] == "A"
    assert d[1:] == ["K", "Q"]


def test_deck_iter():
    """__iter__ makes list(deck)/for-loops work."""
    d = Deck(["A", "K", "Q"])
    assert list(d) == ["A", "K", "Q"]


def test_deck_contains():
    """__contains__ makes the `in` operator work."""
    d = Deck(["A", "K", "Q"])
    assert "K" in d
    assert "J" not in d


def test_add_concatenates_via_operator_overloading():
    """__add__ must return a NEW Deck concatenating both cards lists -- this is what makes `+` work on Deck instances."""
    d1 = Deck(["A", "K"])
    d2 = Deck(["Q", "J"])
    combined = d1 + d2
    assert list(combined) == ["A", "K", "Q", "J"]
    assert isinstance(combined, Deck)


def test_deck_has_no_special_base_class():
    """Deck supports len()/indexing/iteration/`in`/`+` via dunders alone -- no collection base class needed (protocols vs explicit inheritance)."""
    assert Deck.__bases__ == (object,)
