"""
Tests for week11/exercise01 -- OpenCV: Image I/O and Shape.
Auto-generated by generate.py from generator/week11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import numpy as np
from exercises.week11.exercise01.solution import (
    load_image,
    save_image,
    get_dimensions,
    get_channel_count,
)


def test_save_and_load_roundtrip(tmp_path):
    path = str(tmp_path / "img.png")
    original = np.zeros((20, 30, 3), dtype=np.uint8)
    original[:, :] = (0, 0, 255)
    assert save_image(path, original) is True
    loaded = load_image(path)
    assert loaded is not None
    assert loaded.shape == (20, 30, 3)


def test_load_missing_file_returns_none():
    assert load_image("/nonexistent/path/to/image.png") is None


def test_get_dimensions():
    image = np.zeros((20, 30, 3), dtype=np.uint8)
    assert get_dimensions(image) == (20, 30)


def test_get_channel_count_color():
    image = np.zeros((10, 10, 3), dtype=np.uint8)
    assert get_channel_count(image) == 3


def test_get_channel_count_grayscale():
    image = np.zeros((10, 10), dtype=np.uint8)
    assert get_channel_count(image) == 1
