"""
Tests for stage13/exercise05 -- Local API Endpoints: TestClient, Docs, and uvicorn.run.
Auto-generated by generate.py from generator/stage13.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from unittest.mock import patch
from exercises.stage13.exercise05.solution import (
    app,
    get_health_status,
    get_openapi_schema,
    docs_page_status,
    run_server,
)


def test_get_health_status():
    assert get_health_status(app) == {"status": "ok"}


def test_get_openapi_schema_has_health_path():
    schema = get_openapi_schema(app)
    assert "/health" in schema["paths"]


def test_docs_page_status():
    assert docs_page_status(app) == 200


def test_run_server_calls_uvicorn_run_without_starting_a_server():
    with patch("uvicorn.run") as mock_run:
        run_server(app, host="0.0.0.0", port=9000)
    mock_run.assert_called_once_with(app, host="0.0.0.0", port=9000)
