"""
Tests for stage09/tier3_advanced01 -- OS, JSON, Datetime, XML: Recursing with os.walk: File Discovery.
Auto-generated by generate.py from generator/stage09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage09.tier3_advanced01.solution import find_all_py_files, count_files_by_extension


def _make_tree(tmp_path):
    (tmp_path / "a.py").write_text("x = 1")
    (tmp_path / "b.txt").write_text("hello")
    sub = tmp_path / "sub"
    sub.mkdir()
    (sub / "c.py").write_text("y = 2")
    (sub / "d.txt").write_text("world")
    return tmp_path


def test_find_all_py_files_walks_the_whole_tree(tmp_path):
    """find_all_py_files must use os.walk to find .py files at every depth, not just the top level."""
    _make_tree(tmp_path)
    result = find_all_py_files(str(tmp_path))
    assert len(result) == 2
    assert all(p.endswith(".py") for p in result)


def test_count_files_by_extension(tmp_path):
    """count_files_by_extension builds {extension: count} via os.walk + os.path.splitext."""
    _make_tree(tmp_path)
    result = count_files_by_extension(str(tmp_path))
    assert result == {".py": 2, ".txt": 2}
