"""
Tests for week02/exercise06 -- Control Flow: Ternary Expressions.
Auto-generated by generate.py from generator/week02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week02.exercise06.solution import grade_label, abs_value, clamp_to_range


def test_grade_label():
    assert grade_label(75) == "pass"
    assert grade_label(50) == "fail"


def test_abs_value():
    assert abs_value(5) == 5
    assert abs_value(-5) == 5
    assert abs_value(0) == 0


def test_clamp_to_range():
    assert clamp_to_range(15, 0, 10) == 10
    assert clamp_to_range(-5, 0, 10) == 0
    assert clamp_to_range(5, 0, 10) == 5
