"""
Aggregated tests for week03 -- Functions.
Auto-generated by generate.py from generator/week03.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: Recursion Basics
import pytest
from exercises.week03.exercise01.solution import factorial, fibonacci


def test_factorial():
    assert factorial(0) == 1
    assert factorial(1) == 1
    assert factorial(5) == 120


def test_factorial_negative_raises():
    with pytest.raises(ValueError):
        factorial(-1)


def test_fibonacci():
    assert fibonacci(0) == 0
    assert fibonacci(1) == 1
    assert fibonacci(10) == 55


# ------------------------------------------------------------------ exercise02: Args and Kwargs
from exercises.week03.exercise02.solution import sum_all, build_config, describe_call


def test_sum_all():
    assert sum_all(1, 2, 3) == 6
    assert sum_all() == 0


def test_build_config():
    assert build_config(host="x", port=1) == {"host": "x", "port": 1}


def test_describe_call():
    assert describe_call(1, 2, key="value") == "args=(1, 2), kwargs={'key': 'value'}"


# ------------------------------------------------------------------ exercise03: Lambdas and Higher-Order Functions
from exercises.week03.exercise03.solution import (
    make_multiplier,
    sort_by_length,
    top_scorer,
)


def test_make_multiplier():
    double = make_multiplier(2)
    assert double(5) == 10
    triple = make_multiplier(3)
    assert triple(5) == 15


def test_sort_by_length():
    assert sort_by_length(["ccc", "a", "bb"]) == ["a", "bb", "ccc"]


def test_top_scorer():
    records = [{"name": "a", "score": 10}, {"name": "b", "score": 30}, {"name": "c", "score": 20}]
    assert top_scorer(records) == {"name": "b", "score": 30}


# ------------------------------------------------------------------ exercise04: Scope: global and nonlocal
from exercises.week03.exercise04.solution import (
    increment_counter,
    reset_counter,
    set_counter,
    get_counter,
    make_counter,
    make_accumulator,
    make_toggle,
)


def test_increment_and_reset_counter():
    reset_counter()
    assert get_counter() == 0
    assert increment_counter() == 1
    assert increment_counter() == 2
    reset_counter()
    assert get_counter() == 0


def test_set_counter():
    set_counter(100)
    assert get_counter() == 100
    reset_counter()


def test_make_counter_is_independent_per_closure():
    counter_a = make_counter()
    counter_b = make_counter()
    assert counter_a() == 1
    assert counter_a() == 2
    assert counter_b() == 1


def test_make_accumulator():
    acc = make_accumulator(10)
    assert acc(5) == 15
    assert acc(5) == 20


def test_make_toggle():
    toggle = make_toggle()
    assert toggle() is True
    assert toggle() is False
    assert toggle() is True


# ------------------------------------------------------------------ exercise05: Decorators
from exercises.week03.exercise05.solution import log_calls, count_calls, uppercase_result


def test_log_calls_tracks_call_count():
    @log_calls
    def add(a, b):
        return a + b

    assert add(1, 2) == 3
    assert add(2, 2) == 4
    assert add.calls == 2


def test_log_calls_preserves_metadata():
    @log_calls
    def greet(name):
        """Say hello."""
        return f"hi {name}"

    assert greet.__name__ == "greet"
    assert greet.__doc__ == "Say hello."


def test_count_calls():
    @count_calls
    def noop():
        return None

    noop()
    noop()
    noop()
    assert noop.call_count() == 3


def test_uppercase_result():
    @uppercase_result
    def shout(msg):
        return msg

    assert shout("hello") == "HELLO"


def test_uppercase_result_passthrough_non_str():
    @uppercase_result
    def give_number():
        return 42

    assert give_number() == 42


# ------------------------------------------------------------------ exercise06: Functools Toolbox
import functools
from exercises.week03.exercise06.solution import (
    cached_fibonacci,
    cached_is_prime,
    cached_factorial,
    make_adder,
    make_multiplier_via_partial,
    make_usd_formatter,
)


def test_cached_fibonacci_correctness_and_caching():
    assert cached_fibonacci(10) == 55
    assert hasattr(cached_fibonacci, "cache_info")


def test_cached_is_prime_correctness_and_caching():
    assert cached_is_prime(17) is True
    assert cached_is_prime(18) is False
    assert hasattr(cached_is_prime, "cache_info")


def test_cached_factorial_correctness_and_caching():
    assert cached_factorial(5) == 120
    assert hasattr(cached_factorial, "cache_info")


def test_make_adder():
    add5 = make_adder(5)
    assert add5(3) == 8
    assert isinstance(add5, functools.partial)


def test_make_multiplier_via_partial():
    times3 = make_multiplier_via_partial(3)
    assert times3(4) == 12
    assert isinstance(times3, functools.partial)


def test_make_usd_formatter():
    usd = make_usd_formatter()
    assert usd(9.5) == "$9.50"
    assert isinstance(usd, functools.partial)


# ------------------------------------------------------------------ exercise07: Signature Styles
import pytest
from exercises.week03.exercise07.solution import compute_area, divide, connect, scale_point


def test_compute_area_default_unit():
    assert compute_area(2, 3) == "6m^2"


def test_compute_area_custom_unit_keyword_only():
    assert compute_area(2, 3, unit="cm") == "6cm^2"


def test_compute_area_unit_must_be_keyword():
    with pytest.raises(TypeError):
        compute_area(2, 3, "cm")


def test_divide():
    assert divide(10, 3, precision=3) == 3.333


def test_divide_positional_only_enforced():
    with pytest.raises(TypeError):
        divide(a=7, b=2)


def test_divide_precision_keyword_only_enforced():
    with pytest.raises(TypeError):
        divide(7, 2, 3)


def test_connect_defaults():
    assert connect("localhost", 8080) == {
        "host": "localhost", "port": 8080, "timeout": 30, "retries": 3,
    }


def test_connect_keyword_only_overrides():
    result = connect("localhost", 8080, timeout=5, retries=1)
    assert result == {"host": "localhost", "port": 8080, "timeout": 5, "retries": 1}


def test_connect_positional_only_enforced():
    with pytest.raises(TypeError):
        connect(host="localhost", port=8080)


def test_scale_point_default_factor():
    assert scale_point(2, 3) == (2, 3)


def test_scale_point_with_factor_positional_or_keyword():
    assert scale_point(2, 3, 2) == (4, 6)
    assert scale_point(2, 3, factor=2) == (4, 6)


def test_scale_point_positional_only_enforced():
    with pytest.raises(TypeError):
        scale_point(x=2, y=3)


# ------------------------------------------------------------------ exercise08: Generators
from exercises.week03.exercise08.solution import (
    count_up_to,
    evens_only,
    infinite_counter,
    take,
)


def test_count_up_to():
    assert list(count_up_to(5)) == [1, 2, 3, 4, 5]


def test_count_up_to_is_lazy_generator():
    gen = count_up_to(3)
    assert hasattr(gen, "__next__")
    assert next(gen) == 1
    assert next(gen) == 2


def test_evens_only():
    assert list(evens_only([1, 2, 3, 4, 5, 6])) == [2, 4, 6]


def test_infinite_counter_via_take():
    assert take(infinite_counter(), 5) == [0, 1, 2, 3, 4]


def test_take_with_finite_generator():
    assert take(count_up_to(100), 3) == [1, 2, 3]
