"""
Tests for stage07/exercise03 -- OOP II: Duck Typing and Composition.
Auto-generated by generate.py from generator/stage07.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage07.exercise03.solution import (
    Engine,
    Boat,
    Duck,
    Person,
    make_it_quack,
    is_duck_instance,
)


def test_boat_composition_delegates_to_engine():
    boat = Boat(Engine())
    assert boat.start() == "Engine starting..."


def test_make_it_quack_duck():
    assert make_it_quack(Duck()) == "Quack!"


def test_make_it_quack_person_duck_typing():
    assert make_it_quack(Person()) == "I'm quacking like a duck!"


def test_is_duck_instance():
    assert is_duck_instance(Duck()) is True
    assert is_duck_instance(Person()) is False
