"""
Tests for stage01/tier0_hello_world -- Python Fundamentals: Hello, World! (Environment Check).
Auto-generated by generate.py from generator/stage01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import sys


def test_hello_world_variables_and_output(capsys):
    """greeting == "Hello, World!"; author_name is a non-empty str; two print() lines match exactly (concatenation, no f-strings)."""
    sys.modules.pop("exercises.stage01.tier0_hello_world.solution", None)
    import exercises.stage01.tier0_hello_world.solution as solution

    assert solution.greeting == "Hello, World!"
    assert isinstance(solution.author_name, str)
    assert solution.author_name != ""

    out = capsys.readouterr().out
    lines = out.rstrip("\n").split("\n")
    assert lines[0] == "Hello, World!"
    assert lines[1] == "This is " + solution.author_name + "'s first Python program."
