"""
Tests for week08/exercise04 -- The Python Data Model: Callables.
Auto-generated by generate.py from generator/week08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week08.exercise04.solution import Multiplier, Adder, Toggler


def test_multiplier():
    double = Multiplier(2)
    assert double(5) == 10


def test_adder():
    add5 = Adder(5)
    assert add5(10) == 15


def test_toggler_carries_state():
    toggle = Toggler()
    assert toggle() is True
    assert toggle() is False
    assert toggle() is True


def test_instances_are_callable():
    assert callable(Multiplier(2))
    assert callable(Adder(1))
    assert callable(Toggler())
