"""
Tests for stage02/basic01 -- Control Flow: Warehouse Grid Scanner.
Auto-generated by generate.py from generator/stage02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import exercises.stage02.basic01.solution as solution


def test_obstacle_count():
    """obstacle_count == total "#" characters across the grid."""
    assert solution.obstacle_count == 6


def test_unmapped_count():
    """unmapped_count == total "?" characters, only from rows NOT skipped entirely."""
    assert solution.unmapped_count == 1


def test_invalid_char_count():
    """invalid_char_count == total characters that are none of "#"/"."/"?"."""
    assert solution.invalid_char_count == 1


def test_first_obstacle_position():
    """first_obstacle_row/col == the first "#" found scanning row by row, left to right."""
    assert solution.first_obstacle_row == 0
    assert solution.first_obstacle_col == 2


def test_rows_skipped():
    """rows_skipped counts rows that are entirely "?????", skipped via continue before the inner scan."""
    assert solution.rows_skipped == 1


def test_last_obstacle_row_via_while_and_break():
    """last_obstacle_row is found by a SEPARATE while-loop scanning from the bottom, breaking on the first hit."""
    assert solution.last_obstacle_row == 4
