"""
Tests for stage11/advanced02 -- OpenCV: Cascade Classifiers.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import cv2
from exercises.stage11.advanced02.solution import (
    load_default_face_cascade,
    load_cascade_from_path,
    is_cascade_loaded,
)


def test_load_default_face_cascade_loads_successfully():
    """load_default_face_cascade must load one of OpenCV's built-in pretrained cascades."""
    cascade = load_default_face_cascade()
    assert is_cascade_loaded(cascade) is True


def test_load_cascade_from_bad_path_fails_to_load():
    """is_cascade_loaded must be False when the given path doesn't point to a real cascade file."""
    cascade = load_cascade_from_path("/nonexistent/cascade.xml")
    assert is_cascade_loaded(cascade) is False


def test_load_cascade_from_good_path():
    """load_cascade_from_path must work for a real path too, not just load_default_face_cascade's hardcoded one."""
    good_path = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
    cascade = load_cascade_from_path(good_path)
    assert is_cascade_loaded(cascade) is True
