"""
Tests for stage13/tier1_basic02 -- Local API Endpoints: Running the App.
Auto-generated by generate.py from generator/stage13.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from unittest.mock import patch
from fastapi.testclient import TestClient
from exercises.stage13.tier1_basic02.solution import app as running_app, run_server

running_client = TestClient(running_app)


def test_health():
    """GET /health returns {"status": "ok"}."""
    assert running_client.get("/health").json() == {"status": "ok"}


def test_create_note_post():
    """POST /notes returns the JSON body unchanged."""
    assert running_client.post("/notes", json={"text": "hi"}).json() == {"text": "hi"}


def test_run_server_calls_uvicorn_run_without_starting_a_server():
    """run_server must call uvicorn.run(app, host=host, port=port) -- mocked here so no real server starts."""
    with patch("uvicorn.run") as mock_run:
        run_server(running_app, host="0.0.0.0", port=9000)
    mock_run.assert_called_once_with(running_app, host="0.0.0.0", port=9000)
