"""
Tests for week05/exercise01 -- Files, Exceptions, Regex: File Basics.
Auto-generated by generate.py from generator/week05.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week05.exercise01.solution import (
    write_lines,
    read_lines,
    append_line,
    count_lines,
)


def test_write_and_read_lines(tmp_path):
    path = str(tmp_path / "data.txt")
    write_lines(path, ["a", "b", "c"])
    assert read_lines(path) == ["a", "b", "c"]


def test_append_line(tmp_path):
    path = str(tmp_path / "data.txt")
    write_lines(path, ["a"])
    append_line(path, "b")
    assert read_lines(path) == ["a", "b"]


def test_count_lines(tmp_path):
    path = str(tmp_path / "data.txt")
    write_lines(path, ["a", "b", "c", "d"])
    assert count_lines(path) == 4
