"""
Tests for stage03/basic02 -- Functions: Digit & List Utilities.
Auto-generated by generate.py from generator/stage03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage03.basic02.solution import (
    count_digits,
    sum_of_squares_recursive,
    square,
    is_even,
)


def test_count_digits_recursive():
    """count_digits(n) must be recursive; check both a multi-digit and a single-digit input."""
    assert count_digits(12345) == 5
    assert count_digits(7) == 1


def test_sum_of_squares_recursive():
    """sum_of_squares_recursive(numbers) must be recursive; check a non-empty list and the empty-list base case."""
    assert sum_of_squares_recursive([1, 2, 3]) == 14
    assert sum_of_squares_recursive([]) == 0


def test_square_lambda():
    """square must be a lambda equivalent to `lambda x: x * x`."""
    assert square(6) == 36


def test_is_even_lambda():
    """is_even must be a lambda equivalent to `lambda x: x % 2 == 0`, returning real bools."""
    assert is_even(4) is True
    assert is_even(3) is False
