"""
Tests for stage05/basic02 -- Files, Exceptions, Regex: Support Ticket Intake.
Auto-generated by generate.py from generator/stage05.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage05.basic02.solution import (
    extract_ticket_ids,
    contains_urgent_flag,
    clean_ticket_text,
    looks_like_ticket_id,
    parse_priority,
    parse_priority_with_default,
    get_parse_attempts,
)

TEXT = "TICKET-101 is URGENT, also TICKET-202 reported.  Please   check."


def test_extract_ticket_ids():
    """extract_ticket_ids == re.findall(r"TICKET-\d+", text)."""
    assert extract_ticket_ids(TEXT) == ["TICKET-101", "TICKET-202"]


def test_contains_urgent_flag():
    """contains_urgent_flag uses re.search with a \bURGENT\b word-boundary pattern."""
    assert contains_urgent_flag(TEXT) is True
    assert contains_urgent_flag("nothing to see here") is False


def test_clean_ticket_text_collapses_whitespace():
    """clean_ticket_text uses re.sub(r"\s+", " ", text).strip()."""
    assert clean_ticket_text(TEXT) == (
        "TICKET-101 is URGENT, also TICKET-202 reported. Please check."
    )


def test_looks_like_ticket_id_requires_whole_string_match():
    """looks_like_ticket_id must anchor at both start (re.match) and end ($) -- only a bare ticket id matches."""
    assert looks_like_ticket_id("TICKET-101") is True
    assert looks_like_ticket_id("TICKET-101 is URGENT") is False


def test_parse_priority_raises_plain_exception():
    """parse_priority catches ValueError and re-raises as a plain Exception with a clearer message."""
    assert parse_priority("5") == 5
    with pytest.raises(Exception):
        parse_priority("abc")


def test_parse_priority_with_default_and_finally_counts_every_attempt():
    """parse_priority_with_default falls back to default on ValueError, and finally must count BOTH the success and the failure."""
    _ = get_parse_attempts()
    parse_priority_with_default("abc", default=3)
    after_failure = get_parse_attempts()
    parse_priority_with_default("7", default=3)
    after_success = get_parse_attempts()
    assert after_success == after_failure + 1
    assert parse_priority_with_default("abc", default=3) == 3
    assert parse_priority_with_default("7", default=3) == 7
