"""
Aggregated tests for week06 -- OOP I.
Auto-generated by generate.py from generator/week06.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: Bank Account
import pytest
from exercises.week06.exercise01.solution import BankAccount


def test_initial_balance():
    acct = BankAccount("Ada", 100)
    assert acct.balance == 100


def test_deposit():
    acct = BankAccount("Ada", 100)
    acct.deposit(50)
    assert acct.balance == 150


def test_withdraw():
    acct = BankAccount("Ada", 100)
    acct.withdraw(30)
    assert acct.balance == 70


def test_withdraw_insufficient_funds_raises():
    acct = BankAccount("Ada", 100)
    with pytest.raises(ValueError):
        acct.withdraw(200)


def test_negative_balance_raises():
    with pytest.raises(ValueError):
        BankAccount("Ada", -5)


def test_is_valid_amount():
    assert BankAccount.is_valid_amount(10) is True
    assert BankAccount.is_valid_amount(-1) is False
    assert BankAccount.is_valid_amount("10") is False


# ------------------------------------------------------------------ exercise02: Employee Registry
from exercises.week06.exercise02.solution import Employee


def test_instance_attributes_are_per_employee():
    a = Employee("Ada", 90000)
    b = Employee("Grace", 95000)
    assert a.name == "Ada"
    assert b.name == "Grace"
    assert a.salary != b.salary


def test_class_attribute_shared_across_instances():
    a = Employee("Ada", 90000)
    b = Employee("Grace", 95000)
    assert a.company_name == "Acme Corp"
    assert b.company_name == "Acme Corp"
    assert a.company_name is b.company_name


def test_employee_count_increments():
    before = Employee.get_employee_count()
    Employee("New Hire", 50000)
    after = Employee.get_employee_count()
    assert after == before + 1


def test_hire_intern_alternate_constructor():
    intern = Employee.hire_intern("Intern Ivy")
    assert intern.name == "Intern Ivy"
    assert intern.salary == 0
    assert isinstance(intern, Employee)


def test_is_valid_salary():
    assert Employee.is_valid_salary(50000) is True
    assert Employee.is_valid_salary(-1) is False


# ------------------------------------------------------------------ exercise03: Rectangle Properties
import pytest
from exercises.week06.exercise03.solution import Rectangle


def test_area():
    assert Rectangle(4, 5).area == 20


def test_perimeter():
    assert Rectangle(4, 5).perimeter == 18


def test_is_square():
    assert Rectangle(4, 4).is_square is True
    assert Rectangle(4, 5).is_square is False


def test_width_setter_validates():
    rect = Rectangle(4, 5)
    with pytest.raises(ValueError):
        rect.width = -1


def test_height_setter_validates():
    with pytest.raises(ValueError):
        Rectangle(4, -5)


def test_changing_width_updates_area():
    rect = Rectangle(4, 5)
    rect.width = 10
    assert rect.area == 50


# ------------------------------------------------------------------ exercise04: Slots and Memory
import pytest
from exercises.week06.exercise04.solution import PointSlots, Vector3DSlots, TemperatureSlots


def test_point_slots_basic():
    p = PointSlots(1, 2)
    assert (p.x, p.y) == (1, 2)


def test_point_slots_has_no_dict():
    p = PointSlots(1, 2)
    assert not hasattr(p, "__dict__")


def test_point_slots_rejects_new_attribute():
    p = PointSlots(1, 2)
    with pytest.raises(AttributeError):
        p.z = 3


def test_vector3d_slots_magnitude():
    v = Vector3DSlots(2, 3, 6)
    assert v.magnitude() == 7.0


def test_temperature_slots_fahrenheit():
    t = TemperatureSlots(0)
    assert t.fahrenheit() == 32.0


# ------------------------------------------------------------------ exercise05: Descriptors Preview
import pytest
from exercises.week06.exercise05.solution import Product, Person


def test_positive_number_descriptor_get_set():
    p = Product("Widget", 9.99)
    assert p.price == 9.99
    p.price = 19.99
    assert p.price == 19.99


def test_positive_number_descriptor_rejects_negative():
    p = Product("Widget", 9.99)
    with pytest.raises(ValueError):
        p.price = -1


def test_positive_number_descriptor_rejects_at_construction():
    with pytest.raises(ValueError):
        Product("Widget", -5)


def test_typed_descriptor_get_set():
    person = Person("Ada", 30)
    assert person.name == "Ada"
    assert person.age == 30


def test_typed_descriptor_rejects_wrong_type():
    person = Person("Ada", 30)
    with pytest.raises(TypeError):
        person.age = "thirty"


def test_typed_descriptor_rejects_at_construction():
    with pytest.raises(TypeError):
        Person("Ada", "thirty")
