"""
Tests for week11/exercise02 -- OpenCV: Color Conversion and Resizing.
Auto-generated by generate.py from generator/week11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import numpy as np
from exercises.week11.exercise02.solution import (
    to_grayscale,
    to_rgb,
    resize_image,
    resize_by_scale,
    get_shape_after_resize,
)


def _bgr_image():
    image = np.zeros((10, 10, 3), dtype=np.uint8)
    image[:, :] = (255, 0, 0)
    return image


def test_to_grayscale_drops_channel_dim():
    gray = to_grayscale(_bgr_image())
    assert gray.shape == (10, 10)


def test_to_rgb_swaps_channel_order():
    rgb = to_rgb(_bgr_image())
    assert tuple(rgb[0, 0]) == (0, 0, 255)


def test_resize_image():
    resized = resize_image(_bgr_image(), 20, 5)
    assert resized.shape[:2] == (5, 20)


def test_resize_by_scale():
    resized = resize_by_scale(_bgr_image(), 2.0)
    assert resized.shape[:2] == (20, 20)


def test_get_shape_after_resize():
    assert get_shape_after_resize(_bgr_image(), 40, 30) == (30, 40)
