"""
Tests for stage08/tier3_advanced01 -- The Python Data Model: Money and Score: Operator Overloading.
Auto-generated by generate.py from generator/stage08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage08.tier3_advanced01.solution import Money, Score


def test_money_add_and_eq():
    """Money.__add__ combines cents; __eq__ compares by value."""
    assert Money(100) + Money(50) == Money(150)


def test_money_sum_uses_radd():
    """sum() starts from 0 + Money(...), which needs __radd__ to succeed."""
    assert sum([Money(100), Money(200), Money(300)]) == Money(600)


def test_money_hash_required_alongside_eq():
    """Money must be hashable (via __hash__) since it defines __eq__, or it couldn't go in a set."""
    assert len({Money(100), Money(100), Money(200)}) == 2


def test_score_add_and_sum_independently_of_money():
    """Score implements the same pattern independently -- no shared base class with Money."""
    assert Score(10) + Score(5) == Score(15)
    assert sum([Score(1), Score(2), Score(3)]) == Score(6)


def test_money_repr():
    """__repr__ == f"Money({cents})"."""
    assert repr(Money(500)) == "Money(500)"
