"""
Tests for stage10/exercise02 -- Pandas: Boolean Indexing.
Auto-generated by generate.py from generator/stage10.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pandas as pd
from exercises.stage10.exercise02.solution import (
    filter_by_region,
    filter_high_sales,
    filter_multiple_conditions,
)


def _filter_sample_df():
    return pd.DataFrame({
        "region": ["east", "west", "east", "west"],
        "product": ["A", "B", "C", "D"],
        "sales": [100, 250, 50, 300],
    })


def test_filter_by_region():
    result = filter_by_region(_filter_sample_df(), "east")
    assert list(result["product"]) == ["A", "C"]


def test_filter_high_sales():
    result = filter_high_sales(_filter_sample_df(), 100)
    assert list(result["product"]) == ["B", "D"]


def test_filter_multiple_conditions():
    result = filter_multiple_conditions(_filter_sample_df(), "west", 100)
    assert list(result["product"]) == ["B", "D"]
