"""
Tests for stage11/tier1_basic02 -- OpenCV: Hand Posture & Face Gesture Recognition: Preparing Frames for Detection.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import numpy as np
from exercises.stage11.tier1_basic02.solution import (
    to_grayscale,
    resize_for_processing,
    draw_detection_box,
    draw_multiple_boxes,
)


def _bgr_frame():
    frame = np.zeros((10, 10, 3), dtype=np.uint8)
    frame[:, :] = (255, 0, 0)
    return frame


def test_to_grayscale_drops_channel_dim():
    """to_grayscale must use cv2.COLOR_BGR2GRAY, producing a 2D array."""
    gray = to_grayscale(_bgr_frame())
    assert gray.shape == (10, 10)


def test_resize_for_processing_uses_width_height_order():
    """resize_for_processing passes (width, height) to cv2.resize -- the opposite of .shape's (height, width)."""
    resized = resize_for_processing(_bgr_frame(), 20, 5)
    assert resized.shape[:2] == (5, 20)


def test_draw_detection_box_does_not_mutate_original():
    """draw_detection_box must draw on frame.copy(), leaving the original untouched."""
    frame = np.zeros((20, 20, 3), dtype=np.uint8)
    result = draw_detection_box(frame, (2, 2, 8, 8), (255, 255, 255))
    assert np.array_equal(frame, np.zeros((20, 20, 3), dtype=np.uint8))
    assert result[2, 2].tolist() == [255, 255, 255]


def test_draw_multiple_boxes_draws_all_and_does_not_mutate():
    """draw_multiple_boxes draws every box from a copy, leaving the original frame untouched."""
    frame = np.zeros((30, 30, 3), dtype=np.uint8)
    boxes = [(1, 1, 4, 4), (10, 10, 5, 5)]
    result = draw_multiple_boxes(frame, boxes, (255, 0, 0))
    assert result[1, 1].tolist() == [255, 0, 0]
    assert result[10, 10].tolist() == [255, 0, 0]
    assert frame.sum() == 0
