"""
Tests for stage04/exercise02 -- Data Structures: Dict and Set Operations.
Auto-generated by generate.py from generator/stage04.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage04.exercise02.solution import (
    word_lengths,
    index_lookup,
    numbered_pairs,
    pair_and_dict,
    common_elements,
    unique_to_first,
    all_elements,
)


def test_word_lengths():
    assert word_lengths(["a", "bb"]) == {"a": 1, "bb": 2}


def test_index_lookup():
    assert index_lookup(["a", "b"]) == {"a": 0, "b": 1}


def test_numbered_pairs():
    assert numbered_pairs(["a", "b"]) == [(0, "a"), (1, "b")]


def test_pair_and_dict():
    assert pair_and_dict(["x", "y"], [1, 2]) == {"x": 1, "y": 2}


def test_common_elements():
    assert common_elements({1, 2, 3}, {2, 3, 4}) == {2, 3}


def test_unique_to_first():
    assert unique_to_first({1, 2, 3}, {2, 3, 4}) == {1}


def test_all_elements():
    assert all_elements({1, 2}, {2, 3}) == {1, 2, 3}
