"""
Tests for stage03/advanced02 -- Functions: Generators, Scope & the Mutable-Default Trap.
Auto-generated by generate.py from generator/stage03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage03.advanced02.solution import (
    batch_generator,
    increment_global,
    make_local_shadow,
)
import exercises.stage03.advanced02.solution as solution


def test_batch_generator_yields_slices():
    """batch_generator must be a generator function (yield), splitting items into batch_size-length chunks."""
    assert list(batch_generator([1, 2, 3, 4, 5], 2)) == [[1, 2], [3, 4], [5]]


def test_batch_generator_is_lazy():
    """Calling batch_generator(...) must return a generator object, not a fully-built list."""
    gen = batch_generator([1, 2, 3], 1)
    assert hasattr(gen, "__next__")
    assert next(gen) == [1]


def test_increment_global_mutates_module_level_counter():
    """increment_global uses `global counter` to mutate the actual module-level name across calls."""
    solution.counter = 0
    assert increment_global() == 1
    assert increment_global() == 2
    assert solution.counter == 2


def test_make_local_shadow_does_not_affect_module_level_counter():
    """make_local_shadow's `counter = 100` is a LOCAL assignment (no `global`) -- module-level counter must be untouched."""
    solution.counter = 5
    assert make_local_shadow() == 100
    assert solution.counter == 5


def test_append_bad_demonstrates_mutable_default_argument_bug():
    """append_bad's default target=[] is a SHARED object reused across calls -- items accumulate silently."""
    first_call_result = solution.append_bad(1)
    second_call_result = solution.append_bad(2)
    assert second_call_result == [1, 2]
    assert first_call_result is second_call_result


def test_append_safe_gives_a_fresh_list_each_call():
    """append_safe's target=None sentinel must produce an independent list on every call with no target passed."""
    first_call_result = solution.append_safe(1)
    second_call_result = solution.append_safe(2)
    assert first_call_result == [1]
    assert second_call_result == [2]
