"""
Tests for stage11/advanced01 -- OpenCV: Blurring and Contours.
Auto-generated by generate.py from generator/stage11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import cv2
import numpy as np
from exercises.stage11.advanced01.solution import (
    apply_gaussian_blur,
    apply_strong_blur,
    find_contours,
    count_contours,
    largest_contour_area,
)


def test_apply_gaussian_blur_preserves_shape():
    """apply_gaussian_blur must preserve the image's shape."""
    image = np.random.randint(0, 255, (20, 20, 3), dtype=np.uint8)
    blurred = apply_gaussian_blur(image, 5)
    assert blurred.shape == image.shape


def test_apply_strong_blur_smooths_more_than_light_blur():
    """apply_strong_blur's larger (15,15) kernel must smooth a single bright pixel more than a small (3,3) kernel."""
    image = np.zeros((30, 30), dtype=np.uint8)
    image[15, 15] = 255
    light = apply_gaussian_blur(image, 3)
    strong = apply_strong_blur(image)
    assert strong[15, 15] < light[15, 15]


def _square_binary_image():
    image = np.zeros((50, 50), dtype=np.uint8)
    cv2.rectangle(image, (10, 10), (30, 30), 255, -1)
    return image


def test_find_and_count_contours():
    """find_contours/count_contours must find exactly one contour for one filled square."""
    contours = find_contours(_square_binary_image())
    assert len(contours) == 1
    assert count_contours(_square_binary_image()) == 1


def test_largest_contour_area():
    """largest_contour_area uses cv2.contourArea over all found contours."""
    area = largest_contour_area(_square_binary_image())
    assert 300 < area < 500
