"""
Tests for stage07/tier3_advanced01 -- OOP II: Mixins.
Auto-generated by generate.py from generator/stage07.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage07.tier3_advanced01.solution import LoggingMixin, SerializableMixin, Widget


def test_widget_uses_both_mixins():
    """Widget gets .log() and .to_dict() for free by combining both mixins."""
    w = Widget("gadget")
    assert w.log("created") == "[Widget] created"
    assert w.to_dict() == {"name": "gadget"}


def test_log_reports_the_actual_class_name():
    """LoggingMixin.log must read self.__class__.__name__, so it reports "Widget", not "LoggingMixin"."""
    w = Widget("gadget")
    assert "Widget" in w.log("test")
    assert "LoggingMixin" not in w.log("test")


def test_widget_is_instance_of_both_mixins():
    """Widget must be a real instance of both mixin classes via multiple inheritance."""
    w = Widget("gadget")
    assert isinstance(w, LoggingMixin)
    assert isinstance(w, SerializableMixin)
