"""
Tests for stage01/tier3_advanced02 -- Python Fundamentals: Big Numbers and String Identity.
Auto-generated by generate.py from generator/stage01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import exercises.stage01.tier3_advanced02.solution as solution


def test_huge_power_has_arbitrary_precision():
    """huge_power == base ** exponent, with no overflow; huge_power_digit_count == len(str(huge_power))."""
    assert solution.huge_power == 97 ** 42
    assert solution.huge_power_digit_count > 19  # bigger than any 64-bit int could hold


def test_small_int_caching():
    """small_ints_share_identity == (small_int_a is small_int_b) -- both literal 100s; CPython caches -5..256."""
    assert solution.small_ints_share_identity is True


def test_large_ints_not_guaranteed_cached():
    """large_int_from_conversion must be int("1000000") at RUNTIME, not a second literal -- large ints aren't guaranteed cached."""
    assert solution.large_int_from_literal == solution.large_int_from_conversion
    assert solution.large_ints_share_identity is False


def test_string_literal_interning():
    """string_literals_share_identity == (string_literal_a is string_literal_b) -- both literal "python_stage01"; simple literals are interned."""
    assert solution.string_literals_share_identity is True


def test_runtime_built_string_not_interned():
    """string_built_at_runtime must be "".join([...]) built dynamically -- equal to string_literal_a by value, but not the same object."""
    assert solution.string_literal_a == solution.string_built_at_runtime
    assert solution.runtime_string_shares_identity is False
