"""
Tests for stage03/tier2_mid02 -- Functions: Call-Counting Decorator + Validated Config.
Auto-generated by generate.py from generator/stage03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage03.tier2_mid02.solution import count_calls, greet, make_validator


def test_greet_returns_expected_message():
    """greet(name) returns "Hello, " + name."""
    assert greet("Ada") == "Hello, Ada"


def test_count_calls_tracks_call_count_on_wrapper():
    """count_calls(fn) returns a wrapper exposing wrapper.calls (incrementing by 1 per call) while still forwarding to fn."""
    tracked_greet = count_calls(greet)
    assert tracked_greet("Bo") == "Hello, Bo"
    assert tracked_greet("Cy") == "Hello, Cy"
    assert tracked_greet.calls == 2


def test_make_validator_default_max_value():
    """make_validator(min_value=...) uses the default max_value=100 and returns a validate(n) closure."""
    validate = make_validator(min_value=10)
    assert validate(5) is False
    assert validate(50) is True


def test_make_validator_custom_max_value():
    """make_validator(min_value=..., max_value=...) -- both bounds are honored by the returned closure."""
    validate = make_validator(min_value=0, max_value=10)
    assert validate(15) is False
    assert validate(5) is True


def test_make_validator_arguments_are_keyword_only():
    """min_value/max_value must be keyword-only -- calling make_validator positionally must raise TypeError."""
    with pytest.raises(TypeError):
        make_validator(0, 10)
