"""
Tests for stage12/basic01 -- Requests + Threading: Requests Basics.
Auto-generated by generate.py from generator/stage12.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from unittest.mock import Mock, patch
from exercises.stage12.basic01.solution import fetch_json, fetch_status_code, post_data


def _fake_response(json_data=None, status_code=200):
    response = Mock()
    response.json.return_value = json_data or {}
    response.status_code = status_code
    return response


def test_fetch_json():
    """fetch_json == requests.get(url).json()."""
    with patch("requests.get", return_value=_fake_response({"id": 1})) as mock_get:
        result = fetch_json("https://example.test/api")
    mock_get.assert_called_once_with("https://example.test/api")
    assert result == {"id": 1}


def test_fetch_status_code():
    """fetch_status_code == requests.get(url).status_code."""
    with patch("requests.get", return_value=_fake_response(status_code=404)):
        assert fetch_status_code("https://example.test/api") == 404


def test_post_data():
    """post_data == requests.post(url, json=payload).json()."""
    with patch("requests.post", return_value=_fake_response({"created": True})) as mock_post:
        result = post_data("https://example.test/api", {"name": "Ada"})
    mock_post.assert_called_once_with("https://example.test/api", json={"name": "Ada"})
    assert result == {"created": True}
