"""
Tests for stage07/tier4_testing -- OOP II: Testing Without a Framework: Catch the Bug.
Auto-generated by generate.py from generator/stage07.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage07.tier4_testing.solution import check, run_all_checks, _check_log


def test_check_records_a_passing_condition_and_returns_it():
    """check(description, True) must append (description, True) to _check_log and return True."""
    _check_log.clear()
    result = check("sample passing check", True)
    assert result is True
    assert _check_log[-1] == ("sample passing check", True)


def test_check_never_raises_on_a_failing_condition():
    """check(description, False) must NOT raise -- unlike assert, it records the failure and returns False."""
    _check_log.clear()
    result = check("sample failing check", False)
    assert result is False
    assert _check_log[-1] == ("sample failing check", False)


def test_run_all_checks_runs_exactly_four_checks():
    """run_all_checks must call check() exactly once per implementation named in README.md -- four total."""
    summary = run_all_checks()
    assert summary["total"] == 4


def test_run_all_checks_catches_both_bugs():
    """Checked against the shared spec-derived value, Square/make_it_quack_correct pass and the _buggy versions fail."""
    summary = run_all_checks()
    assert summary["passed"] == 2
    assert len(summary["failed"]) == 2
