"""
Aggregated tests for week11 -- OpenCV.
Auto-generated by generate.py from generator/week11.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: Image I/O and Shape
import numpy as np
from exercises.week11.exercise01.solution import (
    load_image,
    save_image,
    get_dimensions,
    get_channel_count,
)


def test_save_and_load_roundtrip(tmp_path):
    path = str(tmp_path / "img.png")
    original = np.zeros((20, 30, 3), dtype=np.uint8)
    original[:, :] = (0, 0, 255)
    assert save_image(path, original) is True
    loaded = load_image(path)
    assert loaded is not None
    assert loaded.shape == (20, 30, 3)


def test_load_missing_file_returns_none():
    assert load_image("/nonexistent/path/to/image.png") is None


def test_get_dimensions():
    image = np.zeros((20, 30, 3), dtype=np.uint8)
    assert get_dimensions(image) == (20, 30)


def test_get_channel_count_color():
    image = np.zeros((10, 10, 3), dtype=np.uint8)
    assert get_channel_count(image) == 3


def test_get_channel_count_grayscale():
    image = np.zeros((10, 10), dtype=np.uint8)
    assert get_channel_count(image) == 1


# ------------------------------------------------------------------ exercise02: Color Conversion and Resizing
import numpy as np
from exercises.week11.exercise02.solution import (
    to_grayscale,
    to_rgb,
    resize_image,
    resize_by_scale,
    get_shape_after_resize,
)


def _bgr_image():
    image = np.zeros((10, 10, 3), dtype=np.uint8)
    image[:, :] = (255, 0, 0)
    return image


def test_to_grayscale_drops_channel_dim():
    gray = to_grayscale(_bgr_image())
    assert gray.shape == (10, 10)


def test_to_rgb_swaps_channel_order():
    rgb = to_rgb(_bgr_image())
    assert tuple(rgb[0, 0]) == (0, 0, 255)


def test_resize_image():
    resized = resize_image(_bgr_image(), 20, 5)
    assert resized.shape[:2] == (5, 20)


def test_resize_by_scale():
    resized = resize_by_scale(_bgr_image(), 2.0)
    assert resized.shape[:2] == (20, 20)


def test_get_shape_after_resize():
    assert get_shape_after_resize(_bgr_image(), 40, 30) == (30, 40)


# ------------------------------------------------------------------ exercise03: Drawing on Images
import numpy as np
from exercises.week11.exercise03.solution import (
    draw_rectangle,
    draw_filled_rectangle,
    draw_bounding_boxes,
)


def test_draw_rectangle_does_not_mutate_original():
    image = np.zeros((20, 20, 3), dtype=np.uint8)
    result = draw_rectangle(image, (2, 2), (10, 10), (255, 255, 255))
    assert np.array_equal(image, np.zeros((20, 20, 3), dtype=np.uint8))
    assert result[2, 2].tolist() == [255, 255, 255]


def test_draw_filled_rectangle_fills_interior():
    image = np.zeros((20, 20, 3), dtype=np.uint8)
    result = draw_filled_rectangle(image, (2, 2), (10, 10), (255, 255, 255))
    assert result[5, 5].tolist() == [255, 255, 255]


def test_draw_bounding_boxes_draws_all():
    image = np.zeros((30, 30, 3), dtype=np.uint8)
    boxes = [(1, 1, 5, 5), (10, 10, 15, 15)]
    result = draw_bounding_boxes(image, boxes, (255, 0, 0))
    assert result[1, 1].tolist() == [255, 0, 0]
    assert result[10, 10].tolist() == [255, 0, 0]


# ------------------------------------------------------------------ exercise04: Thresholding and Blurring
import numpy as np
from exercises.week11.exercise04.solution import (
    apply_threshold,
    apply_otsu_threshold,
    apply_adaptive_threshold,
    apply_gaussian_blur,
    apply_strong_blur,
)


def _half_bright_gray():
    image = np.zeros((20, 20), dtype=np.uint8)
    image[:, 10:] = 200
    return image


def test_apply_threshold():
    result = apply_threshold(_half_bright_gray(), 100)
    assert result[0, 0] == 0
    assert result[0, 15] == 255


def test_apply_otsu_threshold_separates_regions():
    result = apply_otsu_threshold(_half_bright_gray())
    assert result[0, 0] != result[0, 15]


def test_apply_adaptive_threshold_returns_binary_image():
    result = apply_adaptive_threshold(_half_bright_gray())
    assert result.shape == (20, 20)
    assert set(np.unique(result)).issubset({0, 255})


def test_apply_gaussian_blur_preserves_shape():
    image = np.random.randint(0, 255, (20, 20, 3), dtype=np.uint8)
    blurred = apply_gaussian_blur(image, 5)
    assert blurred.shape == image.shape


def test_apply_strong_blur_smooths_more_than_light_blur():
    image = np.zeros((30, 30), dtype=np.uint8)
    image[15, 15] = 255
    light = apply_gaussian_blur(image, 3)
    strong = apply_strong_blur(image)
    assert strong[15, 15] < light[15, 15]


# ------------------------------------------------------------------ exercise05: Edges and Contours
import cv2
import numpy as np
from exercises.week11.exercise05.solution import (
    detect_edges,
    detect_edges_default,
    count_edge_pixels,
    find_contours,
    count_contours,
    largest_contour_area,
)


def _square_image():
    image = np.zeros((50, 50), dtype=np.uint8)
    cv2.rectangle(image, (10, 10), (30, 30), 255, -1)
    return image


def test_detect_edges_finds_something():
    edges = detect_edges(_square_image(), 50, 150)
    assert edges.sum() > 0


def test_detect_edges_default():
    edges = detect_edges_default(_square_image())
    assert edges.shape == (50, 50)


def test_count_edge_pixels():
    assert count_edge_pixels(_square_image(), 50, 150) > 0


def test_find_and_count_contours():
    contours = find_contours(_square_image())
    assert len(contours) == 1
    assert count_contours(_square_image()) == 1


def test_largest_contour_area():
    area = largest_contour_area(_square_image())
    assert 300 < area < 500


# ------------------------------------------------------------------ exercise06: NumPy Arrays and Cascade Classifiers
import cv2
import numpy as np
from exercises.week11.exercise06.solution import (
    create_blank_image,
    crop_image,
    paste_region,
    load_default_face_cascade,
    load_cascade_from_path,
    is_cascade_loaded,
)


def test_create_blank_image():
    image = create_blank_image(10, 20, 3)
    assert image.shape == (10, 20, 3)
    assert image.sum() == 0


def test_crop_image():
    image = np.arange(100).reshape(10, 10).astype(np.uint8)
    cropped = crop_image(image, 2, 5, 3, 6)
    assert cropped.shape == (3, 3)


def test_paste_region_does_not_mutate_original():
    image = np.zeros((10, 10), dtype=np.uint8)
    region = np.full((3, 3), 255, dtype=np.uint8)
    result = paste_region(image, region, 2, 2)
    assert image.sum() == 0
    assert result[2, 2] == 255


def test_load_default_face_cascade_loads_successfully():
    cascade = load_default_face_cascade()
    assert is_cascade_loaded(cascade) is True


def test_load_cascade_from_bad_path_fails_to_load():
    cascade = load_cascade_from_path("/nonexistent/cascade.xml")
    assert is_cascade_loaded(cascade) is False


def test_load_cascade_from_good_path():
    good_path = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
    cascade = load_cascade_from_path(good_path)
    assert is_cascade_loaded(cascade) is True
