"""
Tests for week13/exercise02 -- Local API Endpoints: Pydantic Models.
Auto-generated by generate.py from generator/week13.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from fastapi.testclient import TestClient
from exercises.week13.exercise02.solution import app as models_app

models_client = TestClient(models_app)


def test_create_item_defaults_in_stock_true():
    response = models_client.post("/items", json={"name": "Widget", "price": 9.99})
    assert response.json() == {"name": "Widget", "price": 9.99, "in_stock": True}


def test_create_item_validation_rejects_missing_field():
    response = models_client.post("/items", json={"name": "Widget"})
    assert response.status_code == 422


def test_create_user():
    response = models_client.post("/users", json={"username": "ada", "age": 30})
    assert response.json() == {"username": "ada", "age": 30}


def test_login_never_echoes_password():
    response = models_client.post("/login", json={"username": "ada", "password": "secret"})
    data = response.json()
    assert data == {"ok": True, "username": "ada"}
    assert "password" not in data
