"""
Tests for week04/exercise04 -- Data Structures: Collections Toolbox.
Auto-generated by generate.py from generator/week04.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week04.exercise04.solution import (
    group_by_first_letter,
    count_occurrences,
    most_common_n,
    sliding_window_last_n,
    rotate_queue,
)


def test_group_by_first_letter():
    result = group_by_first_letter(["apple", "avocado", "banana", "cherry"])
    assert result == {"a": ["apple", "avocado"], "b": ["banana"], "c": ["cherry"]}


def test_count_occurrences():
    assert count_occurrences(["a", "b", "a", "c", "a"]) == {"a": 3, "b": 1, "c": 1}


def test_most_common_n():
    assert most_common_n(["a", "b", "a", "c", "a", "b"], 2) == [("a", 3), ("b", 2)]


def test_sliding_window_last_n():
    assert sliding_window_last_n([1, 2, 3, 4, 5], 3) == [3, 4, 5]


def test_rotate_queue():
    assert rotate_queue([1, 2, 3, 4, 5], 2) == [4, 5, 1, 2, 3]
