"""
Tests for stage03/advanced01 -- Functions: functools Toolkit.
Auto-generated by generate.py from generator/stage03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage03.advanced01.solution import logged, multiply, fib, add_ten


def test_logged_preserves_metadata_via_functools_wraps():
    """logged(fn) must use functools.wraps(fn) so the wrapper's __name__/__doc__ still report the ORIGINAL function, not "wrapper"."""
    decorated = logged(multiply)
    assert decorated.__name__ == "multiply"
    assert decorated.__doc__ == "Multiply two numbers."


def test_logged_forwards_call_and_result():
    """The wrapper returned by logged(fn) must still actually call fn(*args, **kwargs) and return its result."""
    decorated = logged(multiply)
    assert decorated(3, 4) == 12


def test_fib_correctness():
    """fib(n) is the standard recursive Fibonacci definition."""
    assert fib(20) == 6765


def test_fib_is_lru_cached():
    """fib must be decorated with functools.lru_cache, exposing cache_info() with recorded hits."""
    fib(20)
    info = fib.cache_info()
    assert info.hits > 0


def test_add_ten_is_functools_partial():
    """add_ten must be functools.partial(lambda a, b: a + b, b=10), not a hand-written equivalent function."""
    import functools
    assert isinstance(add_ten, functools.partial)
    assert add_ten(5) == 15
