"""
Tests for stage12/exercise04 -- Requests + Threading: Locks and Race Conditions.
Auto-generated by generate.py from generator/stage12.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import threading
from exercises.stage12.exercise04.solution import (
    SafeCounter,
    SafeList,
    transfer_funds,
    parallel_increment,
)


def test_safe_counter_survives_real_concurrency():
    counter = SafeCounter()
    parallel_increment(counter, times=2000, num_threads=10)
    assert counter.value == 2000


def test_safe_list_append_from_many_threads():
    safe_list = SafeList()
    threads = [threading.Thread(target=safe_list.append_safe, args=(i,)) for i in range(50)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    assert sorted(safe_list.items) == list(range(50))


def test_transfer_funds_keeps_books_balanced():
    accounts = {"alice": 1000, "bob": 0}
    lock = threading.Lock()
    threads = [
        threading.Thread(target=transfer_funds, args=(accounts, lock, "alice", "bob", 10))
        for _ in range(50)
    ]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    assert accounts["alice"] == 500
    assert accounts["bob"] == 500
    assert accounts["alice"] + accounts["bob"] == 1000
