"""
Tests for stage01/mid02 -- Python Fundamentals: Marathon Pace Report.
Auto-generated by generate.py from generator/stage01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest

import exercises.stage01.mid02.solution as solution


def test_casts_to_correct_types():
    """race_distance_km is a float() cast; elapsed_minutes/target_minutes are int() casts."""
    assert isinstance(solution.race_distance_km, float)
    assert isinstance(solution.elapsed_minutes, int)
    assert isinstance(solution.target_minutes, int)


def test_pace_min_per_km():
    """pace_min_per_km == elapsed_minutes / race_distance_km."""
    assert solution.pace_min_per_km == pytest.approx(6.04337)


def test_walrus_computed_minutes_over_is_exposed_as_module_variable():
    """The walrus assignment inside pace_report's f-string must expose `minutes_over` as its own module-level name too."""
    assert solution.minutes_over == 15


def test_pace_report_contains_minutes_over_and_formatted_pace():
    """pace_report is an f-string containing both the walrus-computed minutes_over and the :.2f-formatted pace."""
    assert "15" in solution.pace_report
    assert "6.04" in solution.pace_report


def test_minutes_over_per_km_reuses_walrus_value():
    """minutes_over_per_km == minutes_over / race_distance_km -- reusing the walrus value, not recomputing elapsed_minutes - target_minutes."""
    assert solution.minutes_over_per_km == pytest.approx(0.35549, abs=1e-4)


def test_on_pace_chained_comparison():
    """on_pace must be one chained comparison: 0 < pace_min_per_km <= 6.5."""
    assert solution.on_pace is True


def test_total_penalty_seconds_via_augmented_assignment():
    """total_penalty_seconds starts at 0 and is built up with two `+=` statements (a flat 30, then minutes_over * 2)."""
    assert solution.total_penalty_seconds == 60


def test_fatigue_index_respects_operator_precedence():
    """fatigue_index == 2 + 3 * pace_min_per_km ** 2, written exactly in that form (no extra parentheses)."""
    assert solution.fatigue_index == pytest.approx(111.56697)
