"""
Tests for stage01/mid02 -- Python Fundamentals: Marathon Pace Report.
Auto-generated by generate.py from generator/stage01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest

import exercises.stage01.mid02.solution as solution


def test_casts_to_correct_types():
    assert isinstance(solution.race_distance_km, float)
    assert isinstance(solution.elapsed_minutes, int)
    assert isinstance(solution.target_minutes, int)


def test_pace_min_per_km():
    assert solution.pace_min_per_km == pytest.approx(6.04337)


def test_walrus_computed_minutes_over_is_exposed_as_module_variable():
    assert solution.minutes_over == 15


def test_pace_report_contains_minutes_over_and_formatted_pace():
    assert "15" in solution.pace_report
    assert "6.04" in solution.pace_report


def test_minutes_over_per_km_reuses_walrus_value():
    assert solution.minutes_over_per_km == pytest.approx(0.35549, abs=1e-4)


def test_on_pace_chained_comparison():
    assert solution.on_pace is True


def test_total_penalty_seconds_via_augmented_assignment():
    assert solution.total_penalty_seconds == 60


def test_fatigue_index_respects_operator_precedence():
    assert solution.fatigue_index == pytest.approx(111.56697)
