"""
Tests for stage06/exercise02 -- OOP I: Employee Registry.
Auto-generated by generate.py from generator/stage06.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage06.exercise02.solution import Employee


def test_instance_attributes_are_per_employee():
    a = Employee("Ada", 90000)
    b = Employee("Grace", 95000)
    assert a.name == "Ada"
    assert b.name == "Grace"
    assert a.salary != b.salary


def test_class_attribute_shared_across_instances():
    a = Employee("Ada", 90000)
    b = Employee("Grace", 95000)
    assert a.company_name == "Acme Corp"
    assert b.company_name == "Acme Corp"
    assert a.company_name is b.company_name


def test_employee_count_increments():
    before = Employee.get_employee_count()
    Employee("New Hire", 50000)
    after = Employee.get_employee_count()
    assert after == before + 1


def test_hire_intern_alternate_constructor():
    intern = Employee.hire_intern("Intern Ivy")
    assert intern.name == "Intern Ivy"
    assert intern.salary == 0
    assert isinstance(intern, Employee)


def test_is_valid_salary():
    assert Employee.is_valid_salary(50000) is True
    assert Employee.is_valid_salary(-1) is False
