"""
Tests for week05/exercise04 -- Files, Exceptions, Regex: Regex Basics.
Auto-generated by generate.py from generator/week05.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week05.exercise04.solution import (
    contains_digit,
    find_all_numbers,
    starts_with_word,
    normalize_whitespace,
    extract_emails,
)


def test_contains_digit():
    assert contains_digit("room 42") is True
    assert contains_digit("no numbers here") is False


def test_find_all_numbers():
    assert find_all_numbers("a1 b22 c333") == ["1", "22", "333"]


def test_starts_with_word():
    assert starts_with_word("hello world", "hello") is True
    assert starts_with_word("say hello", "hello") is False


def test_normalize_whitespace():
    assert normalize_whitespace("a   b\t\tc\n\nd") == "a b c d"


def test_extract_emails():
    text = "contact ada@example.com or grace@nav.mil for details"
    assert extract_emails(text) == ["ada@example.com", "grace@nav.mil"]
