"""
Aggregated tests for week01 -- Python Fundamentals.
Auto-generated by generate.py from generator/week01.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: Profile Basics
from exercises.week01.exercise01.solution import (
    build_profile,
    value_kind,
    display_profile,
)


def test_build_profile():
    profile = build_profile("Ada", 30, 1.7, False)
    assert profile == {"name": "Ada", "age": 30, "height_m": 1.7, "is_student": False}


def test_value_kind_int():
    assert value_kind(5) == "int"


def test_value_kind_str():
    assert value_kind("hi") == "str"


def test_value_kind_float():
    assert value_kind(3.14) == "float"


def test_display_profile(capsys):
    display_profile({"name": "Ada", "age": 30, "height_m": 1.7, "is_student": False})
    out = capsys.readouterr().out
    assert out == "Ada is 30 years old, 1.7m tall, student=False\n"


# ------------------------------------------------------------------ exercise02: Temperature and BMI
from exercises.week01.exercise02.solution import (
    celsius_to_fahrenheit,
    bmi_calculator,
    validate_measurement,
)


def test_celsius_to_fahrenheit_freezing():
    assert celsius_to_fahrenheit(0) == 32.0


def test_celsius_to_fahrenheit_boiling():
    assert celsius_to_fahrenheit(100) == 212.0


def test_bmi_calculator():
    assert abs(bmi_calculator(70, 1.75) - 22.86) < 0.01


def test_validate_measurement_accepts_int_and_float():
    assert validate_measurement(70) is True
    assert validate_measurement(1.75) is True


def test_validate_measurement_rejects_bool():
    assert validate_measurement(True) is False
    assert validate_measurement(False) is False


def test_validate_measurement_rejects_str():
    assert validate_measurement("70") is False


# ------------------------------------------------------------------ exercise03: Type Inspector
from exercises.week01.exercise03.solution import (
    describe_value,
    print_type_report,
    classify_values,
)


def test_describe_value_none():
    assert describe_value(None) == "None (the absence of a value)"


def test_describe_value_int():
    assert describe_value(5) == "5 is a int"


def test_describe_value_str():
    assert describe_value("hi") == "'hi' is a str"


def test_print_type_report(capsys):
    print_type_report(5)
    assert capsys.readouterr().out == "5 is a int\n"


def test_classify_values_separates_bool_from_int():
    result = classify_values([1, 2, True, False, 3.5, "x", None])
    assert result["ints"] == [1, 2]
    assert result["bools"] == [True, False]
    assert result["floats"] == [3.5]
    assert result["strs"] == ["x"]
    assert result["nones"] == [None]


# ------------------------------------------------------------------ exercise04: Boolean Logic
from exercises.week01.exercise04.solution import (
    can_enter_venue,
    access_level,
    is_valid_choice,
    toggle_flag,
)


def test_can_enter_venue_adult_with_ticket():
    assert can_enter_venue(20, True, False) is True


def test_can_enter_venue_minor_rejected():
    assert can_enter_venue(15, True, True) is False


def test_can_enter_venue_unknown_age_rejected():
    assert can_enter_venue(None, True, True) is False


def test_can_enter_venue_vip_without_ticket():
    assert can_enter_venue(25, False, True) is True


def test_access_level_backstage_for_staff():
    assert access_level(False, False, True) == "backstage"


def test_access_level_general_for_ticket_only():
    assert access_level(True, False, False) == "general"


def test_access_level_denied():
    assert access_level(False, False, False) == "denied"


def test_is_valid_choice_true():
    assert is_valid_choice("red", ["red", "blue"]) is True


def test_is_valid_choice_not_in_list():
    assert is_valid_choice("green", ["red", "blue"]) is False


def test_is_valid_choice_empty_string():
    assert is_valid_choice("", ["", "blue"]) is False


def test_is_valid_choice_non_string():
    assert is_valid_choice(5, ["red", "blue"]) is False


def test_toggle_flag():
    assert toggle_flag(True) is False
    assert toggle_flag(False) is True


# ------------------------------------------------------------------ exercise05: CLI Interaction
from exercises.week01.exercise05.solution import (
    ask_name,
    ask_age,
    ask_yes_no,
    greet,
    greeting_flow,
)


def test_ask_name(monkeypatch):
    monkeypatch.setattr("builtins.input", lambda prompt="": "Ada")
    assert ask_name() == "Ada"


def test_ask_age(monkeypatch):
    monkeypatch.setattr("builtins.input", lambda prompt="": "30")
    assert ask_age() == 30


def test_ask_yes_no_true_for_y(monkeypatch):
    monkeypatch.setattr("builtins.input", lambda prompt="": "y")
    assert ask_yes_no("Continue? ") is True


def test_ask_yes_no_true_for_yes_mixed_case(monkeypatch):
    monkeypatch.setattr("builtins.input", lambda prompt="": "YES")
    assert ask_yes_no("Continue? ") is True


def test_ask_yes_no_false_for_no(monkeypatch):
    monkeypatch.setattr("builtins.input", lambda prompt="": "n")
    assert ask_yes_no("Continue? ") is False


def test_greet(capsys):
    greet("Ada")
    assert capsys.readouterr().out == "Hello, Ada!\n"


def test_greeting_flow(monkeypatch, capsys):
    monkeypatch.setattr("builtins.input", lambda prompt="": "Ada")
    result = greeting_flow()
    assert result == "Ada"
    assert capsys.readouterr().out == "Hello, Ada!\n"


# ------------------------------------------------------------------ exercise06: Mutability and Identity
from exercises.week01.exercise06.solution import (
    append_and_return,
    concat_strings,
    same_object,
    equal_but_not_identical,
    default_if_none,
)


def test_append_and_return_mutates_in_place_and_is_same_object():
    original = [1, 2]
    result = append_and_return(original, 3)
    assert result == [1, 2, 3]
    assert result is original


def test_concat_strings_returns_new_object():
    a = "foo"
    b = "bar"
    result = concat_strings(a, b)
    assert result == "foobar"
    assert result is not a
    assert result is not b


def test_same_object_true_for_shared_reference():
    x = [1, 2, 3]
    y = x
    assert same_object(x, y) is True


def test_same_object_false_for_equal_but_distinct_objects():
    x = [1, 2, 3]
    y = [1, 2, 3]
    assert x == y
    assert same_object(x, y) is False


def test_equal_but_not_identical():
    l1, l2 = equal_but_not_identical()
    assert l1 == l2
    assert l1 is not l2


def test_default_if_none_uses_default_for_none():
    assert default_if_none(None, "fallback") == "fallback"


def test_default_if_none_keeps_real_value():
    assert default_if_none(0, "fallback") == 0
