"""
Tests for week06/exercise03 -- OOP I: Rectangle Properties.
Auto-generated by generate.py from generator/week06.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.week06.exercise03.solution import Rectangle


def test_area():
    assert Rectangle(4, 5).area == 20


def test_perimeter():
    assert Rectangle(4, 5).perimeter == 18


def test_is_square():
    assert Rectangle(4, 4).is_square is True
    assert Rectangle(4, 5).is_square is False


def test_width_setter_validates():
    rect = Rectangle(4, 5)
    with pytest.raises(ValueError):
        rect.width = -1


def test_height_setter_validates():
    with pytest.raises(ValueError):
        Rectangle(4, -5)


def test_changing_width_updates_area():
    rect = Rectangle(4, 5)
    rect.width = 10
    assert rect.area == 50
