"""
Tests for week09/exercise01 -- OS, JSON, Datetime, XML: os.path and pathlib Basics.
Auto-generated by generate.py from generator/week09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week09.exercise01.solution import (
    list_files,
    join_path,
    file_exists,
    list_files_pathlib,
    read_text_pathlib,
)


def test_list_files(tmp_path):
    (tmp_path / "b.txt").write_text("b")
    (tmp_path / "a.txt").write_text("a")
    assert list_files(str(tmp_path)) == ["a.txt", "b.txt"]


def test_join_path():
    assert join_path("dir", "file.txt") in ("dir/file.txt", "dir\\file.txt")


def test_file_exists(tmp_path):
    (tmp_path / "a.txt").write_text("a")
    assert file_exists(str(tmp_path / "a.txt")) is True
    assert file_exists(str(tmp_path / "missing.txt")) is False


def test_list_files_pathlib(tmp_path):
    (tmp_path / "b.txt").write_text("b")
    (tmp_path / "a.txt").write_text("a")
    assert list_files_pathlib(str(tmp_path)) == ["a.txt", "b.txt"]


def test_read_text_pathlib(tmp_path):
    path = tmp_path / "a.txt"
    path.write_text("hello")
    assert read_text_pathlib(str(path)) == "hello"
