"""
Tests for week05/exercise05 -- Files, Exceptions, Regex: Regex Named Groups.
Auto-generated by generate.py from generator/week05.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.week05.exercise05.solution import parse_log_line, parse_date, parse_key_value


def test_parse_log_line():
    assert parse_log_line("ERROR: disk full") == {"level": "ERROR", "message": "disk full"}


def test_parse_log_line_invalid_raises():
    with pytest.raises(ValueError):
        parse_log_line("not a log line")


def test_parse_date():
    result = parse_date("event happened on 2024-03-15 in the evening")
    assert result == {"year": "2024", "month": "03", "day": "15"}


def test_parse_date_none_found_raises():
    with pytest.raises(ValueError):
        parse_date("no date here")


def test_parse_key_value():
    assert parse_key_value("host=localhost") == {"key": "host", "value": "localhost"}


def test_parse_key_value_invalid_raises():
    with pytest.raises(ValueError):
        parse_key_value("not-key-value")
