"""
Tests for stage10/advanced02 -- Pandas: Apply and Dtype Optimization.
Auto-generated by generate.py from generator/stage10.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pandas as pd
from exercises.stage10.advanced02.solution import (
    add_sales_tax_column,
    categorize_sales,
    full_name_column,
    optimize_dtypes,
    set_region_product_index,
)


def test_add_sales_tax_column():
    """add_sales_tax_column adds a "total" column via .apply() on the "sales" column."""
    df = pd.DataFrame({"sales": [100, 200]})
    result = add_sales_tax_column(df, 0.1)
    assert list(result["total"]) == [110.0, 220.0]


def test_categorize_sales():
    """categorize_sales adds a "tier" column via .apply(_categorize_amount)."""
    df = pd.DataFrame({"sales": [50, 150, 350]})
    result = categorize_sales(df)
    assert list(result["tier"]) == ["low", "medium", "high"]


def test_full_name_column_uses_row_wise_apply():
    """full_name_column must use df.apply(..., axis=1) -- one call per ROW, not per column."""
    df = pd.DataFrame({"first": ["Ada", "Grace"], "last": ["Lovelace", "Hopper"]})
    result = full_name_column(df)
    assert list(result["full_name"]) == ["Ada Lovelace", "Grace Hopper"]


def test_optimize_dtypes():
    """optimize_dtypes casts the "region" column to the "category" dtype."""
    df = pd.DataFrame({"region": ["east", "west", "east"]})
    result = optimize_dtypes(df)
    assert str(result["region"].dtype) == "category"


def test_set_region_product_index_is_multi_indexed():
    """set_region_product_index uses df.set_index([...]) to build a MultiIndex explicitly."""
    df = pd.DataFrame({"region": ["east", "west"], "product": ["A", "B"], "sales": [1, 2]})
    result = set_region_product_index(df)
    assert isinstance(result.index, pd.MultiIndex)
    assert result.loc[("east", "A"), "sales"] == 1
