"""
Tests for week10/exercise05 -- Pandas: Apply and Dtype Optimization.
Auto-generated by generate.py from generator/week10.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pandas as pd
from exercises.week10.exercise05.solution import (
    add_sales_tax_column,
    categorize_sales,
    full_name_column,
    optimize_dtypes,
    set_region_product_index,
)


def test_add_sales_tax_column():
    df = pd.DataFrame({"sales": [100, 200]})
    result = add_sales_tax_column(df, 0.1)
    assert list(result["total"]) == [110.0, 220.0]


def test_categorize_sales():
    df = pd.DataFrame({"sales": [50, 150, 350]})
    result = categorize_sales(df)
    assert list(result["tier"]) == ["low", "medium", "high"]


def test_full_name_column():
    df = pd.DataFrame({"first": ["Ada", "Grace"], "last": ["Lovelace", "Hopper"]})
    result = full_name_column(df)
    assert list(result["full_name"]) == ["Ada Lovelace", "Grace Hopper"]


def test_optimize_dtypes():
    df = pd.DataFrame({"region": ["east", "west", "east"]})
    result = optimize_dtypes(df)
    assert str(result["region"].dtype) == "category"


def test_set_region_product_index():
    df = pd.DataFrame({"region": ["east", "west"], "product": ["A", "B"], "sales": [1, 2]})
    result = set_region_product_index(df)
    assert isinstance(result.index, pd.MultiIndex)
    assert result.loc[("east", "A"), "sales"] == 1
