"""
Tests for week03/exercise08 -- Functions: Generators.
Auto-generated by generate.py from generator/week03.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week03.exercise08.solution import (
    count_up_to,
    evens_only,
    infinite_counter,
    take,
)


def test_count_up_to():
    assert list(count_up_to(5)) == [1, 2, 3, 4, 5]


def test_count_up_to_is_lazy_generator():
    gen = count_up_to(3)
    assert hasattr(gen, "__next__")
    assert next(gen) == 1
    assert next(gen) == 2


def test_evens_only():
    assert list(evens_only([1, 2, 3, 4, 5, 6])) == [2, 4, 6]


def test_infinite_counter_via_take():
    assert take(infinite_counter(), 5) == [0, 1, 2, 3, 4]


def test_take_with_finite_generator():
    assert take(count_up_to(100), 3) == [1, 2, 3]
