"""
Tests for week01/exercise03 -- Python Fundamentals: Type Inspector.
Auto-generated by generate.py from generator/week01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week01.exercise03.solution import (
    describe_value,
    print_type_report,
    classify_values,
)


def test_describe_value_none():
    assert describe_value(None) == "None (the absence of a value)"


def test_describe_value_int():
    assert describe_value(5) == "5 is a int"


def test_describe_value_str():
    assert describe_value("hi") == "'hi' is a str"


def test_print_type_report(capsys):
    print_type_report(5)
    assert capsys.readouterr().out == "5 is a int\n"


def test_classify_values_separates_bool_from_int():
    result = classify_values([1, 2, True, False, 3.5, "x", None])
    assert result["ints"] == [1, 2]
    assert result["bools"] == [True, False]
    assert result["floats"] == [3.5]
    assert result["strs"] == ["x"]
    assert result["nones"] == [None]
