"""
Tests for stage01/advanced02 -- Python Fundamentals: Big Numbers and String Identity.
Auto-generated by generate.py from generator/stage01.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import exercises.stage01.advanced02.solution as solution


def test_huge_power_has_arbitrary_precision():
    assert solution.huge_power == 97 ** 42
    assert solution.huge_power_digit_count > 19  # bigger than any 64-bit int could hold


def test_small_int_caching():
    assert solution.small_ints_share_identity is True


def test_large_ints_not_guaranteed_cached():
    assert solution.large_int_from_literal == solution.large_int_from_conversion
    assert solution.large_ints_share_identity is False


def test_string_literal_interning():
    assert solution.string_literals_share_identity is True


def test_runtime_built_string_not_interned():
    assert solution.string_literal_a == solution.string_built_at_runtime
    assert solution.runtime_string_shares_identity is False
