"""
Tests for week09/exercise07 -- OS, JSON, Datetime, XML: XML with ElementTree.
Auto-generated by generate.py from generator/week09.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import xml.etree.ElementTree as ET
from exercises.week09.exercise07.solution import (
    parse_xml_titles,
    parse_xml_string_titles,
    count_elements,
    get_attribute_values,
    build_simple_xml,
)

LIBRARY_XML = (
    '<library>'
    '<book id="1"><title>Dune</title></book>'
    '<book id="2"><title>Foundation</title></book>'
    "</library>"
)


def test_parse_xml_titles(tmp_path):
    path = tmp_path / "library.xml"
    path.write_text(LIBRARY_XML)
    assert parse_xml_titles(str(path)) == ["Dune", "Foundation"]


def test_parse_xml_string_titles():
    assert parse_xml_string_titles(LIBRARY_XML) == ["Dune", "Foundation"]


def test_count_elements(tmp_path):
    path = tmp_path / "library.xml"
    path.write_text(LIBRARY_XML)
    assert count_elements(str(path), "book") == 2


def test_get_attribute_values(tmp_path):
    path = tmp_path / "library.xml"
    path.write_text(LIBRARY_XML)
    assert get_attribute_values(str(path), "book", "id") == ["1", "2"]


def test_build_simple_xml():
    xml_string = build_simple_xml(["a", "b"])
    root = ET.fromstring(xml_string)
    items = root.findall("item")
    assert [el.text for el in items] == ["a", "b"]
