"""
Tests for week07/exercise05 -- OOP II: Mixins and Protocols.
Auto-generated by generate.py from generator/week07.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.week07.exercise05.solution import (
    LoggingMixin,
    SerializableMixin,
    Widget,
    SupportsArea,
    Coin,
    total_area,
    supports_area,
)


def test_widget_uses_both_mixins():
    w = Widget("gadget")
    assert w.log("created") == "[Widget] created"
    assert w.to_dict() == {"name": "gadget"}


def test_widget_is_instance_of_both_mixins():
    w = Widget("gadget")
    assert isinstance(w, LoggingMixin)
    assert isinstance(w, SerializableMixin)


def test_total_area():
    assert round(total_area([Coin(1), Coin(2)]), 2) == round(3.14159 + 12.56636, 2)


def test_supports_area_structural_typing():
    assert supports_area(Coin(1)) is True
    assert supports_area("not a shape") is False


def test_coin_never_inherits_from_supports_area():
    assert SupportsArea not in Coin.__bases__
