"""
Tests for stage02/exercise07 -- Control Flow: The else Clause on Loops.
Auto-generated by generate.py from generator/stage02.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage02.exercise07.solution import (
    contains_value,
    all_positive,
    find_first_negative_index,
    retry_until_success,
    first_positive_index,
)


def test_contains_value_found():
    assert contains_value([1, 2, 3], 2) is True


def test_contains_value_not_found():
    assert contains_value([1, 2, 3], 9) is False


def test_all_positive_true():
    assert all_positive([1, 2, 3]) is True


def test_all_positive_false():
    assert all_positive([1, -2, 3]) is False


def test_find_first_negative_index_found():
    assert find_first_negative_index([1, 2, -3, 4]) == 2


def test_find_first_negative_index_none():
    assert find_first_negative_index([1, 2, 3]) == -1


def test_retry_until_success_true():
    assert retry_until_success([False, False, True]) is True


def test_retry_until_success_false():
    assert retry_until_success([False, False]) is False


def test_first_positive_index_found():
    assert first_positive_index([-1, -2, 3, 4]) == 2


def test_first_positive_index_none():
    assert first_positive_index([-1, -2]) == -1
