"""
Tests for stage13/exercise03 -- Local API Endpoints: Dependency Injection.
Auto-generated by generate.py from generator/stage13.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from fastapi.testclient import TestClient
from exercises.stage13.exercise03.solution import app as di_app

di_client = TestClient(di_app)


def test_paginated_defaults():
    assert di_client.get("/paginated").json() == {"page": 1, "size": 10}


def test_paginated_custom_values():
    assert di_client.get("/paginated?page=3&size=20").json() == {"page": 3, "size": 20}


def test_status_depends_on_get_db():
    assert di_client.get("/status").json() == {"connected": True}


def test_protected_without_token():
    assert di_client.get("/protected").json() == {"error": "unauthorized"}


def test_protected_with_correct_token():
    response = di_client.get("/protected?token=secret")
    assert response.json() == {"data": "secret data"}
