"""
Tests for week11/exercise05 -- OpenCV: Edges and Contours.
Auto-generated by generate.py from generator/week11.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import cv2
import numpy as np
from exercises.week11.exercise05.solution import (
    detect_edges,
    detect_edges_default,
    count_edge_pixels,
    find_contours,
    count_contours,
    largest_contour_area,
)


def _square_image():
    image = np.zeros((50, 50), dtype=np.uint8)
    cv2.rectangle(image, (10, 10), (30, 30), 255, -1)
    return image


def test_detect_edges_finds_something():
    edges = detect_edges(_square_image(), 50, 150)
    assert edges.sum() > 0


def test_detect_edges_default():
    edges = detect_edges_default(_square_image())
    assert edges.shape == (50, 50)


def test_count_edge_pixels():
    assert count_edge_pixels(_square_image(), 50, 150) > 0


def test_find_and_count_contours():
    contours = find_contours(_square_image())
    assert len(contours) == 1
    assert count_contours(_square_image()) == 1


def test_largest_contour_area():
    area = largest_contour_area(_square_image())
    assert 300 < area < 500
