"""
Aggregated tests for week04 -- Data Structures.
Auto-generated by generate.py from generator/week04.py -- edit that file, not this one, then re-run `python generate.py`.
"""


# ------------------------------------------------------------------ exercise01: List and Tuple Basics
from exercises.week04.exercise01.solution import (
    build_shopping_list,
    unique_sorted,
    sort_in_place,
    as_tuple_pairs,
    zip_and_sum,
    label_each,
    count_items,
)


def test_build_shopping_list():
    assert build_shopping_list(["milk", "eggs"]) == ["milk", "eggs"]


def test_unique_sorted():
    assert unique_sorted([3, 1, 2, 1, 3]) == [1, 2, 3]


def test_sort_in_place():
    items = [3, 1, 2]
    result = sort_in_place(items)
    assert result is None
    assert items == [1, 2, 3]


def test_as_tuple_pairs():
    assert as_tuple_pairs(["a", "b"], [1, 2]) == [("a", 1), ("b", 2)]


def test_zip_and_sum():
    assert zip_and_sum([1, 2, 3], [10, 20, 30]) == [11, 22, 33]


def test_label_each():
    assert label_each(["a", "b"]) == ["0:a", "1:b"]


def test_count_items():
    assert count_items([1, 2, 3]) == 3


# ------------------------------------------------------------------ exercise02: Dict and Set Operations
from exercises.week04.exercise02.solution import (
    word_lengths,
    index_lookup,
    numbered_pairs,
    pair_and_dict,
    common_elements,
    unique_to_first,
    all_elements,
)


def test_word_lengths():
    assert word_lengths(["a", "bb"]) == {"a": 1, "bb": 2}


def test_index_lookup():
    assert index_lookup(["a", "b"]) == {"a": 0, "b": 1}


def test_numbered_pairs():
    assert numbered_pairs(["a", "b"]) == [(0, "a"), (1, "b")]


def test_pair_and_dict():
    assert pair_and_dict(["x", "y"], [1, 2]) == {"x": 1, "y": 2}


def test_common_elements():
    assert common_elements({1, 2, 3}, {2, 3, 4}) == {2, 3}


def test_unique_to_first():
    assert unique_to_first({1, 2, 3}, {2, 3, 4}) == {1}


def test_all_elements():
    assert all_elements({1, 2}, {2, 3}) == {1, 2, 3}


# ------------------------------------------------------------------ exercise03: Comprehensions
from exercises.week04.exercise03.solution import squares, evens_squared_dict, flatten


def test_squares():
    assert squares(5) == [0, 1, 4, 9, 16]


def test_evens_squared_dict():
    assert evens_squared_dict(6) == {0: 0, 2: 4, 4: 16}


def test_flatten():
    assert flatten([[1, 2], [3, 4], [5]]) == [1, 2, 3, 4, 5]


# ------------------------------------------------------------------ exercise04: Collections Toolbox
from exercises.week04.exercise04.solution import (
    group_by_first_letter,
    count_occurrences,
    most_common_n,
    sliding_window_last_n,
    rotate_queue,
)


def test_group_by_first_letter():
    result = group_by_first_letter(["apple", "avocado", "banana", "cherry"])
    assert result == {"a": ["apple", "avocado"], "b": ["banana"], "c": ["cherry"]}


def test_count_occurrences():
    assert count_occurrences(["a", "b", "a", "c", "a"]) == {"a": 3, "b": 1, "c": 1}


def test_most_common_n():
    assert most_common_n(["a", "b", "a", "c", "a", "b"], 2) == [("a", 3), ("b", 2)]


def test_sliding_window_last_n():
    assert sliding_window_last_n([1, 2, 3, 4, 5], 3) == [3, 4, 5]


def test_rotate_queue():
    assert rotate_queue([1, 2, 3, 4, 5], 2) == [4, 5, 1, 2, 3]


# ------------------------------------------------------------------ exercise05: Dataclasses
import pytest
from exercises.week04.exercise05.solution import Point, FrozenPoint, TaggedItem


def test_point_distance_and_eq():
    assert Point(3, 4).distance_from_origin() == 5.0
    assert Point(1, 2) == Point(1, 2)


def test_point_is_not_hashable():
    with pytest.raises(TypeError):
        hash(Point(1, 2))


def test_frozen_point_distance_and_eq():
    assert FrozenPoint(3, 4).distance_from_origin() == 5.0
    assert FrozenPoint(1, 2) == FrozenPoint(1, 2)


def test_frozen_point_is_hashable():
    points = {FrozenPoint(1, 2), FrozenPoint(1, 2), FrozenPoint(3, 4)}
    assert len(points) == 2


def test_tagged_item_add_tag():
    item = TaggedItem("shirt")
    item.add_tag("clothing")
    assert item.tags == ["clothing"]


def test_tagged_item_default_factory_is_independent_per_instance():
    item1 = TaggedItem("shirt")
    item2 = TaggedItem("shoe")
    item1.add_tag("clothing")
    assert item2.tags == []


# ------------------------------------------------------------------ exercise06: Records and Hashability
import pytest
from exercises.week04.exercise06.solution import (
    Coordinate,
    make_coordinate,
    SimpleFraction,
    dedupe_preserving_order,
)


def test_make_coordinate():
    c = make_coordinate(1, 2)
    assert c == Coordinate(1, 2)
    assert c.x == 1 and c.y == 2


def test_simple_fraction_reduces():
    assert SimpleFraction(2, 4) == SimpleFraction(1, 2)


def test_simple_fraction_normalizes_negative_denominator():
    assert SimpleFraction(1, -2) == SimpleFraction(-1, 2)


def test_simple_fraction_zero_denominator_raises():
    with pytest.raises(ZeroDivisionError):
        SimpleFraction(1, 0)


def test_simple_fraction_is_hashable():
    fractions = {SimpleFraction(1, 2), SimpleFraction(2, 4), SimpleFraction(1, 3)}
    assert len(fractions) == 2


def test_dedupe_preserving_order_with_hashable_records():
    items = [
        SimpleFraction(1, 2),
        SimpleFraction(2, 4),
        Coordinate(1, 1),
        SimpleFraction(1, 3),
        Coordinate(1, 1),
    ]
    result = dedupe_preserving_order(items)
    assert result == [SimpleFraction(1, 2), Coordinate(1, 1), SimpleFraction(1, 3)]


def test_dedupe_preserving_order_with_plain_values():
    assert dedupe_preserving_order([1, 2, 1, 3, 2]) == [1, 2, 3]
