"""
Tests for week08/exercise07 -- The Python Data Model: Context Managers as a Protocol.
Auto-generated by generate.py from generator/week08.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.week08.exercise07.solution import ResourceGuard, Transaction, SuppressAll


def test_resource_guard_active_during_block():
    guard = ResourceGuard()
    with guard:
        assert guard.active is True
    assert guard.active is False


def test_transaction_commits_on_success():
    with Transaction() as tx:
        pass
    assert tx.committed is True
    assert tx.rolled_back is False


def test_transaction_rolls_back_on_exception():
    with pytest.raises(RuntimeError):
        with Transaction() as tx:
            raise RuntimeError("boom")
    assert tx.rolled_back is True
    assert tx.committed is False


def test_suppress_all_swallows_any_exception():
    with SuppressAll():
        raise ValueError("this never propagates")
    with SuppressAll():
        raise KeyError("neither does this")


def test_no_special_base_class():
    assert ResourceGuard.__bases__ == (object,)
    assert Transaction.__bases__ == (object,)
    assert SuppressAll.__bases__ == (object,)
