"""
Tests for stage04/tier3_advanced02 -- Data Structures: Hashable Records: Frozen Dataclasses and Manual __hash__.
Auto-generated by generate.py from generator/stage04.py -- edit that file, not this one, then re-run `python generate.py`.
"""

import pytest
from exercises.stage04.tier3_advanced02.solution import (
    Point,
    FrozenPoint,
    SimpleFraction,
    dedupe_preserving_order,
)


def test_point_distance():
    """Point.distance_from_origin() == (x**2 + y**2) ** 0.5."""
    assert Point(3, 4).distance_from_origin() == 5.0


def test_point_is_not_hashable():
    """Point is a plain (mutable) dataclass with eq=True -- dataclass sets __hash__ = None, so hash() must raise TypeError."""
    with pytest.raises(TypeError):
        hash(Point(1, 2))


def test_frozen_point_distance_and_is_hashable():
    """FrozenPoint.distance_from_origin() works, and frozen=True gives it a working auto-generated __hash__."""
    assert FrozenPoint(3, 4).distance_from_origin() == 5.0
    points = {FrozenPoint(1, 2), FrozenPoint(1, 2), FrozenPoint(3, 4)}
    assert len(points) == 2


def test_simple_fraction_eq_compares_reduced_values():
    """SimpleFraction.__eq__ must compare reduced numerator/denominator, not object identity."""
    assert SimpleFraction(2, 4) == SimpleFraction(1, 2)
    assert SimpleFraction(1, 2) != SimpleFraction(1, 3)


def test_simple_fraction_is_hashable_via_hand_written_hash():
    """SimpleFraction.__hash__ must be written by hand (hash((numerator, denominator))) -- without it, defining __eq__ alone makes it unhashable."""
    fractions = {SimpleFraction(1, 2), SimpleFraction(2, 4), SimpleFraction(1, 3)}
    assert len(fractions) == 2


def test_dedupe_preserving_order_relies_on_hashability():
    """dedupe_preserving_order (dict.fromkeys) only works because SimpleFraction/FrozenPoint are both hashable."""
    items = [
        SimpleFraction(1, 2),
        SimpleFraction(2, 4),
        FrozenPoint(1, 1),
        SimpleFraction(1, 3),
        FrozenPoint(1, 1),
    ]
    result = dedupe_preserving_order(items)
    assert result == [SimpleFraction(1, 2), FrozenPoint(1, 1), SimpleFraction(1, 3)]
    assert len(result) == 3


def test_dedupe_preserving_order_with_plain_values():
    """dedupe_preserving_order also works on ordinary hashable values like ints."""
    assert dedupe_preserving_order([1, 2, 1, 3, 2]) == [1, 2, 3]
