"""
Tests for stage07/advanced02 -- OOP II: Protocol Structural Typing.
Auto-generated by generate.py from generator/stage07.py -- edit that file, not this one, then re-run `python generate.py`.
"""

from exercises.stage07.advanced02.solution import SupportsArea, Coin, total_area, supports_area


def test_total_area():
    """total_area == sum(s.area() for s in shapes)."""
    assert round(total_area([Coin(1), Coin(2)]), 2) == round(3.14159 + 12.56636, 2)


def test_supports_area_structural_typing():
    """supports_area(Coin(...)) is True via structural typing, despite Coin never inheriting from SupportsArea."""
    assert supports_area(Coin(1)) is True
    assert supports_area("not a shape") is False


def test_coin_never_inherits_from_supports_area():
    """Coin must satisfy SupportsArea purely structurally -- SupportsArea must not appear in its base classes."""
    assert SupportsArea not in Coin.__bases__
