// Glossary entries for every clickable badge in the reference (data.js).
// Keyed by the exact badge text. Each entry: { category, summary, usage, example?, related? }
// category is one of: keyword, method, dunder, module, concept, theory
// "example" is optional runnable-looking Python; omit it for pure-theory entries
// where a snippet wouldn't add anything. "related" is an optional list of other
// glossary keys worth a look next (rendered as clickable chips in the drawer).

const GLOSSARY_CATEGORY_LABELS = {
  keyword: "Keyword & syntax",
  method: "Method / attribute",
  dunder: "Special method (dunder)",
  module: "Module",
  concept: "Concept",
  theory: "Theory & internals"
};

const GLOSSARY = {

/* ---------------------------------------------------------------- */
/* Topic 1 — Python Fundamentals                                     */
/* ---------------------------------------------------------------- */
"int": { category: "keyword", summary: "The built-in arbitrary-precision integer type.", usage: "Use for whole numbers; Python ints grow automatically, they never overflow.", example: "x = 7\ny: int = 1_000_000\nprint(type(x))  # <class 'int'>" },
"float": { category: "keyword", summary: "The built-in double-precision (IEEE-754) floating-point type.", usage: "Use for numbers with a fractional part; be aware of rounding error (see IEEE-754 floating point).", example: "pi = 3.14159\nprint(0.1 + 0.2)  # 0.30000000000000004", related: ["IEEE-754 floating point"] },
"str": { category: "keyword", summary: "The built-in immutable text type (a sequence of Unicode characters).", usage: "Create with quotes; use f-strings for interpolation and slicing for substrings.", example: "name = \"Ada\"\ngreeting = f\"Hello, {name}!\"" },
"bool": { category: "keyword", summary: "The built-in boolean type; a subclass of int with exactly two instances, True and False.", usage: "Result of comparisons and logical expressions; anything can be tested for truthiness with bool(x).", example: "print(bool(0), bool(\"\"), bool([1]))  # False False True" },
"None": { category: "keyword", summary: "The singleton value representing \"no value\".", usage: "Used as a default placeholder, a function's implicit return value, or a sentinel; compare with `is None`, not `== None`.", example: "def f():\n    pass\n\nprint(f() is None)  # True" },
"True": { category: "keyword", summary: "The boolean literal for truth; one of the two bool instances.", usage: "Used directly in conditions, or as the result of a comparison.", example: "print(1 == 1)  # True" },
"False": { category: "keyword", summary: "The boolean literal for falsehood; the other bool instance.", usage: "Used directly in conditions, or as the result of a comparison.", example: "print(1 == 2)  # False" },
"print()": { category: "method", summary: "Writes text (plus a trailing newline by default) to standard output.", usage: "The most common way to see a value while learning or debugging; accepts multiple comma-separated arguments and keyword args like sep= and end=.", example: "print(\"a\", \"b\", sep=\"-\")  # a-b" },
"input()": { category: "method", summary: "Reads a line of text typed by the user from standard input, returned as a str.", usage: "Pass an optional prompt string; remember to convert the result with int()/float() if you need a number.", example: "name = input(\"Your name: \")\nage = int(input(\"Your age: \"))" },
"type()": { category: "method", summary: "Returns the type (class) of an object.", usage: "Use for quick introspection; prefer isinstance() for actual type checks since it also handles subclasses.", example: "print(type(3))       # <class 'int'>\nprint(type(3) is int)  # True" },
"isinstance()": { category: "method", summary: "Checks whether an object is an instance of a class (or a tuple of classes), including subclasses.", usage: "The idiomatic way to branch on type; prefer it over `type(x) == SomeClass`.", example: "if isinstance(x, (int, float)):\n    print(\"numeric\")" },
"and": { category: "keyword", summary: "Logical AND; short-circuits and returns one of its operands, not necessarily a bool.", usage: "Combine boolean conditions, or use the short-circuit behavior for a compact default (`x and y`).", example: "print(0 and \"never seen\")  # 0\nprint(2 and \"seen\")        # seen", related: ["short-circuit evaluation"] },
"or": { category: "keyword", summary: "Logical OR; short-circuits and returns the first truthy operand (or the last one).", usage: "Combine boolean conditions, or use `x or default` to fall back to a default value.", example: "name = user_input or \"Guest\"", related: ["short-circuit evaluation"] },
"not": { category: "keyword", summary: "Logical negation; converts its operand's truthiness and flips it.", usage: "Negate a condition, e.g. `if not items:` to check for an empty list.", example: "print(not [])   # True\nprint(not [1])  # False" },
"is": { category: "keyword", summary: "Identity comparison — true only if both sides are the exact same object in memory.", usage: "Use for `is None` / `is True` checks, not for comparing values (use == for that).", example: "a = [1]\nb = [1]\nprint(a == b, a is b)  # True False", related: ["identity vs equality"] },
"in": { category: "keyword", summary: "Membership test operator; also used to introduce the iterable in a for-loop.", usage: "Checks containment for sequences/sets/dicts (`x in container`), or drives iteration (`for x in container:`).", example: "print(3 in [1, 2, 3])  # True\nfor ch in \"abc\":\n    print(ch)" },
"x: int = 5": { category: "keyword", summary: "A variable annotation: attaches a type hint to a variable assignment.", usage: "Documents the intended type for readers and tools like mypy; Python itself does not enforce it at runtime.", example: "count: int = 5\nname: str = \"Ada\"", related: ["type hints"] },
"type hints": { category: "concept", summary: "Optional annotations (PEP 484) that document the expected types of variables, parameters, and return values.", usage: "Add them for readability and static analysis (mypy/pyright); FastAPI (Topic 13) even uses them at runtime for validation.", example: "def add(a: int, b: int) -> int:\n    return a + b" },
"mutability vs immutability": { category: "concept", summary: "Whether an object's contents can change after creation (mutable: list/dict/set) or not (immutable: int/str/tuple/frozenset).", usage: "Immutable objects are safe to share and hash as dict keys; mutable ones are not hashable by default and can be changed in place, which is the source of the mutable-default-argument bug.", related: ["hashability", "mutable default argument bug"] },
"identity vs equality": { category: "concept", summary: "`is` compares object identity (same object in memory); `==` compares value equality (calls __eq__).", usage: "Use `is` only for singletons (None/True/False); use `==` for everything else.", related: ["is", "__eq__"] },
"small-integer caching": { category: "theory", summary: "CPython pre-creates and reuses integer objects for -5..256, so small ints of the same value are literally the same object.", usage: "Explains why `a = 5; b = 5; a is b` is True but the same trick with 1000 usually isn't — never rely on this, always compare ints with ==." },
"string interning": { category: "theory", summary: "CPython may reuse a single object for identical string literals (especially identifier-like ones) instead of allocating a new one each time.", usage: "Explains surprising `is` results between string literals; still compare strings with == in real code." },
"IEEE-754 floating point": { category: "theory", summary: "The binary floating-point standard Python's float type uses; most decimal fractions have no exact binary representation.", usage: "Never compare floats with ==; use math.isclose() or round to a fixed number of digits.", example: "import math\nprint(math.isclose(0.1 + 0.2, 0.3))  # True" },

/* ---------------------------------------------------------------- */
/* Topic 2 — Control Flow                                            */
/* ---------------------------------------------------------------- */
"if": { category: "keyword", summary: "Starts a conditional branch, executing its block only when the condition is truthy.", usage: "Pair with elif/else for multi-way branching.", example: "if age >= 18:\n    print(\"adult\")" },
"elif": { category: "keyword", summary: "An additional condition checked only if the preceding if/elif was false.", usage: "Chain as many as needed instead of nesting if-statements.", example: "if score >= 90:\n    grade = \"A\"\nelif score >= 80:\n    grade = \"B\"" },
"else": { category: "keyword", summary: "The fallback branch run when no preceding if/elif matched (or, on a loop, when it finished without break).", usage: "Terminates an if/elif chain, or pairs with for/while for a for...else pattern.", related: ["for...else / while...else"] },
"while": { category: "keyword", summary: "Repeats a block as long as its condition stays truthy.", usage: "Use when the number of iterations isn't known ahead of time (unlike for + range()).", example: "n = 3\nwhile n > 0:\n    print(n)\n    n -= 1" },
"for": { category: "keyword", summary: "Iterates over any iterable, binding each element to a loop variable in turn.", usage: "The idiomatic way to loop in Python — prefer it over manual index/while loops.", example: "for word in [\"a\", \"b\"]:\n    print(word)", related: ["iterator protocol (iter/next)"] },
"range()": { category: "method", summary: "Produces a lazy sequence of integers, commonly used to loop a fixed number of times.", usage: "range(stop), range(start, stop), or range(start, stop, step) — it doesn't build a list, it computes values on demand.", example: "for i in range(3):\n    print(i)  # 0 1 2" },
"break": { category: "keyword", summary: "Immediately exits the nearest enclosing for/while loop.", usage: "Use to stop early once you've found what you're looking for; skips any loop `else` clause.", example: "for x in items:\n    if x == target:\n        break" },
"continue": { category: "keyword", summary: "Skips the rest of the current loop iteration and moves to the next one.", usage: "Use to skip items that don't need processing without nesting the rest of the loop body.", example: "for x in nums:\n    if x % 2 == 0:\n        continue\n    print(x)" },
"pass": { category: "keyword", summary: "A no-op statement — does literally nothing.", usage: "Use as a placeholder wherever a statement is syntactically required, e.g. an empty function/class body while stubbing code.", example: "def todo():\n    pass" },
"zip()": { category: "method", summary: "Pairs up elements from two or more iterables into tuples, stopping at the shortest one.", usage: "Iterate over several sequences in lockstep instead of indexing manually.", example: "for name, age in zip(names, ages):\n    print(name, age)" },
"enumerate()": { category: "method", summary: "Wraps an iterable to also yield a running index alongside each element.", usage: "Use instead of manual `range(len(x))` indexing when you need both index and value.", example: "for i, ch in enumerate(\"ab\"):\n    print(i, ch)  # 0 a / 1 b" },
"short-circuit evaluation": { category: "concept", summary: "`and`/`or` stop evaluating as soon as the result is determined, and return an operand rather than a plain bool.", usage: "Lets you write compact guards like `obj and obj.value` to avoid a None error.", related: ["and", "or"] },
"truthiness": { category: "concept", summary: "Every object has an implicit boolean value used in conditions, decided by __bool__ or, failing that, __len__ == 0.", usage: "Lets you write `if items:` instead of `if len(items) > 0:`.", related: ["__bool__"] },
"ternary expression": { category: "concept", summary: "A single-expression conditional: `value_if_true if condition else value_if_false`.", usage: "Use for short conditional assignments where a full if/else statement would be overkill.", example: "label = \"even\" if n % 2 == 0 else \"odd\"" },
"for...else / while...else": { category: "concept", summary: "An else clause on a loop that runs only if the loop finished without hitting break.", usage: "Classic use: searching a list and running \"not found\" logic in the else branch.", example: "for x in items:\n    if x == target:\n        break\nelse:\n    print(\"not found\")" },
"iterator protocol (iter/next)": { category: "theory", summary: "`for` calls iter(obj) to get an iterator, then calls next() on it repeatedly until StopIteration is raised.", usage: "Understanding this lets you write your own iterable classes (see __iter__/__next__ in Topic 8).", related: ["__iter__", "StopIteration"] },
"StopIteration": { category: "theory", summary: "The exception an iterator's __next__ raises to signal it is exhausted.", usage: "`for` loops catch this automatically; you only see it directly if you call next() manually past the end.", example: "it = iter([1])\nnext(it)\nnext(it)  # raises StopIteration" },

/* ---------------------------------------------------------------- */
/* Topic 3 — Functions                                               */
/* ---------------------------------------------------------------- */
"def": { category: "keyword", summary: "Defines a function (or method).", usage: "Followed by a name, parameter list, optional return type hint, and an indented body.", example: "def square(n: int) -> int:\n    return n * n" },
"return": { category: "keyword", summary: "Exits a function immediately, optionally sending a value back to the caller.", usage: "A function with no return (or a bare `return`) implicitly returns None.", example: "def add(a, b):\n    return a + b" },
"->": { category: "keyword", summary: "Introduces a function's return type hint.", usage: "Purely documentation for humans and type checkers; Python doesn't enforce it at runtime.", example: "def name() -> str:\n    return \"Ada\"" },
"*args": { category: "keyword", summary: "Collects any extra positional arguments into a tuple named args.", usage: "Use when a function should accept a variable number of positional arguments.", example: "def total(*args):\n    return sum(args)\n\ntotal(1, 2, 3)  # 6" },
"**kwargs": { category: "keyword", summary: "Collects any extra keyword arguments into a dict named kwargs.", usage: "Use when a function should accept arbitrary named options, often to forward them to another call.", example: "def greet(**kwargs):\n    print(kwargs)\n\ngreet(name=\"Ada\")  # {'name': 'Ada'}" },
"lambda": { category: "keyword", summary: "Creates a small anonymous function limited to a single expression.", usage: "Handy as a short throwaway callback, e.g. a sort key; for anything longer, use a real def.", example: "pairs.sort(key=lambda p: p[1])" },
"global": { category: "keyword", summary: "Declares that an assignment inside a function should target the module-level (global) variable, not create a local one.", usage: "Needed only when you intend to reassign a global from inside a function; reading a global never requires it.", example: "counter = 0\ndef increment():\n    global counter\n    counter += 1" },
"nonlocal": { category: "keyword", summary: "Declares that an assignment inside a nested function should target a variable in an enclosing (but not global) scope.", usage: "Used inside closures when the inner function needs to mutate a variable from the outer function.", example: "def make_counter():\n    n = 0\n    def inc():\n        nonlocal n\n        n += 1\n        return n\n    return inc", related: ["closures"] },
"yield": { category: "keyword", summary: "Pauses a function and produces a value, turning it into a generator function.", usage: "Use for lazily producing a sequence of values one at a time instead of building a whole list in memory.", example: "def countdown(n):\n    while n > 0:\n        yield n\n        n -= 1" },
"functools.wraps()": { category: "method", summary: "A decorator-writing helper that copies a wrapped function's name/docstring/metadata onto the wrapper.", usage: "Always apply it inside your own decorators so introspection tools and debuggers still see the original function's identity.", example: "import functools\n\ndef logged(fn):\n    @functools.wraps(fn)\n    def wrapper(*a, **kw):\n        return fn(*a, **kw)\n    return wrapper", related: ["decorators"] },
"functools.lru_cache()": { category: "method", summary: "A decorator that memoizes a function's results, caching by argument values.", usage: "Speeds up pure functions called repeatedly with the same arguments (e.g. recursive Fibonacci).", example: "import functools\n\n@functools.lru_cache\ndef fib(n):\n    return n if n < 2 else fib(n-1) + fib(n-2)" },
"functools.partial()": { category: "method", summary: "Builds a new callable with some arguments of an existing function pre-filled.", usage: "Use to specialize a general function for a specific call site without writing a wrapper by hand.", example: "import functools\ndouble = functools.partial(lambda a, b: a * b, 2)\ndouble(5)  # 10" },
"closures": { category: "concept", summary: "A nested function that remembers variables from its enclosing function's scope even after that function has returned.", usage: "The mechanism behind function factories and simple decorators.", related: ["nonlocal", "decorators"] },
"decorators": { category: "concept", summary: "A function that takes a function (or class) and returns a modified/wrapped version of it, applied with @ syntax.", usage: "Use to add cross-cutting behavior (logging, caching, validation) without changing the original function's body.", example: "@functools.lru_cache\ndef expensive(n):\n    ...", related: ["closures", "functools.wraps()"] },
"keyword-only arguments": { category: "concept", summary: "Parameters that must be passed by name, declared after a bare * in the parameter list.", usage: "Use to force clarity at call sites for options that would be confusing as positional args.", example: "def connect(host, *, timeout=5):\n    ...\n\nconnect(\"example.com\", timeout=10)" },
"positional-only parameters": { category: "concept", summary: "Parameters that can only be passed positionally, declared before a bare / in the parameter list.", usage: "Use to lock down a function's public call signature so the parameter name can change freely later.", example: "def pow2(x, /):\n    return x * x" },
"LEGB scope resolution": { category: "theory", summary: "Name lookup order: Local, then Enclosing function, then Global (module), then Built-in.", usage: "Explains why a name inside a function resolves to the nearest enclosing definition, and why `global`/`nonlocal` are needed to reassign outer names." },
"mutable default argument bug": { category: "theory", summary: "A default argument value is evaluated once, at def-time, and reused on every call — so a mutable default (like []) accumulates state across calls.", usage: "Fix it by defaulting to None and creating the mutable object inside the function body.", example: "def add(item, bucket=None):\n    if bucket is None:\n        bucket = []\n    bucket.append(item)\n    return bucket" },
"no tail-call optimization": { category: "theory", summary: "CPython does not optimize tail-recursive calls, so deep recursion consumes stack frames and can hit RecursionError.", usage: "For deep or unbounded recursion, prefer an iterative loop or increase sys.setrecursionlimit() only as a last resort." },

/* ---------------------------------------------------------------- */
/* Topic 4 — Data Structures                                         */
/* ---------------------------------------------------------------- */
"list": { category: "keyword", summary: "A built-in mutable, ordered sequence type.", usage: "Use for collections you'll modify (append/remove/sort); indexable and sliceable.", example: "nums = [1, 2, 3]\nnums.append(4)" },
"tuple": { category: "keyword", summary: "A built-in immutable, ordered sequence type.", usage: "Use for fixed-size records or as hashable composite dict keys/set members.", example: "point = (3, 4)\nx, y = point" },
"dict": { category: "keyword", summary: "A built-in mutable mapping from hashable keys to values, insertion-ordered since Python 3.7.", usage: "Use for key-value lookups; keys must be hashable (immutable).", example: "ages = {\"Ada\": 36}\nages[\"Ada\"]  # 36", related: ["insertion-ordered dicts (3.7+)"] },
"set": { category: "keyword", summary: "A built-in mutable, unordered collection of unique hashable elements.", usage: "Use for membership tests and set algebra (union/intersection/difference).", example: "s = {1, 2, 2, 3}\nprint(s)  # {1, 2, 3}" },
"append()": { category: "method", summary: "Adds a single element to the end of a list, in place.", usage: "The standard way to grow a list one item at a time inside a loop.", example: "items = []\nitems.append(1)" },
"sort()/sorted()": { category: "method", summary: "list.sort() sorts a list in place; the built-in sorted() returns a new sorted list from any iterable.", usage: "Both accept key= for a custom sort key and reverse=True for descending order.", example: "nums.sort(reverse=True)\nordered = sorted(words, key=len)" },
"len()": { category: "method", summary: "Returns the number of items in a container (or characters in a string).", usage: "Works on anything implementing __len__: list, str, dict, set, tuple.", example: "len([1, 2, 3])  # 3", related: ["__len__"] },
"[x for x in ...]": { category: "keyword", summary: "List comprehension syntax: builds a new list from an existing iterable in one expression.", usage: "Prefer it over a manual append-loop for simple transformations/filters.", example: "squares = [x * x for x in range(5)]\nevens = [x for x in range(10) if x % 2 == 0]" },
"{k:v for ...}": { category: "keyword", summary: "Dict comprehension syntax: builds a new dict from an iterable in one expression.", usage: "Use to transform or filter key/value pairs concisely.", example: "squares = {x: x * x for x in range(5)}" },
"collections.defaultdict()": { category: "method", summary: "A dict subclass that auto-creates a default value for missing keys instead of raising KeyError.", usage: "Great for grouping/counting without checking `if key not in dict` every time.", example: "from collections import defaultdict\ngroups = defaultdict(list)\ngroups[\"a\"].append(1)" },
"collections.Counter()": { category: "method", summary: "A dict subclass specialized for counting hashable items.", usage: "Build one from any iterable to get frequency counts, plus helpers like most_common().", example: "from collections import Counter\nCounter(\"aabbc\").most_common(1)  # [('a', 2)]" },
"collections.deque()": { category: "method", summary: "A double-ended queue with O(1) appends/pops from both ends.", usage: "Use instead of a list when you need fast insertion/removal at the front (a list's pop(0) is O(n)).", example: "from collections import deque\nq = deque([1, 2])\nq.appendleft(0)" },
"dataclasses.dataclass": { category: "method", summary: "A class decorator that auto-generates __init__, __repr__, and __eq__ from type-annotated fields.", usage: "Use for simple data-holding classes instead of writing boilerplate __init__/__repr__ by hand.", example: "from dataclasses import dataclass\n\n@dataclass\nclass Point:\n    x: int\n    y: int" },
"hashability": { category: "concept", summary: "Whether an object has a stable __hash__ (and consistent __eq__), which is required to be a dict key or set member.", usage: "Immutable built-ins (int/str/tuple) are hashable; mutable ones (list/dict/set) are not.", related: ["__hash__", "mutability vs immutability"] },
"namedtuple / dataclass records": { category: "concept", summary: "Two lightweight ways to define a small, named record type without a full hand-written class.", usage: "Use namedtuple for an immutable tuple-like record; use @dataclass when you also want mutability or more features.", related: ["dataclasses.dataclass"] },
"set operations (union/intersection/difference)": { category: "concept", summary: "Sets support algebraic operators: | (union), & (intersection), - (difference), ^ (symmetric difference).", usage: "Use to compare two collections of unique items without writing manual loops.", example: "a = {1, 2, 3}\nb = {2, 3, 4}\nprint(a & b)  # {2, 3}" },
"dynamic array amortized growth": { category: "theory", summary: "A Python list over-allocates extra capacity when it grows, so most append() calls are O(1); occasional reallocation is amortized across many appends.", usage: "Explains why appending is fast in practice even though a resize is technically O(n)." },
"hash table internals": { category: "theory", summary: "Dicts and sets are implemented as hash tables: a key's hash() determines its bucket, and __eq__ resolves collisions.", usage: "Explains the hashability requirement and why average-case lookup is O(1).", related: ["hashability"] },
"insertion-ordered dicts (3.7+)": { category: "theory", summary: "Since Python 3.7, dicts preserve the order keys were first inserted, as a language guarantee (not just an implementation detail).", usage: "You can rely on iteration order matching insertion order in modern Python." },

/* ---------------------------------------------------------------- */
/* Topic 5 — Files, Exceptions, Regex                                 */
/* ---------------------------------------------------------------- */
"open()": { category: "keyword", summary: "Opens a file and returns a file object.", usage: "Almost always use it with a `with` block so the file is closed automatically.", example: "with open(\"data.txt\") as f:\n    text = f.read()" },
"with": { category: "keyword", summary: "Starts a context-managed block, guaranteeing cleanup (via __exit__) even if an exception occurs.", usage: "Use for files, locks, or any resource that needs reliable setup/teardown.", example: "with open(\"data.txt\") as f:\n    ...", related: ["__enter__", "__exit__"] },
"as": { category: "keyword", summary: "Binds a name to the result of a `with`/`except`/`import` clause.", usage: "`with open(...) as f:`, `except ValueError as e:`, `import numpy as np`.", example: "except ValueError as e:\n    print(e)" },
"try": { category: "keyword", summary: "Starts a block whose exceptions can be caught by a following except clause.", usage: "Wrap only the code that might actually fail, to avoid hiding unrelated bugs.", example: "try:\n    risky()\nexcept ValueError:\n    print(\"bad value\")" },
"except": { category: "keyword", summary: "Catches exceptions of a given type (or types) raised in the preceding try block.", usage: "Be specific about the exception type — bare `except:` swallows everything, including typos.", example: "except (ValueError, TypeError) as e:\n    ..." },
"finally": { category: "keyword", summary: "A block that always runs after try/except, whether or not an exception occurred.", usage: "Use for cleanup that must happen regardless of success or failure.", example: "try:\n    f = open(\"x\")\nfinally:\n    f.close()" },
"raise": { category: "keyword", summary: "Throws an exception, either a new one or re-raising the current one.", usage: "Raise the most specific exception type that fits; use `raise ... from ...` to chain a cause.", example: "if age < 0:\n    raise ValueError(\"age can't be negative\")", related: ["exception chaining (raise ... from ...)"] },
"Exception": { category: "keyword", summary: "The base class for almost all built-in and user-defined exceptions (excluding a few system-exiting ones).", usage: "Subclass it to define your own exception types; avoid catching it directly unless you really mean \"anything\".", example: "class InsufficientFunds(Exception):\n    pass" },
"re.search()": { category: "method", summary: "Scans a string for the first location where a regex pattern matches, anywhere in the string.", usage: "Returns a Match object (or None); use .group() to pull out the matched text.", example: "import re\nm = re.search(r\"\\d+\", \"room 42\")\nm.group()  # '42'" },
"re.findall()": { category: "method", summary: "Returns a list of all non-overlapping matches of a pattern in a string.", usage: "Use when you want every match, not just the first.", example: "re.findall(r\"\\d+\", \"a1 b22 c3\")  # ['1', '22', '3']" },
"re.compile()": { category: "method", summary: "Pre-compiles a regex pattern into a reusable pattern object.", usage: "Use when applying the same pattern repeatedly, for both clarity and a small performance win.", example: "pattern = re.compile(r\"\\d+\")\npattern.findall(\"a1 b2\")" },
"re.match()": { category: "method", summary: "Like re.search(), but only checks for a match at the very start of the string.", usage: "Use when the pattern must anchor to the beginning; otherwise prefer re.search().", example: "re.match(r\"\\d+\", \"42 apples\")  # matches\nre.match(r\"\\d+\", \"apples 42\")  # None" },
"re.sub()": { category: "method", summary: "Replaces all matches of a pattern in a string with a replacement string (or function).", usage: "Use for regex-based find-and-replace.", example: "re.sub(r\"\\s+\", \" \", \"a   b\\tc\")  # 'a b c'" },
"contextlib.contextmanager": { category: "method", summary: "A decorator that turns a generator function into a context manager, without writing a full class.", usage: "Write setup code, `yield`, then teardown code — much shorter than __enter__/__exit__ for simple cases.", example: "from contextlib import contextmanager\n\n@contextmanager\ndef timer():\n    print(\"start\")\n    yield\n    print(\"end\")" },
"exception chaining (raise ... from ...)": { category: "concept", summary: "Attaches an explicit cause to a newly raised exception, preserving the original traceback context.", usage: "Use when translating a low-level exception into a more meaningful one, without losing the original cause.", example: "try:\n    int(\"x\")\nexcept ValueError as e:\n    raise RuntimeError(\"bad config\") from e" },
"exception hierarchies": { category: "concept", summary: "Exception classes form an inheritance tree (e.g. ValueError and TypeError both descend from Exception).", usage: "Catch a base class to handle a whole family of related errors, or define your own hierarchy for a library." },
"custom context managers": { category: "concept", summary: "Any object implementing __enter__/__exit__ (or a @contextmanager generator) can be used in a `with` block.", usage: "Write one to guarantee setup/teardown for a resource that isn't a plain file, e.g. a lock or a temp directory.", related: ["__enter__", "__exit__", "contextlib.contextmanager"] },
"regex named groups": { category: "concept", summary: "Regex groups can be named with (?P<name>...) and retrieved by name instead of position.", usage: "Improves readability when a pattern has several capture groups.", example: "m = re.search(r\"(?P<year>\\d{4})-(?P<month>\\d{2})\", \"2024-05\")\nm.group(\"year\")  # '2024'" },
"traceback propagation up the call stack": { category: "theory", summary: "An unhandled exception unwinds the call stack frame by frame, accumulating a traceback, until caught or the program exits.", usage: "Explains why a try/except higher up the call chain can still catch an error raised deep inside a helper function." },
"backtracking regex engine": { category: "theory", summary: "Python's `re` module compiles patterns into a backtracking state machine that tries alternatives and undoes choices on failure.", usage: "Explains both how regex matching works and why certain patterns can be pathologically slow." },
"catastrophic backtracking": { category: "theory", summary: "A regex pattern with nested/ambiguous repetition can cause the backtracking engine to try exponentially many paths on certain inputs.", usage: "Avoid nested quantifiers like (a+)+ on user-controlled input; simplify the pattern or use a bounded alternative." },

/* ---------------------------------------------------------------- */
/* Topic 6 — OOP I                                                    */
/* ---------------------------------------------------------------- */
"class": { category: "keyword", summary: "Defines a new class (a blueprint for objects).", usage: "Followed by a name and an indented body containing methods and class-level attributes.", example: "class Dog:\n    def __init__(self, name):\n        self.name = name" },
"self": { category: "keyword", summary: "The conventional name for a method's first parameter, bound to the instance it was called on.", usage: "Always the first parameter of an instance method; use it to read/write the instance's attributes.", example: "def bark(self):\n    print(f\"{self.name} says woof\")" },
"__init__": { category: "dunder", summary: "The initializer, called automatically right after a new instance is created.", usage: "Use it to set up instance attributes from the constructor arguments.", example: "class Point:\n    def __init__(self, x, y):\n        self.x, self.y = x, y" },
"@property": { category: "keyword", summary: "A decorator that turns a method into a read-only attribute, computed on access.", usage: "Use to expose a computed value with attribute syntax (obj.value, no parentheses), or to add validation later without breaking existing code.", example: "class Circle:\n    def __init__(self, r):\n        self._r = r\n    @property\n    def area(self):\n        return 3.14159 * self._r ** 2" },
"@x.setter": { category: "keyword", summary: "Pairs with @property to define what happens when the property is assigned to.", usage: "Use to validate or transform a value on assignment while keeping plain attribute syntax at call sites.", example: "@x.setter\ndef x(self, value):\n    if value < 0:\n        raise ValueError(\"must be >= 0\")\n    self._x = value" },
"@staticmethod": { category: "keyword", summary: "A decorator marking a method that doesn't receive self or cls — just a regular function namespaced inside the class.", usage: "Use for helper logic that's related to the class conceptually but doesn't need instance or class state.", example: "class MathUtils:\n    @staticmethod\n    def add(a, b):\n        return a + b" },
"@classmethod": { category: "keyword", summary: "A decorator marking a method that receives the class itself (cls) instead of an instance.", usage: "Commonly used for alternative constructors that build and return an instance.", example: "class Point:\n    @classmethod\n    def origin(cls):\n        return cls(0, 0)" },
"cls": { category: "keyword", summary: "The conventional name for a classmethod's first parameter, bound to the class it was called on.", usage: "Use `cls(...)` inside a classmethod to construct an instance in a way that also works for subclasses.", related: ["@classmethod"] },
"__get__/__set__ (preview)": { category: "dunder", summary: "The descriptor protocol methods that power @property under the hood.", usage: "You typically use @property instead of implementing these directly, unless you're building a reusable descriptor.", related: ["descriptors"] },
"encapsulation": { category: "concept", summary: "Bundling data and the methods that operate on it together, and controlling access to that data.", usage: "Python signals \"internal use\" by convention (a leading underscore) rather than enforcing true privacy." },
"instance vs class attributes": { category: "concept", summary: "Instance attributes live on self and differ per object; class attributes are defined in the class body and shared by all instances (until shadowed).", usage: "Use class attributes for shared constants/defaults, instance attributes for per-object state.", example: "class Dog:\n    species = \"Canis familiaris\"  # class attribute\n    def __init__(self, name):\n        self.name = name          # instance attribute" },
"__slots__ memory savings": { category: "concept", summary: "Declaring __slots__ on a class replaces each instance's __dict__ with fixed, fixed-size storage for named attributes.", usage: "Use on classes you'll instantiate in large numbers to cut memory use — but it disables adding arbitrary new attributes later.", example: "class Point:\n    __slots__ = (\"x\", \"y\")" },
"descriptors": { category: "concept", summary: "Objects implementing __get__ (and optionally __set__/__delete__) that customize attribute access when placed on a class.", usage: "@property, @staticmethod, and @classmethod are all built on descriptors; write your own for reusable validated-attribute logic." },
"attribute lookup order (instance → class → MRO)": { category: "theory", summary: "obj.attr first checks the instance's __dict__, then the class's __dict__, then walks the class's MRO.", usage: "Explains why setting an instance attribute shadows a class attribute of the same name." },
"descriptor protocol (__get__/__set__)": { category: "theory", summary: "Attribute access on a class-level descriptor object is redirected through its __get__/__set__ methods instead of plain dict lookup.", usage: "This is precisely how @property, @staticmethod, and @classmethod are implemented internally." },

/* ---------------------------------------------------------------- */
/* Topic 7 — OOP II                                                   */
/* ---------------------------------------------------------------- */
"class Child(Parent)": { category: "keyword", summary: "Syntax for inheritance: Child inherits attributes and methods from Parent.", usage: "Use when Child genuinely \"is a\" Parent; otherwise prefer composition.", example: "class Dog(Animal):\n    def speak(self):\n        return \"Woof\"" },
"super()": { category: "method", summary: "Returns a proxy that forwards method calls along the class's MRO, typically to the parent class.", usage: "Call it in __init__ (and other overridden methods) to run the parent's version before/after your own logic.", example: "class Dog(Animal):\n    def __init__(self, name):\n        super().__init__(name)", related: ["Method Resolution Order (C3 linearization)"] },
"abc": { category: "module", summary: "Standard library module providing tools (ABC, @abstractmethod) for defining abstract base classes.", usage: "Import ABC to subclass from, and @abstractmethod to mark methods subclasses must implement.", example: "from abc import ABC, abstractmethod" },
"ABC": { category: "keyword", summary: "Base class from the abc module that marks a class as abstract — it cannot be instantiated directly.", usage: "Subclass it to define an interface that concrete subclasses must implement.", example: "class Shape(ABC):\n    @abstractmethod\n    def area(self): ..." },
"@abstractmethod": { category: "keyword", summary: "Marks a method as required: subclasses of an ABC must override it or they can't be instantiated.", usage: "Use to define an interface's required methods without providing an implementation.", example: "class Shape(ABC):\n    @abstractmethod\n    def area(self): ..." },
"polymorphism": { category: "concept", summary: "Different classes responding to the same method call/operator in their own way.", usage: "In Python this mostly falls out of duck typing — no special syntax needed, just implement the same method name." },
"duck typing": { category: "concept", summary: "\"If it walks like a duck and quacks like a duck...\" — an object's suitability is judged by the methods/attributes it has, not its declared type.", usage: "Write code against behavior (e.g. \"has a .read() method\") rather than checking isinstance() everywhere." },
"composition vs inheritance": { category: "concept", summary: "Two ways to reuse code: inheritance (\"is-a\", subclassing) vs composition (\"has-a\", holding another object as an attribute).", usage: "Prefer composition when the relationship isn't a true is-a, to avoid fragile deep class hierarchies." },
"mixins": { category: "concept", summary: "Small classes designed to be combined via multiple inheritance to add one specific piece of behavior.", usage: "Use for optional, orthogonal capabilities (e.g. a LoggingMixin) rather than a single monolithic base class." },
"Protocol structural typing": { category: "concept", summary: "typing.Protocol lets you define an interface by the methods/attributes an object must have, without requiring explicit inheritance.", usage: "Use for static-typing duck-typed code — a class \"matches\" a Protocol just by having the right shape.", example: "from typing import Protocol\n\nclass Readable(Protocol):\n    def read(self) -> str: ..." },
"Method Resolution Order (C3 linearization)": { category: "theory", summary: "The deterministic order Python searches base classes for an attribute/method, computed by the C3 linearization algorithm and visible as Cls.__mro__.", usage: "Matters most with multiple inheritance, where it decides which parent's method super() actually calls." },
"diamond inheritance": { category: "theory", summary: "A class hierarchy where two parent classes share a common ancestor, forming a diamond shape.", usage: "Python's C3-linearized MRO resolves this consistently (each class appears once, in a well-defined order), unlike some other languages." },

/* ---------------------------------------------------------------- */
/* Topic 8 — The Python Data Model                                    */
/* ---------------------------------------------------------------- */
"__repr__": { category: "dunder", summary: "Returns an unambiguous, developer-facing string representation of an object, used by repr() and the REPL.", usage: "Aim for output that could recreate the object, e.g. `Point(x=1, y=2)`.", example: "def __repr__(self):\n    return f\"Point(x={self.x}, y={self.y})\"" },
"__str__": { category: "dunder", summary: "Returns a human-readable string representation, used by str() and print().", usage: "Falls back to __repr__ if not defined; define it separately when you want friendlier output for end users." },
"__eq__": { category: "dunder", summary: "Defines behavior for the == operator between two objects.", usage: "Define alongside __hash__ if instances need to be dict keys or set members; otherwise objects compare by identity by default.", related: ["__hash__"] },
"__add__": { category: "dunder", summary: "Defines behavior for the + operator (left-hand side).", usage: "Implement to make custom objects support addition; return NotImplemented if the other operand's type isn't supported.", related: ["reflected operators & NotImplemented"] },
"__len__": { category: "dunder", summary: "Defines behavior for len(obj), and is also used by truthiness checks when __bool__ isn't defined.", usage: "Implement on any custom container so len() and `if obj:` work naturally." },
"__getitem__": { category: "dunder", summary: "Defines behavior for obj[key] (indexing and slicing).", usage: "Implement to make a custom class support subscript access; combine with __setitem__ for assignment too." },
"__iter__": { category: "dunder", summary: "Returns an iterator for the object, making it usable in a for loop.", usage: "Implement on a custom collection so `for x in obj:` works; typically returns self (if __next__ is also defined) or a generator." },
"__contains__": { category: "dunder", summary: "Defines behavior for the `in` operator.", usage: "Implement for an efficient membership check; without it, Python falls back to iterating with __iter__." },
"__call__": { category: "dunder", summary: "Makes instances of the class callable like a function: obj(...).", usage: "Useful for objects that wrap a single operation with configurable state (a callable class instead of a closure)." },
"__bool__": { category: "dunder", summary: "Defines an object's truthiness for use in conditions.", usage: "Implement to control `if obj:` directly; if absent, Python falls back to `len(obj) != 0`.", related: ["truthiness"] },
"__enter__": { category: "dunder", summary: "Called when entering a `with` block; its return value is bound by `as`.", usage: "Implement alongside __exit__ to make an object usable as a context manager.", related: ["with", "__exit__"] },
"__exit__": { category: "dunder", summary: "Called when leaving a `with` block, even if an exception occurred inside it.", usage: "Use it for cleanup (closing a file, releasing a lock); return True to suppress a propagating exception.", related: ["with", "__enter__"] },
"__hash__": { category: "dunder", summary: "Returns an integer hash used to place the object in dicts/sets.", usage: "If you define __eq__, also define __hash__ consistently (equal objects must have equal hashes) — or explicitly set __hash__ = None to mark instances unhashable.", related: ["hashability", "__eq__"] },
"__radd__": { category: "dunder", summary: "The \"reflected\" version of __add__, tried when `left + right` and left's __add__ returned NotImplemented.", usage: "Implement it so your custom type also supports being on the right-hand side of +, e.g. `5 + my_obj`.", related: ["reflected operators & NotImplemented"] },
"operator overloading": { category: "concept", summary: "Giving built-in operators (+, ==, [], len(), ...) custom meaning for your own classes via dunder methods.", usage: "Implement only the operators that make genuine sense for the type — don't overload + to mean something surprising." },
"protocols vs explicit inheritance": { category: "concept", summary: "Python often prefers \"if it has the right dunder methods, it qualifies\" over requiring a specific base class.", usage: "You don't need to inherit from a special base class to be iterable, callable, or a context manager — just implement the matching dunders." },
"dunder lookup happens on the type, not the instance": { category: "theory", summary: "`len(x)` really calls `type(x).__len__(x)` — special methods are looked up on the class, bypassing instance attributes.", usage: "Explains why monkey-patching a dunder onto a single instance (`obj.__len__ = ...`) silently has no effect." },
"reflected operators & NotImplemented": { category: "theory", summary: "If `a + b` returns NotImplemented from a.__add__, Python retries with b.__radd__(a) before finally raising TypeError.", usage: "Return NotImplemented (not raise an exception) from an operator dunder when you don't support the other operand's type.", related: ["__radd__"] },
"iterator protocol requires StopIteration": { category: "theory", summary: "A custom iterator's __next__ must raise StopIteration once exhausted — that's the exact signal a for-loop is watching for.", usage: "Forgetting to raise it turns your iterator into an infinite loop when consumed by a for statement." },

/* ---------------------------------------------------------------- */
/* Topic 9 — OS, JSON, Datetime, XML                                  */
/* ---------------------------------------------------------------- */
"os.listdir": { category: "keyword", summary: "Returns a list of entry names (files and directories) in a given directory.", usage: "Use for a flat listing of one directory; use os.walk() for recursive traversal.", example: "import os\nos.listdir(\".\")" },
"os.path": { category: "keyword", summary: "Submodule with functions for manipulating filesystem paths as strings (join, exists, splitext, ...).", usage: "Use os.path.join() to build paths portably instead of concatenating with '/'; consider pathlib for a more modern API.", example: "import os\nos.path.join(\"a\", \"b.txt\")  # 'a/b.txt'", related: ["pathlib as the modern os.path alternative"] },
"json.load/dump": { category: "keyword", summary: "json.load(file) reads JSON from an open file into Python objects; json.dump(obj, file) writes Python objects out as JSON.", usage: "Use the *_s variants (loads/dumps) when working with strings instead of file objects.", example: "import json\nwith open(\"data.json\") as f:\n    data = json.load(f)" },
"datetime.now/isoformat": { category: "keyword", summary: "datetime.now() gets the current local date and time; .isoformat() renders a datetime as a standard ISO-8601 string.", usage: "Use isoformat() when you need a sortable, unambiguous, serializable timestamp string.", example: "from datetime import datetime\ndatetime.now().isoformat()" },
"ElementTree.parse/findall": { category: "keyword", summary: ".parse() reads an XML file into an in-memory element tree; .findall() searches that tree for matching child elements.", usage: "Use findall() with an XPath-like path string to pull out specific elements.", example: "import xml.etree.ElementTree as ET\ntree = ET.parse(\"data.xml\")\ntree.findall(\".//item\")" },
"os.walk()": { category: "method", summary: "Recursively walks a directory tree, yielding (dirpath, dirnames, filenames) for each directory visited.", usage: "Use for processing an entire directory tree instead of one level at a time.", example: "import os\nfor root, dirs, files in os.walk(\".\"):\n    print(root, files)" },
"pathlib.Path": { category: "method", summary: "An object-oriented representation of a filesystem path, with methods replacing most os.path functions.", usage: "Build paths with the / operator and call methods like .exists()/.read_text() directly on the path object.", example: "from pathlib import Path\np = Path(\"data\") / \"file.txt\"\np.exists()" },
"json.dumps(default=...)": { category: "method", summary: "Serializes a Python object to a JSON string; the default= callback lets you convert otherwise-non-serializable objects.", usage: "Use default= to handle custom classes, dates, etc. that json doesn't know how to serialize natively.", example: "import json\njson.dumps(obj, default=lambda o: o.__dict__)" },
"pathlib as the modern os.path alternative": { category: "concept", summary: "pathlib.Path wraps path manipulation in an object with methods and the / operator, instead of passing raw strings to os.path functions.", usage: "Prefer pathlib in new code for more readable path-building and built-in convenience methods." },
"timezone-aware vs naive datetimes": { category: "concept", summary: "A \"naive\" datetime has no timezone attached; an \"aware\" one does, and can be safely compared/converted across timezones.", usage: "Prefer aware datetimes (e.g. via zoneinfo) for anything involving multiple timezones or serialization." },
"JSON recursive-descent parsing": { category: "theory", summary: "The json module parses text by recursively descending into nested objects/arrays, mapping JSON types onto Python dict/list/str/int/float/bool/None.", usage: "Explains why arbitrary Python objects (that aren't one of those types) need a default= hook to be serialized." },
"DOM-style (ElementTree) vs streaming (SAX) XML parsing": { category: "theory", summary: "ElementTree loads the entire XML document into an in-memory tree (DOM-style); a streaming parser (SAX) processes it incrementally without holding it all in memory.", usage: "Use ElementTree for typical file sizes; consider a streaming parser only for very large XML documents." },

/* ---------------------------------------------------------------- */
/* Topic 10 — Pandas                                                  */
/* ---------------------------------------------------------------- */
"pd.read_csv": { category: "keyword", summary: "Reads a CSV file into a pandas DataFrame.", usage: "The most common way to load tabular data; supports many options (delimiter, dtype, parse_dates, ...).", example: "import pandas as pd\ndf = pd.read_csv(\"data.csv\")" },
"df.head()": { category: "keyword", summary: "Returns the first n rows of a DataFrame (default 5), for a quick peek at the data.", usage: "Use immediately after loading data to sanity-check its shape and columns.", example: "df.head(3)" },
"df.groupby()": { category: "keyword", summary: "Splits a DataFrame into groups based on one or more columns' values, for aggregation.", usage: "Chain an aggregation like .sum()/.mean()/.count() after groupby() to summarize each group.", example: "df.groupby(\"category\")[\"amount\"].sum()" },
"df.sort_values()": { category: "keyword", summary: "Returns a DataFrame sorted by the values in one or more columns.", usage: "Pass ascending=False for descending order, or a list of columns for a multi-key sort.", example: "df.sort_values(\"price\", ascending=False)" },
"df.merge()": { category: "keyword", summary: "Joins two DataFrames together based on common columns or indexes, like a SQL join.", usage: "Specify on= (or left_on/right_on) and how= (\"inner\"/\"left\"/\"right\"/\"outer\").", example: "orders.merge(customers, on=\"customer_id\", how=\"left\")" },
"df.info()": { category: "method", summary: "Prints a summary of a DataFrame: column names, dtypes, non-null counts, and memory usage.", usage: "Use right after loading data to check for missing values and unexpected types." },
"df.describe()": { category: "method", summary: "Generates summary statistics (count, mean, std, min/max, quartiles) for numeric columns.", usage: "Use for a fast statistical overview of a dataset." },
"df.apply()": { category: "method", summary: "Applies a function along an axis of the DataFrame (row-wise or column-wise).", usage: "Use for logic that can't be expressed as a built-in vectorized operation — but prefer vectorized operations when possible, since apply() is much slower.", example: "df[\"upper\"] = df[\"name\"].apply(str.upper)", related: ["vectorization vs per-row Python loops"] },
"df.pivot_table()": { category: "method", summary: "Reshapes data into a spreadsheet-style pivot table, aggregating values by row/column categories.", usage: "Use to summarize data across two categorical dimensions at once.", example: "df.pivot_table(values=\"sales\", index=\"region\", columns=\"month\", aggfunc=\"sum\")" },
"boolean indexing": { category: "concept", summary: "Filtering a DataFrame/Series with a boolean array, typically produced by a comparison expression.", usage: "The idiomatic way to filter rows in pandas instead of writing a manual loop.", example: "df[df[\"age\"] > 18]" },
"multi-indexing": { category: "concept", summary: "A DataFrame or Series can have a hierarchical (multi-level) index made of tuples instead of a single flat index.", usage: "Useful for representing grouped/nested data, e.g. after a groupby() on multiple columns." },
"dtype-based memory optimization": { category: "concept", summary: "Choosing narrower/more specific dtypes (e.g. category, int32) for columns can drastically cut a DataFrame's memory footprint.", usage: "Check df.info(memory_usage=\"deep\") and convert low-cardinality string columns to \"category\" dtype." },
"columnar storage backed by NumPy arrays": { category: "theory", summary: "Each DataFrame column is backed by a contiguous NumPy array of a single dtype, not a list of Python objects.", usage: "Explains both pandas' speed and why mixed-type columns (dtype=object) are slower than typed ones." },
"vectorization vs per-row Python loops": { category: "theory", summary: "Vectorized pandas/NumPy operations run in compiled C over a whole array at once; looping row-by-row falls back to slow per-element Python bytecode.", usage: "Always look for a vectorized equivalent (arithmetic, .str methods, boolean masks) before reaching for .apply() or a manual loop." },

/* ---------------------------------------------------------------- */
/* Topic 11 — OpenCV                                                  */
/* ---------------------------------------------------------------- */
"cv2.imread": { category: "keyword", summary: "Reads an image file from disk into a NumPy array (in BGR order by default).", usage: "Check the return value isn't None — it fails silently (returns None) on a bad path instead of raising.", example: "import cv2\nimg = cv2.imread(\"photo.jpg\")" },
"cv2.imwrite": { category: "keyword", summary: "Writes a NumPy array image out to a file, inferring format from the file extension.", usage: "Pass the array and a destination path; returns True/False for success.", example: "cv2.imwrite(\"out.png\", img)" },
"cv2.cvtColor": { category: "keyword", summary: "Converts an image between color spaces (e.g. BGR to grayscale or RGB).", usage: "Use cv2.COLOR_BGR2GRAY or cv2.COLOR_BGR2RGB as the conversion code, most commonly.", example: "gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)", related: ["BGR vs RGB channel order"] },
"cv2.resize": { category: "keyword", summary: "Resizes an image to a given size or scale factor.", usage: "Pass a (width, height) tuple, or fx/fy scale factors; choose an interpolation method for quality vs speed.", example: "small = cv2.resize(img, (100, 100))" },
"cv2.rectangle": { category: "keyword", summary: "Draws a rectangle onto an image, in place.", usage: "Pass the image, top-left and bottom-right corner points, a BGR color tuple, and a line thickness.", example: "cv2.rectangle(img, (10, 10), (50, 50), (0, 255, 0), 2)" },
"image.shape": { category: "keyword", summary: "A NumPy array attribute giving an image's dimensions as (height, width, channels).", usage: "Use to check an image's size/channel count before processing it.", example: "h, w, c = img.shape" },
"cv2.Canny()": { category: "method", summary: "Detects edges in an image using the Canny edge-detection algorithm.", usage: "Typically run on a grayscale image, passing two threshold values that control sensitivity.", example: "edges = cv2.Canny(gray, 100, 200)" },
"cv2.findContours()": { category: "method", summary: "Finds the outlines (contours) of connected white regions in a binary image.", usage: "Run after thresholding/edge detection to locate distinct shapes or objects.", example: "contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)" },
"cv2.GaussianBlur()": { category: "method", summary: "Smooths an image using a Gaussian kernel, reducing noise and detail.", usage: "Often applied before edge detection to reduce false edges from noise.", example: "blurred = cv2.GaussianBlur(img, (5, 5), 0)" },
"cv2.CascadeClassifier": { category: "method", summary: "Loads a pre-trained Haar cascade model for detecting objects like faces.", usage: "Load a .xml cascade file, then call .detectMultiScale() on a grayscale image.", example: "face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + \"haarcascade_frontalface_default.xml\")" },
"thresholding": { category: "concept", summary: "Converting a grayscale image to binary (black/white) by classifying each pixel above or below a cutoff value.", usage: "A common first step before contour detection or shape analysis." },
"convolution filtering": { category: "concept", summary: "Sliding a small kernel matrix over an image to blur, sharpen, or detect edges, pixel by pixel.", usage: "Most OpenCV filters (blur, Canny, Sobel) are built on this idea under the hood." },
"images as NumPy arrays (height × width × channels)": { category: "theory", summary: "An OpenCV image is just a 3-D NumPy array — rows × columns × color channels — so ordinary NumPy slicing/indexing works on it directly.", usage: "You can crop an image with plain array slicing: `img[y1:y2, x1:x2]`." },
"BGR vs RGB channel order": { category: "theory", summary: "OpenCV stores color images with Blue first, not Red — the opposite of most other libraries (PIL, matplotlib).", usage: "Convert with cv2.cvtColor(img, cv2.COLOR_BGR2RGB) before displaying an OpenCV image in a library that expects RGB." },

/* ---------------------------------------------------------------- */
/* Topic 12 — Requests + Threading                                   */
/* ---------------------------------------------------------------- */
"requests.get()": { category: "keyword", summary: "Sends an HTTP GET request and returns a Response object.", usage: "Pass params= for query parameters, headers= for custom headers, timeout= to avoid hanging forever.", example: "import requests\nr = requests.get(\"https://api.example.com/data\", timeout=5)" },
"response.json()": { category: "keyword", summary: "Parses a Response body as JSON and returns the resulting Python object.", usage: "Raises an error if the body isn't valid JSON; check response.status_code first if unsure.", example: "data = requests.get(url).json()" },
"threading.Thread": { category: "keyword", summary: "Represents a separate thread of execution running a target function concurrently.", usage: "Construct with target= (and optionally args=), then call .start(); remember the GIL limits real CPU parallelism.", example: "import threading\nt = threading.Thread(target=worker)\nt.start()", related: ["Global Interpreter Lock (GIL)"] },
".start()": { category: "keyword", summary: "Begins executing a Thread's target function in a new OS thread.", usage: "Call once per Thread object; calling it twice on the same thread raises an error." },
".join()": { category: "keyword", summary: "Blocks the calling thread until the target thread finishes.", usage: "Call after .start() when you need to wait for a background thread's work to complete before continuing." },
"threading.Lock": { category: "keyword", summary: "A mutual-exclusion lock used to protect shared state from concurrent access by multiple threads.", usage: "Acquire it (ideally with a `with lock:` block) around code that reads/modifies shared data from multiple threads.", example: "lock = threading.Lock()\nwith lock:\n    shared_counter += 1", related: ["race conditions & deadlocks"] },
"requests.post()": { category: "method", summary: "Sends an HTTP POST request, typically with a body (form data or JSON).", usage: "Use json= to send a JSON body automatically, or data= for form-encoded data.", example: "requests.post(url, json={\"name\": \"Ada\"})" },
"response.raise_for_status()": { category: "method", summary: "Raises an HTTPError if the response's status code indicates a client or server error (4xx/5xx).", usage: "Call it right after a request so failures surface immediately instead of being silently ignored.", example: "r = requests.get(url)\nr.raise_for_status()" },
"requests.Session()": { category: "method", summary: "A session object that persists settings (headers, cookies) and reuses the underlying TCP connection across multiple requests.", usage: "Use for making several requests to the same host — it's both faster and more convenient than separate requests.get() calls.", example: "s = requests.Session()\ns.headers.update({\"Authorization\": \"Bearer ...\"})\ns.get(url)" },
"concurrent.futures.ThreadPoolExecutor": { category: "method", summary: "Manages a pool of worker threads and lets you submit tasks that return Future objects.", usage: "Prefer it over manually creating raw Thread objects for running many similar concurrent tasks.", example: "from concurrent.futures import ThreadPoolExecutor\nwith ThreadPoolExecutor(max_workers=4) as ex:\n    results = list(ex.map(fetch, urls))" },
"sessions & connection reuse": { category: "concept", summary: "Reusing an HTTP connection (via requests.Session) avoids the overhead of a new TCP/TLS handshake for every request.", usage: "Use a Session whenever making multiple requests to the same server." },
"retry/backoff strategies": { category: "concept", summary: "Automatically retrying a failed request with increasing delays between attempts, to ride out transient failures.", usage: "Configure via requests' HTTPAdapter + urllib3 Retry, rather than hand-rolling retry loops." },
"race conditions & deadlocks": { category: "concept", summary: "A race condition is a bug from unsynchronized concurrent access to shared state; a deadlock is threads permanently blocked waiting on each other's locks.", usage: "Protect shared state with a Lock to avoid races; always acquire multiple locks in a consistent order to avoid deadlocks." },
"Global Interpreter Lock (GIL)": { category: "theory", summary: "A lock in CPython ensuring only one thread executes Python bytecode at a time, even on a multi-core machine.", usage: "Threading still helps for I/O-bound work (the GIL is released during I/O waits) but gives no speedup for CPU-bound work — use multiprocessing for that instead." },
"I/O-bound vs CPU-bound concurrency": { category: "theory", summary: "I/O-bound work spends most of its time waiting (network, disk); CPU-bound work spends it computing.", usage: "Use threads (or async) for I/O-bound concurrency; use multiple processes for CPU-bound parallelism, since the GIL blocks true CPU parallelism within one process." },

/* ---------------------------------------------------------------- */
/* Topic 13 — FastAPI                                                 */
/* ---------------------------------------------------------------- */
"FastAPI()": { category: "keyword", summary: "Creates the main application instance that routes and middleware are registered on.", usage: "Usually created once at module level and referenced by a name like `app`.", example: "from fastapi import FastAPI\napp = FastAPI()" },
"@app.get": { category: "keyword", summary: "Registers a function as the handler for GET requests to a given path.", usage: "Path and query parameters are declared as ordinary function parameters with type hints.", example: "@app.get(\"/items/{item_id}\")\ndef read_item(item_id: int):\n    return {\"id\": item_id}" },
"@app.post": { category: "keyword", summary: "Registers a function as the handler for POST requests to a given path.", usage: "Declare a Pydantic model as a parameter to automatically parse and validate the request body.", example: "@app.post(\"/items\")\ndef create_item(item: Item):\n    return item" },
"Depends": { category: "keyword", summary: "Declares a dependency that FastAPI resolves and injects automatically before calling the route function.", usage: "Use for shared logic like auth checks or a database session, without repeating it in every route.", example: "def get_db():\n    ...\n\n@app.get(\"/items\")\ndef list_items(db=Depends(get_db)):\n    ..." },
"uvicorn.run": { category: "keyword", summary: "Starts an ASGI server running a FastAPI app.", usage: "More commonly invoked from the command line (`uvicorn main:app --reload`) than called directly in code.", example: "import uvicorn\nuvicorn.run(app, host=\"0.0.0.0\", port=8000)" },
"TestClient()": { category: "method", summary: "A test client (from fastapi.testclient / Starlette) that calls a FastAPI app in-process, without running a real server.", usage: "Use in pytest tests to send requests to your API and assert on the response.", example: "from fastapi.testclient import TestClient\nclient = TestClient(app)\nassert client.get(\"/\").status_code == 200" },
"BaseModel (pydantic)": { category: "method", summary: "The base class for defining a Pydantic data model with typed fields.", usage: "Subclass it to describe a request/response shape; FastAPI uses it to validate and document your API automatically.", example: "from pydantic import BaseModel\n\nclass Item(BaseModel):\n    name: str\n    price: float" },
"path & query parameters": { category: "concept", summary: "Path parameters are embedded in the URL ({item_id}); query parameters come after ? in the URL.", usage: "FastAPI infers which is which from whether the parameter name appears in the route's path string." },
"dependency injection": { category: "concept", summary: "Declaring what a route needs (a DB session, the current user, ...) and letting the framework supply it, via Depends().", usage: "Keeps route functions focused on business logic instead of repeating setup code." },
"async def endpoints": { category: "concept", summary: "Route handlers can be declared with async def to use non-blocking I/O (await) inside them.", usage: "Use async def when a route needs to await other async calls (e.g. an async database driver); a plain def route still works fine for synchronous code." },
"automatic interactive docs (/docs)": { category: "concept", summary: "FastAPI auto-generates interactive Swagger UI (/docs) and ReDoc (/redoc) documentation from your route signatures and Pydantic models.", usage: "Use /docs during development to try out endpoints without writing a separate HTTP client." },
"ASGI vs WSGI": { category: "theory", summary: "WSGI (used by Flask/Django classic) handles one synchronous request at a time per worker; ASGI (used by FastAPI/Starlette) natively supports async and features like websockets.", usage: "Explains why FastAPI can handle async def endpoints and high-concurrency I/O-bound workloads efficiently." },
"type-hint-driven runtime validation": { category: "theory", summary: "FastAPI reads a route function's type hints (and Pydantic models) at runtime to validate, parse, and document incoming request data automatically.", usage: "This is why using accurate, specific type hints on route parameters directly improves both validation and the generated docs." },

/* ---------------------------------------------------------------- */
/* Topic 14 — Capstone                                                */
/* ---------------------------------------------------------------- */
"synthesizing multiple modules into one project": { category: "concept", summary: "Combining several of the tools from Topics 1-13 (e.g. requests + pandas + FastAPI) into a single working project.", usage: "Focus on integration: passing data cleanly between the pieces, not learning anything brand new." },

/* ---------------------------------------------------------------- */
/* Topic 15 — Appendix: The Tooling Itself                            */
/* ---------------------------------------------------------------- */
"argparse.ArgumentParser": { category: "keyword", summary: "Builds a command-line argument parser: define expected arguments/flags, then call .parse_args().", usage: "Use add_argument() for flags/positional args and add_subparsers() for git-style subcommands (like `cli.py test ...`).", example: "import argparse\np = argparse.ArgumentParser()\np.add_argument(\"name\")\nargs = p.parse_args()" },
"add_subparsers()": { category: "keyword", summary: "Adds support for subcommands (like `git commit` or `cli.py test`) to an ArgumentParser.", usage: "Call it once, then .add_parser(\"name\") for each subcommand, each with its own arguments.", example: "sub = parser.add_subparsers(dest=\"command\")\nsub.add_parser(\"list\")" },
"sys.exit()": { category: "keyword", summary: "Terminates the program, optionally with an exit code (0 = success, non-zero = failure).", usage: "Use the exit code to signal success/failure to shell scripts, CI, or git hooks that call your script.", example: "import sys\nsys.exit(0 if all_tests_passed else 1)" },
"if __name__ == \"__main__\":": { category: "keyword", summary: "A guard that only runs the following block when the file is executed directly, not when it's imported as a module.", usage: "Put your script's entry-point call (like main()) inside this guard.", example: "if __name__ == \"__main__\":\n    main()" },
"__main__": { category: "dunder", summary: "The special __name__ value a module gets when it is run directly (rather than imported).", usage: "Compare `__name__ == \"__main__\"` to distinguish \"run as a script\" from \"imported by something else\".", related: ["if __name__ == \"__main__\":"] },
"argparse": { category: "module", summary: "Standard library module for parsing command-line arguments and generating --help text automatically.", usage: "Used by tools/cli.py to implement the `list`/`test` subcommands and their flags." },
"subprocess": { category: "module", summary: "Standard library module for spawning and communicating with child processes.", usage: "Used by tools/core.py to launch `pytest` as a separate process and capture its output/exit code.", related: ["subprocess.run()"] },
"tkinter": { category: "module", summary: "Python's standard, built-in GUI toolkit, bundled with most Python installs.", usage: "Used by tools/gui.py to build the test-runner window, dropdown, buttons, and colored output pane." },
"venv": { category: "module", summary: "Standard library module for creating isolated Python virtual environments.", usage: "Run `python -m venv .venv` then activate it before `pip install -r requirements.txt`, so project dependencies don't collide with other projects.", example: "python -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt" },
"subprocess.run()": { category: "method", summary: "Runs a command as a child process and waits for it to finish, returning a CompletedProcess with stdout/stderr/returncode.", usage: "Pass capture_output=True and text=True to get its output back as strings instead of printing straight to the terminal.", example: "import subprocess, sys\nresult = subprocess.run([sys.executable, \"-m\", \"pytest\"], capture_output=True, text=True)" },
"result.returncode": { category: "method", summary: "The exit code a finished subprocess returned: 0 for success, non-zero for failure.", usage: "Forward it with sys.exit(result.returncode) so your own script's exit code mirrors the child process's." },
"result.stdout / result.stderr": { category: "method", summary: "The captured standard-output and standard-error text from a subprocess.run() call (when capture_output=True).", usage: "Print stdout for normal results and stderr separately (often to sys.stderr) so error output isn't mixed into normal output." },
"tkinter.Tk()": { category: "method", summary: "Creates the root window of a Tkinter application.", usage: "Usually subclassed (`class App(tk.Tk):`) so the whole window and its widgets live together in one class.", example: "import tkinter as tk\nroot = tk.Tk()\nroot.mainloop()" },
"ttk.Button()": { category: "method", summary: "Creates a themed (\"ttk\") clickable button widget.", usage: "Pass command= a function to call when clicked, and .pack()/.grid() it into a parent widget.", example: "ttk.Button(parent, text=\"Run\", command=on_click).pack()" },
"ttk.Combobox()": { category: "method", summary: "Creates a themed dropdown selection widget.", usage: "Pass values= a list of choices and state=\"readonly\" to prevent free-text typing.", example: "ttk.Combobox(parent, values=[\"a\", \"b\"], state=\"readonly\")" },
"scrolledtext.ScrolledText()": { category: "method", summary: "A multi-line text widget with a built-in scrollbar, from tkinter.scrolledtext.", usage: "Use for showing long, scrollable output like test results; use .tag_config()/.insert(..., tag) to color specific lines.", example: "from tkinter import scrolledtext\noutput = scrolledtext.ScrolledText(root)\noutput.tag_config(\"fail\", foreground=\"red\")" },
"threading.Thread()": { category: "method", summary: "Constructs a Thread object to run a function in the background without blocking the caller.", usage: "In a GUI, run slow work (like a subprocess call) on a background thread so the main event loop keeps responding.", example: "threading.Thread(target=run_tests, daemon=True).start()", related: ["Tkinter's single-threaded event loop model"] },
"separating shared logic from each frontend": { category: "concept", summary: "Both cli.py and gui.py import the same functions from core.py instead of each reimplementing how to run pytest.", usage: "Put behavior that must stay identical across multiple entry points in one shared module, and keep each frontend as a thin presentation layer over it." },
"non-blocking GUI via background threads": { category: "concept", summary: "Running a slow operation on a separate thread so the GUI's main loop keeps redrawing/responding to clicks while it runs.", usage: "Tkinter's gui.py runs pytest via a background threading.Thread, then uses self.after(0, ...) to safely update widgets once it finishes.", related: ["Tkinter's single-threaded event loop model"] },
"exit codes as pass/fail signals": { category: "concept", summary: "A process's numeric exit code (0 = success) is the standard way scripts, shells, and CI systems detect success or failure.", usage: "Always propagate a subprocess's real exit code with sys.exit(...) instead of always exiting 0." },
"git hooks gating commits on tests": { category: "concept", summary: "A git hook (e.g. pre-commit) can run a script and block the commit if that script exits non-zero.", usage: "Point a pre-commit hook at `python tools/cli.py test weekNN` for the week that changed, and let its exit code decide whether the commit proceeds." },
"ANSI escape codes & isatty() terminal detection": { category: "theory", summary: "Terminal text color comes from special escape sequences (e.g. \\033[32m for green); sys.stdout.isatty() detects whether output is going to a real terminal versus being piped/redirected.", usage: "Gate colored output on isatty() so redirected output (files, CI logs) doesn't get literal escape-code garbage." },
"Tkinter's single-threaded event loop model": { category: "theory", summary: "Tkinter processes all widget updates and events on one thread via mainloop(); blocking that thread (e.g. with a slow subprocess call) freezes the entire window.", usage: "Explains why gui.py offloads the pytest subprocess call to a background thread instead of calling it directly from a button handler." },

/* ---------------------------------------------------------------- */
/* Module names (the "Modules" badge group across topics)            */
/* ---------------------------------------------------------------- */
"itertools": { category: "module", summary: "Standard library module of fast, memory-efficient iterator building blocks (chain, product, groupby, ...).", usage: "Reach for it instead of hand-rolling loops for common iteration patterns like combinations or grouping.", example: "import itertools\nlist(itertools.chain([1, 2], [3, 4]))  # [1, 2, 3, 4]" },
"functools": { category: "module", summary: "Standard library module of higher-order function tools: caching, partial application, decorator helpers.", usage: "Reach for it when writing decorators (wraps) or memoizing pure functions (lru_cache).", related: ["functools.wraps()", "functools.lru_cache()"] },
"collections": { category: "module", summary: "Standard library module of specialized container datatypes beyond the built-in list/dict/set.", usage: "Use defaultdict/Counter/deque instead of reimplementing their behavior with a plain dict or list.", related: ["collections.defaultdict()", "collections.Counter()", "collections.deque()"] },
"dataclasses": { category: "module", summary: "Standard library module for the @dataclass decorator, which auto-generates boilerplate for simple record classes.", usage: "Use for classes that are mostly just typed fields plus __init__/__repr__/__eq__.", related: ["dataclasses.dataclass"] },
"re": { category: "module", summary: "Standard library module implementing regular expression matching.", usage: "Use for pattern-based text search, validation, and substitution.", related: ["re.search()", "re.compile()"] },
"contextlib": { category: "module", summary: "Standard library module of tools for working with context managers, including the @contextmanager decorator.", usage: "Use to build a `with`-compatible object without writing a full __enter__/__exit__ class.", related: ["contextlib.contextmanager"] },
"typing": { category: "module", summary: "Standard library module of tools for type hints: generics, Optional, Protocol, and more.", usage: "Import from it to write richer type annotations than plain built-in types allow.", related: ["Protocol structural typing"] },
"os": { category: "module", summary: "Standard library module for interacting with the operating system: files, directories, environment variables.", usage: "Use os.path/os.listdir/os.walk for filesystem work, or consider pathlib for a more modern API.", related: ["os.walk()", "pathlib as the modern os.path alternative"] },
"json": { category: "module", summary: "Standard library module for reading and writing JSON data.", usage: "Use load/dump for files, loads/dumps for strings.", related: ["json.load/dump", "json.dumps(default=...)"] },
"pathlib": { category: "module", summary: "Standard library module providing the object-oriented Path class for filesystem paths.", usage: "Prefer it over os.path string manipulation in new code.", related: ["pathlib.Path"] },
"datetime": { category: "module", summary: "Standard library module for representing and manipulating dates and times.", usage: "Use datetime.now() for the current time and timedelta for date arithmetic.", related: ["datetime.now/isoformat", "timezone-aware vs naive datetimes"] },
"xml.etree.ElementTree": { category: "module", summary: "Standard library module for parsing and building XML documents as a tree of elements.", usage: "Use .parse()/.findall() to read XML, or build a tree with Element()/SubElement() to write it.", related: ["ElementTree.parse/findall"] },
"pandas": { category: "module", summary: "Third-party library providing the DataFrame/Series data structures for tabular data analysis.", usage: "The standard tool for loading, cleaning, filtering, and summarizing tabular datasets in Python.", related: ["pd.read_csv", "columnar storage backed by NumPy arrays"] },
"opencv-python (cv2)": { category: "module", summary: "Third-party library (imported as cv2) for image and video processing, backed by the C++ OpenCV project.", usage: "Use for reading/writing images, color conversion, filtering, and computer-vision tasks.", related: ["images as NumPy arrays (height × width × channels)"] },
"numpy": { category: "module", summary: "Third-party library providing the ndarray type and fast vectorized numerical operations.", usage: "The foundation pandas and OpenCV are both built on; use it directly for numerical array work.", related: ["images as NumPy arrays (height × width × channels)", "columnar storage backed by NumPy arrays"] },
"requests": { category: "module", summary: "Third-party library providing a simple, high-level HTTP client.", usage: "The de-facto standard for making HTTP requests in Python, wrapping urllib3.", related: ["requests.get()", "requests.Session()"] },
"threading": { category: "module", summary: "Standard library module for running code concurrently using OS threads within one process.", usage: "Best suited to I/O-bound concurrency; remember the GIL limits CPU-bound speedups.", related: ["threading.Thread", "Global Interpreter Lock (GIL)"] },
"fastapi": { category: "module", summary: "Third-party web framework for building APIs quickly, using type hints for validation and auto-generated docs.", usage: "Built on Starlette (ASGI) and Pydantic; the framework used in Topic 13's local API endpoints.", related: ["FastAPI()", "ASGI vs WSGI"] },
"pydantic": { category: "module", summary: "Third-party library for data validation using Python type annotations.", usage: "FastAPI uses Pydantic BaseModel classes to validate request/response bodies automatically.", related: ["BaseModel (pydantic)"] },
"uvicorn": { category: "module", summary: "Third-party ASGI server used to actually run a FastAPI (or other ASGI) application.", usage: "Run your app with it in development (`uvicorn main:app --reload`) or production.", related: ["uvicorn.run"] },
"json + your choice of pandas/requests/opencv/FastAPI": { category: "module", summary: "The Capstone week doesn't introduce a new module — it's an invitation to combine whichever of the earlier topics' libraries fit your own project idea.", usage: "Pick the modules your capstone project actually needs; json is listed as the one near-universal building block for saving/loading results." }

};
